# syntax=docker/dockerfile:1.7
#
# AlphaLog PWA — Fly.io image (pre-built strategy)
#
# This image does NOT build the Next.js app. The build runs on the developer's
# machine via `npm run build` and produces .next/standalone + .next/static.
# This Dockerfile just packages those artefacts onto node:24-slim.
#
# Rationale: Fly's Depot builder runs OOM (~4GB) during `next build` because
# the codebase has 187 routes + Sentry + PWA wrappers + React 19. Local
# machines have plenty of RAM, so we shift the heavy lifting there.
#
# Workflow:
#   1. npm run build                  # produces .next/standalone, .next/static
#   2. fly deploy --app alphalog-pwa  # this Dockerfile copies + runs
#
# If you forget step 1, the COPY at the bottom fails fast with "no such file".

FROM node:24-slim AS runner
WORKDIR /app

ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1 \
    PORT=3000 \
    HOSTNAME=::

# Non-root user matching Next.js standalone conventions.
RUN groupadd --system --gid 1001 nodejs \
    && useradd  --system --uid 1001 --gid nodejs nextjs

# public/ holds PWA assets (sw.js, workbox-*.js, manifest, icons).
COPY --chown=nextjs:nodejs public ./public

# .next/standalone is a self-contained Node app: server.js + minimal
# node_modules + .next/ runtime metadata. Generated by Next.js when
# `output: 'standalone'` is set in next.config.ts.
COPY --chown=nextjs:nodejs .next/standalone ./

# Static chunks live separately and must be placed at .next/static so the
# runtime serves them at /_next/static/*.
COPY --chown=nextjs:nodejs .next/static ./.next/static

USER nextjs
EXPOSE 3000

# Health probe used by Fly's [http_service.checks].
HEALTHCHECK --interval=30s --timeout=5s --start-period=15s --retries=3 \
    CMD node -e "fetch('http://127.0.0.1:3000/api/health').then(r=>{if(r.status>=500)process.exit(1)}).catch(()=>process.exit(1))"

CMD ["node", "server.js"]
