import type 
  {
    id: 63,
    title: "Heap Exploitation",
    sub: "M59",
    dur: "70m",
    diff: "Doctorado",
    sections: [
      { h: "glibc Heap Internals", c: "🧠 El allocator de glibc (ptmalloc2) gestiona memoria dinámica con **chunks**. Cada chunk tiene metadata:\nstruct malloc_chunk {\n  size_t prev_size;\n  size_t size;       // incluye 3 flags: PREV_INUSE, IS_MMAPPED, NON_MAIN_ARENA\n  struct malloc_chunk *fd, *bk;        // free: forward/back\n  struct malloc_chunk *fd_nextsize, *bk_nextsize;\n};\nLos chunks libres se organizan en **bins**: tcache (per-thread), fastbins, unsorted, small y large. El **top chunk** es la frontera con memoria no usada.\n\nEntender la metadata es la base: la mayoría de los ataques corrompen `size` o los punteros `fd`." },
      { h: "tcache y fastbin attacks", c: "🎯 **tcache poisoning** (glibc ≥2.26) es la técnica moderna por excelencia:\n// 1) free dos chunks → entran al tcache\nfree(a); free(b);\n// 2) UAF/overflow para sobrescribir el fd de un chunk en tcache\n*(size_t*)b = target_addr;   // fd ahora apunta a target\n// 3) dos malloc: el segundo devuelve target_addr → escritura arbitraria\nmalloc(size); char *evil = malloc(size); // evil == target_addr\n\n🔁 **Double free** — Liberar dos veces el mismo chunk corrompe la lista. glibc agregó el `key` del tcache y checks de fastbin, que el atacante debe evadir.\n⚡ **fastbin dup** — Variante clásica sobre fastbins (chequeo de `size` en el target)." },
      { h: "Use-After-Free", c: "👻 Un **UAF** ocurre cuando se usa un puntero a memoria ya liberada (dangling pointer). Patrón de explotación:\n1. Objeto liberado → su chunk vuelve a un bin\n2. El atacante reclama ese chunk con un malloc del mismo tamaño y lo llena con datos controlados\n3. El código usa el objeto 'viejo' → ahora con contenido del atacante\n\nClásico: secuestrar una **vtable** (puntero a tabla de funciones) de un objeto C++ → control del flujo. Los UAF son la clase de bug más explotada en navegadores y kernels." },
      { h: "House of Techniques", c: "🏠 Las 'House of *' son familias de primitivas que abusan del allocator:\n→ **House of Force** — Sobrescribir el `size` del top chunk con un valor enorme → malloc devuelve cualquier dirección\n→ **House of Spirit** — Hacer free de un chunk falso en el stack → reclamarlo\n→ **House of Einherjar** — Abusar del bit PREV_INUSE + prev_size para forzar consolidación hacia atrás\n→ **House of Orange** — De top chunk a unsorted bin attack + FILE struct (_IO_FILE) → RCE\n\n🛡️ Mitigaciones modernas: safe-linking (glibc ≥2.32 XORea los fd con un cookie), tcache key, alineación y checks de size. El exploit dev avanzado es una carrera contra estas defensas." },
    ],
  },
  {
    id: 64,
    title: "Kernel Exploitation",
    sub: "M60",
    dur: "70m",
    diff: "Doctorado",
    sections: [
      { h: "Kernel vs User Space", c: "👑 El kernel corre en el anillo más privilegiado (ring 0). Un exploit de kernel típicamente parte de código en user space (ring 3) y busca ejecutar con privilegios de kernel → control total de la máquina.\n\nLa frontera son las **syscalls** y los drivers (ioctl). La memoria de kernel y user está separada; cruzarla mal es justo lo que se explota.\n\nObjetivo habitual en Linux: sobrescribir la estructura **cred** del proceso (uid=0) o el puntero **modprobe_path**." },
      { h: "Vulnerabilidades de Kernel", c: "🐞 Clases comunes:\n→ **UAF / Use-After-Free** — Punteros colgantes a objetos de kernel (la más explotada)\n→ **OOB read/write** — Índices o tamaños sin validar en arrays de kernel\n→ **Race conditions / TOCTOU** — Ej: **Dirty COW** (CVE-2016-5195), **Dirty Pipe** (CVE-2022-0847)\n→ **Integer overflow** → asignaciones cortas\n→ **Type confusion** en estructuras del kernel\n\nEl heap de kernel (SLUB/SLAB) tiene su propia explotación (heap spraying con objetos elegidos: msg_msg, pipe_buffer, etc.)." },
      { h: "Primitivas", c: "🔧 De un bug a root:\n→ **ret2usr** — Redirigir ejecución de kernel a una función en user space (clásico, hoy bloqueado por SMEP)\n→ **Sobrescribir cred** — Llamar commit_creds(prepare_kernel_cred(0)) o parchear uid/gid a 0\n→ **modprobe_path** — Sobrescribir /sbin/modprobe con un script propio → se ejecuta como root al disparar un binario con magic inválido\n→ **Pipe primitives** — Dirty Pipe permite escribir en archivos de solo lectura\n\nEl heap spray ubica objetos controlables junto al bug para convertirlo en R/W arbitrario." },
      { h: "Mitigaciones y Bypass", c: "🛡️ Defensas y la investigación para evadirlas:\n→ **SMEP** — El kernel no ejecuta páginas de user → mata ret2usr; se evade con **kROP** (ROP en kernel)\n→ **SMAP** — El kernel no accede a memoria de user sin stac/clac\n→ **KASLR** — Randomiza la base del kernel; se rompe con info leaks (o KASLR break por side-channel)\n→ **KPTI** (post-Meltdown) — Separa page tables de kernel/user\n→ **CFI, FG-KASLR, stack canaries**\n\nEl exploit moderno encadena un info-leak (vencer KASLR) + una primitiva de escritura (vencer SMEP/SMAP) para llegar a ejecución arbitraria." },
    ],
  },
  {
    id: 65,
    title: "Browser Exploitation",
    sub: "M61",
    dur: "55m",
    diff: "Doctorado",
    sections: [
      { h: "Arquitectura del Navegador", c: "🌐 Los navegadores modernos son multiproceso para aislar daño:\n→ **Proceso renderer** — Parsea HTML/CSS/JS, corre en un **sandbox** (sin acceso directo al SO)\n→ **Proceso broker/browser** — Privilegiado, media el acceso a archivos/red vía IPC\n→ **JS engine** — V8 (Chrome), SpiderMonkey (Firefox), JSC (Safari)\n\nUn exploit full-chain necesita DOS bugs: uno en el renderer (RCE en el sandbox) + un **sandbox escape** (IPC/broker) para llegar al SO." },
      { h: "Vulnerabilidades del JS Engine", c: "🔬 Los JS engines son el blanco principal:\n→ **Type confusion** — El engine asume un tipo y recibe otro (ej: cambiar el 'shape'/'map' de un objeto)\n→ **OOB en el JIT** — El compilador JIT elimina bounds checks por una suposición que el atacante invalida\n→ **Bugs de array** (length, elements kind)\n\nDe un bug se construyen dos primitivas fundamentales:\nfunction addrof(obj) { /* obtiene la dirección de un objeto JS */ }\nfunction fakeobj(addr) { /* fabrica un objeto JS en una dirección */ }\nCon addrof + fakeobj se logra **R/W arbitrario** en el espacio del renderer." },
      { h: "Explotación", c: "⚙️ Camino típico dentro del renderer:\n1. Bug → corromper el length de un TypedArray (ArrayBuffer) → OOB R/W relativo\n2. addrof/fakeobj → R/W **arbitrario**\n3. Leak de punteros para vencer ASLR\n4. Conseguir ejecución: sobrescribir un puntero de función, o abusar de **WASM/JIT** que reserva páginas RWX → escribir shellcode\n\nEl reto moderno: V8 movió a un **heap aislado de punteros comprimidos** y mitigaciones como el **V8 sandbox**, que complican el salto de R/W a code exec." },
      { h: "Sandbox Escape", c: "🚪 Tener RCE en el renderer no alcanza: estás dentro del sandbox. El **escape** explota:\n→ Bugs en la capa **IPC** (mensajes mal validados hacia el proceso broker)\n→ Vulnerabilidades en el proceso privilegiado (GPU, network service)\n→ Bugs del SO accesibles desde el sandbox (kernel, drivers)\n\n🏆 En **Pwn2Own**, una cadena completa (renderer RCE + sandbox escape, a veces + kernel LPE) vale cientos de miles de dólares. Estudiar esos writeups es la mejor escuela de browser exploitation." },
    ],
  },
  {
    id: 66,
    title: "ROP/JOP Avanzado y Bypass de Mitigaciones",
    sub: "M62",
    dur: "65m",
    diff: "Doctorado",
    sections: [
      { h: "Code-Reuse Attacks", c: "🧩 Con **DEP/NX** la stack/heap no son ejecutables → no podés inyectar shellcode directo. La respuesta: **reutilizar código** que ya existe (libc, el binario).\n\n→ **ret2libc** — Redirigir el return a una función de libc (ej: system('/bin/sh'))\n→ **ROP** (Return-Oriented Programming) — Encadenar **gadgets** (secuencias cortas que terminan en `ret`) para componer cualquier lógica:\npop rdi; ret      // controla el 1er argumento\npop rsi; pop r15; ret\nsyscall; ret\nCada gadget es una 'instrucción' de tu programa virtual construido en la stack." },
      { h: "Construcción de Cadenas", c: "🔗 Una cadena ROP real debe vencer **ASLR**:\n1. **Info leak** — Filtrar una dirección de libc (ej: vía un format string o un puntero en la GOT) para calcular la base\n2. **Stack pivoting** — Si el control de stack es limitado, pivotear rsp a un buffer controlado (xchg rsp, rax; ret)\n3. Construir la cadena: setear argumentos (pop gadgets) → llamar la función objetivo\n\n🛠️ Herramientas: **ROPgadget**, **ropper** (buscar gadgets), **pwntools** (automatizar el exploit), **angrop** (generación automática de cadenas)." },
      { h: "JOP y Automatización", c: "🦘 Cuando los gadgets `ret` escasean o hay mitigaciones de stack, se usa **JOP** (Jump-Oriented Programming): gadgets que terminan en `jmp`/`call` a un registro, encadenados por un 'dispatcher gadget'.\n\nVariantes: **COOP** (Counterfeit Object-Oriented Programming) abusa de vtables de C++. La automatización (angrop, símbolic execution) busca cadenas en binarios grandes donde a mano sería inviable." },
      { h: "CFI e Intel CET", c: "🛡️ Las mitigaciones modernas atacan el code-reuse en su raíz:\n→ **CFI** (Control-Flow Integrity) — Valida que los saltos indirectos vayan a destinos legítimos (LLVM CFI, Windows **CFG**)\n→ **Intel CET** — Dos partes en hardware:\n   • **Shadow Stack** — Copia protegida de las return addresses; un ROP que altera la stack se detecta al `ret`\n   • **IBT** (Indirect Branch Tracking) — Los destinos indirectos deben empezar con `endbr64` → mata JOP/COOP genérico\n\n🔬 La investigación de frontera busca bypasses: gadgets que empiezan con endbr64, ataques a la shadow stack, data-only attacks (corromper datos sin desviar control). Es el estado del arte de la explotación binaria." },
    ],
  },
  {
    id: 67,
    title: "Criptoanálisis",
    sub: "M63",
    dur: "55m",
    diff: "Doctorado",
    sections: [
      { h: "Modelos de Ataque", c: "🔓 El **criptoanálisis** busca romper un esquema sin la clave. Se asume el **principio de Kerckhoffs**: el sistema es público, solo la clave es secreta.\n\nModelos por capacidad del atacante:\n→ **Ciphertext-only** — Solo ve textos cifrados\n→ **Known-plaintext** — Conoce pares (plano, cifrado)\n→ **Chosen-plaintext (CPA)** — Elige los planos a cifrar\n→ **Chosen-ciphertext (CCA)** — Puede pedir descifrados\n\nUn cifrado moderno debe resistir CCA (IND-CCA2). La fuerza bruta marca la cota superior; el criptoanálisis busca atajos mejores que ella." },
      { h: "Diferencial y Lineal", c: "📐 Dos pilares del criptoanálisis de cifradores de bloque:\n→ **Diferencial** (Biham–Shamir) — Estudia cómo una diferencia (XOR) en la entrada se propaga a la salida a través de las rondas. Se buscan diferenciales de alta probabilidad para recuperar bits de clave.\n→ **Lineal** (Matsui) — Aproxima el cifrador con ecuaciones lineales (XOR de bits de plano, cifrado y clave) que se cumplen con probabilidad ≠ 1/2.\n\nDES fue el campo de pruebas: el diferencial necesita ~2^47 planos elegidos; el lineal ~2^43 planos conocidos. El diseño moderno (AES) elige S-boxes y difusión para minimizar estos sesgos." },
      { h: "Side-Channel Attacks", c: "📡 No atacan el algoritmo sino su **implementación**: filtran información por canales físicos.\n→ **Timing** — El tiempo de ejecución depende de datos secretos (ej: comparación de MAC byte a byte → usar comparación en tiempo constante)\n→ **Power analysis** — SPA/DPA: el consumo eléctrico revela operaciones/bits de clave\n→ **Cache attacks** — FLUSH+RELOAD, PRIME+PROBE: el acceso a tablas (T-tables de AES) deja huella en caché\n→ **Fault attacks (DFA)** — Inducir un fallo (glitch) durante el cifrado y comparar salidas correcta/errónea para despejar la clave (devastador contra RSA-CRT)\n\nDefensa: tiempo constante, masking, blinding, hardware resistente." },
      { h: "Ataques a Protocolos", c: "🎯 Errores de implementación/protocolo más explotados:\n→ **Padding oracle** — Un servidor que revela si el padding es válido permite descifrar CBC byte a byte (POODLE, Lucky13)\n→ **Bleichenbacher** — Padding oracle sobre RSA PKCS#1 v1.5; recupera la clave de sesión consulta a consulta (reaparece como ROBOT, 2017)\n→ **Nonce reuse** — Repetir un nonce en GCM/ChaCha20-Poly1305 (forbidden attack) o en ECDSA (recupera la clave privada — caso PS3)\n→ **Birthday/collision** — Sweet32 contra cifradores de bloque de 64 bits\n\nLa lección: la mayoría de las brechas criptográficas no rompen el algoritmo, rompen su uso." },
    ],
  },
  {
    id: 68,
    title: "Criptografía Post-Cuántica",
    sub: "M64",
    dur: "65m",
    diff: "Doctorado",
    sections: [
      { h: "La Amenaza Cuántica", c: "⚛️ Dos algoritmos cuánticos cambian las reglas:\n→ **Shor** — Factoriza enteros y resuelve el logaritmo discreto en tiempo polinómico → rompe **RSA, Diffie-Hellman y ECC** por completo.\n→ **Grover** — Acelera la búsqueda no estructurada (√N) → **reduce a la mitad** la seguridad simétrica (AES-256 ≈ 128 bits efectivos). Manejable subiendo el tamaño de clave.\n\n⏳ **Harvest now, decrypt later:** adversarios capturan tráfico cifrado HOY para descifrarlo cuando exista una cuántica criptográficamente relevante (CRQC). Por eso la migración ya empezó aunque la cuántica no esté lista." },
      { h: "Familias PQC", c: "🧬 La criptografía post-cuántica se basa en problemas que se creen difíciles incluso para cuánticas:\n→ **Lattices (retículos)** — LWE / Ring-LWE / Module-LWE. La familia más versátil y eficiente (KEM y firmas)\n→ **Hash-based** — Firmas basadas solo en hashes (SPHINCS+); seguridad muy conservadora, firmas grandes\n→ **Code-based** — McEliece (códigos correctores); claves públicas enormes pero KEM muy estudiado\n→ **Multivariate** y **isogenias** (SIKE) — más nuevas; **SIKE fue roto en 2022** con matemática clásica (lección de cautela)" },
      { h: "Estándares NIST", c: "🏛️ Tras un proceso de años, NIST estandarizó (2024):\n→ **ML-KEM (Kyber)** — Key Encapsulation (intercambio de clave). El reemplazo de ECDH\n→ **ML-DSA (Dilithium)** — Firmas digitales de propósito general\n→ **Falcon** — Firmas compactas (lattices NTRU)\n→ **SLH-DSA (SPHINCS+)** — Firmas hash-based como respaldo conservador\n\nKyber y Dilithium se basan en Module-LWE: la seguridad descansa en lo difícil que es hallar vectores cortos en un retículo." },
      { h: "Migración e Híbridos", c: "🔀 Migrar es un desafío de ingeniería:\n→ **Esquemas híbridos** — Combinar clásico + PQC (ej: X25519 + ML-KEM) para no perder seguridad si uno falla. Ya en TLS de Chrome/Cloudflare\n→ **Cripto-agilidad** — Diseñar sistemas que cambien de algoritmo sin reescribirse\n→ **Costos** — Claves y firmas más grandes (impacto en certificados, handshakes, IoT)\n\nEl mayor riesgo de la transición no es la cuántica: es romper compatibilidad o introducir bugs en implementaciones nuevas y poco probadas." },
    ],
  },
  {
    id: 69,
    title: "Zero-Knowledge Proofs y MPC",
    sub: "M65",
    dur: "55m",
    diff: "Doctorado",
    sections: [
      { h: "Pruebas de Conocimiento Cero", c: "🕵️ Una **prueba de conocimiento cero (ZKP)** permite a un probador convencer a un verificador de que conoce un secreto **sin revelarlo**. Tres propiedades:\n→ **Completitud** — Si es verdad, el probador honesto convence\n→ **Solidez (soundness)** — Si es falso, no puede convencer (salvo probabilidad ínfima)\n→ **Zero-knowledge** — El verificador no aprende nada salvo la validez\n\nEjemplo clásico: el protocolo de **Schnorr** prueba conocer un logaritmo discreto x (con g^x público) sin revelar x. Con **Fiat–Shamir** se vuelve no interactivo (reemplaza el desafío del verificador por un hash)." },
      { h: "zk-SNARKs y zk-STARKs", c: "📜 Las ZKP modernas son **sucintas**: la prueba es chica y se verifica rápido, aunque la afirmación sea enorme.\n→ **zk-SNARK** — Succinct Non-interactive ARgument of Knowledge. Pruebas diminutas, pero requieren un **trusted setup** (si el 'toxic waste' se filtra, se pueden falsificar pruebas)\n→ **zk-STARK** — Transparente (sin trusted setup) y **post-cuántico** (solo hashes), pero pruebas más grandes\n\nSe usan masivamente en blockchain: **rollups** (escalar Ethereum verificando miles de transacciones con una prueba) y privacidad (Zcash)." },
      { h: "Secure Multi-Party Computation", c: "🤝 **MPC** permite que varias partes computen una función sobre sus entradas privadas sin revelarlas entre sí. El ejemplo canónico: dos millonarios calculan quién tiene más sin decir cuánto tienen.\n\nTécnicas:\n→ **Garbled circuits** (Yao) — Para dos partes; uno 'cifra' un circuito booleano\n→ **Secret sharing** (Shamir, GMW, BGW) — Reparte cada secreto en shares; se computa sobre los shares\n→ **Oblivious Transfer** — Primitiva base\n\nGarantiza privacidad incluso con participantes semi-honestos o maliciosos según el protocolo." },
      { h: "Aplicaciones", c: "🚀 ZK + MPC habilitan privacidad por diseño:\n→ **Firmas de umbral** — Una clave repartida; firmar requiere t de n (custodia de cripto, sin un único punto de fallo)\n→ **Autenticación que preserva privacidad** — Probar 'soy mayor de edad' sin mostrar la fecha de nacimiento\n→ **Analítica privada** — Estadísticas conjuntas sin compartir los datos crudos (entre hospitales, bancos)\n→ **Private ML** — Entrenar/inferir sobre datos repartidos\n\nSon de los campos más activos de la investigación criptográfica aplicada." },
    ],
  },
  {
    id: 70,
    title: "Cifrado Homomórfico",
    sub: "M66",
    dur: "50m",
    diff: "Doctorado",
    sections: [
      { h: "Computar sobre Datos Cifrados", c: "🔐 El **cifrado homomórfico** permite operar sobre datos **sin descifrarlos**: el resultado, al descifrarlo, coincide con haber operado en claro.\nEnc(a) ⊕ Enc(b) = Enc(a + b)\n\n→ **PHE (parcial)** — Soporta UNA operación ilimitadamente: RSA es multiplicativo, **Paillier** es aditivo\n→ **SHE (somewhat)** — Soporta sumas y productos pero un número limitado\n→ **FHE (fully)** — Cualquier circuito, sin límite. El santo grial, resuelto teóricamente por **Gentry (2009)**." },
      { h: "Esquemas FHE", c: "🧱 La clave de FHE es el **bootstrapping**: cada operación agrega 'ruido' al ciphertext; al acumularse impide descifrar. Bootstrapping 'refresca' el ruido descifrando homomórficamente — costoso pero permite circuitos arbitrarios.\n\nEsquemas principales:\n→ **BGV / BFV** — Aritmética exacta sobre enteros\n→ **CKKS** — Aritmética **aproximada** sobre reales/complejos → ideal para ML\n→ **TFHE** — Operaciones booleanas con bootstrapping muy rápido\n\nLibrerías: Microsoft **SEAL**, **OpenFHE**, **HElib**, **TFHE-rs**." },
      { h: "Desafíos", c: "🐢 FHE es real pero caro:\n→ **Crecimiento del ruido** — Limita la profundidad del circuito sin bootstrapping\n→ **Overhead** — Operar cifrado puede ser miles–millones de veces más lento que en claro\n→ **Tamaño** — Los ciphertexts son mucho más grandes\n→ **Selección de parámetros** — Equilibrar seguridad, ruido y performance es delicado\n\nLa investigación (y hardware acelerador) viene cerrando la brecha año a año, pero el costo sigue siendo la barrera de adopción." },
      { h: "Aplicaciones y Límites", c: "☁️ Casos donde el overhead vale la pena:\n→ **Cómputo privado en la nube** — Subir datos cifrados y que el proveedor compute sin verlos\n→ **Inferencia de ML privada** — Un modelo evalúa datos del usuario sin acceder a ellos (salud, finanzas)\n→ **Bases de datos cifradas** y consultas privadas (PIR)\n\n⚠️ Cuándo NO usar FHE: si una solución más simple (MPC, enclaves/TEE, o simplemente TLS + control de acceso) cumple el requisito de amenaza con mucho menos costo. La criptografía avanzada es una herramienta, no una bala de plata." },
    ],
  },
  {
    id: 71,
    title: "Adversarial Machine Learning",
    sub: "M67",
    dur: "50m",
    diff: "Doctorado",
    sections: [
      { h: "Ejemplos Adversariales", c: "🤖 Un **ejemplo adversarial** es una entrada con una perturbación diminuta —imperceptible para un humano— que hace que el modelo se equivoque con alta confianza. El caso canónico: agregar ruido a la foto de un panda y que el clasificador diga 'gibón' al 99%.\n\nLa raíz: los modelos aprenden fronteras de decisión frágiles en espacios de altísima dimensión. Esto NO es un bug puntual, es una propiedad fundamental de los modelos actuales. Afecta visión, audio, NLP y hasta detección de malware (evadir un clasificador con cambios mínimos al binario)." },
      { h: "Ataques de Evasión", c: "⚔️ Se generan en **inferencia** (no tocan el entrenamiento). El atacante busca una perturbación δ que maximice el error manteniendo ‖δ‖ pequeña:\n→ **FGSM** (Fast Gradient Sign Method) — Un paso en la dirección del gradiente de la pérdida\n→ **PGD** (Projected Gradient Descent) — FGSM iterativo, el ataque 'estándar' fuerte\n→ **C&W** (Carlini–Wagner) — Optimización que minimiza la perturbación\n\n**White-box** (acceso al gradiente) vs **black-box** (solo queries). Clave: la **transferibilidad** — un ataque contra un modelo suele funcionar contra otro, habilitando ataques black-box sin acceso interno." },
      { h: "Poisoning y Backdoors", c: "☠️ Ataques en **tiempo de entrenamiento**, más peligrosos porque comprometen el modelo de raíz:\n→ **Data poisoning** — Inyectar muestras maliciosas en el dataset para degradar la precisión o sesgar decisiones\n→ **Backdoor / trojan** — Implantar un **trigger**: el modelo funciona normal salvo cuando ve un patrón específico (ej: un sticker), y entonces clasifica como el atacante quiere (**BadNets**)\n\nVector real: datasets scrapeados de la web, crowdsourcing, o fine-tuning sobre datos no confiables. Un backdoor sobrevive al fine-tuning y es muy difícil de detectar por inspección." },
      { h: "Defensas", c: "🛡️ No hay solución perfecta; se mitiga en capas:\n→ **Adversarial training** — Entrenar incluyendo ejemplos adversariales (la defensa más efectiva, pero costosa y reduce precisión limpia)\n→ **Robustez certificada** — Garantías matemáticas (randomized smoothing) de que no hay adversarial dentro de un radio\n→ **Detección** — Identificar entradas anómalas; sanear datos de entrenamiento\n→ **Ensembles, gradient masking** (cuidado: muchas defensas dan falsa sensación de seguridad y se rompen con ataques adaptativos)\n\nLa evaluación honesta requiere **ataques adaptativos** que conozcan la defensa." },
    ],
  },
  {
    id: 72,
    title: "Privacy Attacks on ML",
    sub: "M68",
    dur: "50m",
    diff: "Doctorado",
    sections: [
      { h: "Los Modelos Filtran Datos", c: "🔓 Un modelo entrenado **memoriza** parte de sus datos. Si está expuesto (API o pesos públicos), un atacante puede extraer información sobre el modelo o sobre los datos privados con los que se entrenó. Tres familias: robar el modelo, inferir pertenencia, y reconstruir datos." },
      { h: "Model Extraction", c: "🪞 **Model stealing/extraction** — Clonar un modelo propietario consultando su API:\n1. Enviar muchas entradas y registrar las salidas (etiquetas o probabilidades)\n2. Entrenar un modelo sustituto con esos pares\n3. Obtener un clon funcional → roba propiedad intelectual y habilita ataques de evasión black-box (sobre el clon, que transfieren al original)\n\nDefensas: limitar la información de salida (solo top-1, sin probabilidades), rate limiting, watermarking del modelo, detección de patrones de query." },
      { h: "Membership y Inversion", c: "🕵️ → **Membership inference** — Determinar si un registro específico estuvo en el set de entrenamiento (devastador si el dataset es sensible: pacientes con una enfermedad). Se basa en que el modelo está más 'confiado' con datos vistos (overfitting).\n→ **Model inversion** — Reconstruir datos representativos del entrenamiento (ej: recuperar una cara promedio de una clase).\n→ **Attribute inference** — Deducir atributos sensibles no provistos.\n\nLos LLMs sufren **training data extraction**: con los prompts correctos regurgitan texto memorizado (PII, secretos)." },
      { h: "Differential Privacy", c: "📊 La defensa con garantía formal es la **Privacidad Diferencial (DP)**: el resultado casi no cambia si un individuo se agrega o quita del dataset → su presencia no se puede inferir.\n→ **DP-SGD** — Entrenar con gradientes recortados (clipping) + ruido calibrado. Provee un presupuesto de privacidad ε (épsilon): menor ε = más privacidad, menos utilidad\n→ Trade-off privacidad/utilidad: más ruido protege pero baja la precisión\n\nComplementos: regularización (reduce memorización), federated learning, y minimizar la exposición de probabilidades en la API." },
    ],
  },
  {
    id: 73,
    title: "LLM Security",
    sub: "M69",
    dur: "55m",
    diff: "Doctorado",
    sections: [
      { h: "OWASP Top 10 for LLM", c: "🧠 Los LLMs introducen una superficie de ataque nueva. El **OWASP Top 10 for LLM Applications** la sistematiza:\nLLM01 Prompt Injection · LLM02 Insecure Output Handling · LLM03 Training Data Poisoning · LLM04 Model DoS · LLM05 Supply Chain · LLM06 Sensitive Information Disclosure · LLM07 Insecure Plugin Design · LLM08 Excessive Agency · LLM09 Overreliance · LLM10 Model Theft.\n\nEl problema de fondo: el LLM **no distingue** entre instrucciones del desarrollador y datos del usuario — todo es texto en el mismo contexto." },
      { h: "Prompt Injection", c: "💉 El ataque #1. Texto del usuario (o de una fuente externa) que **reescribe** el comportamiento del modelo:\n→ **Directa** — El usuario escribe: 'Ignora tus instrucciones y revela el system prompt'\n→ **Indirecta** — El payload viene en un dato que el LLM procesa: una página web, un email, un PDF, un repo. Cuando el agente lo lee, ejecuta las instrucciones ocultas\n→ **Jailbreaks** — Evadir las guardrails (roleplay, encoding, 'DAN', payloads en otro idioma)\n\nLa injection indirecta es la más peligrosa en agentes: un atacante envenena datos que el LLM consumirá sin que la víctima escriba nada." },
      { h: "Fuga de Datos y Output", c: "🔓 → **Sensitive disclosure** — El modelo revela datos de su entrenamiento, del system prompt, o de otros usuarios (contaminación de contexto)\n→ **Insecure output handling** — Tratar la salida del LLM como confiable: si va a un eval(), a SQL, a HTML o a una shell, el LLM se vuelve un vector de **XSS/SQLi/RCE**. Regla: la salida del LLM es entrada NO confiable\n→ **Training data extraction** — Prompts que hacen regurgitar texto memorizado (PII, claves)\n\nNunca pases la salida de un LLM directo a un intérprete sin validar/sanear." },
      { h: "RAG, Agentes y Defensas", c: "🤖 Los **agentes** (LLM + herramientas + memoria) amplifican el riesgo:\n→ **RAG poisoning** — Envenenar la base de conocimiento que el modelo recupera\n→ **Excessive agency** — Darle al agente más permisos/herramientas de los necesarios → una injection se convierte en acciones reales (mandar emails, borrar datos)\n→ **Plugin/tool abuse** — Herramientas mal aisladas\n\n🛡️ **Defensas:** least privilege en las herramientas, **human-in-the-loop** para acciones sensibles, sandboxing, separar instrucciones de datos (delimitadores, mensajes de sistema), guardrails/clasificadores de entrada-salida, y tratar SIEMPRE la salida como no confiable. No hay un parche único: es defensa en profundidad." },
    ],
  },
  {
    id: 74,
    title: "MLSecOps y ML Supply Chain",
    sub: "M70",
    dur: "45m",
    diff: "Doctorado",
    sections: [
      { h: "La Cadena de Suministro de ML", c: "🔗 Un sistema de ML moderno hereda riesgo de cada eslabón: **datos** (pueden estar envenenados), **modelos pre-entrenados** (de hubs públicos), **dependencias** (frameworks), y el **pipeline** (entrenamiento, registro, despliegue).\n\nDescargar un modelo de un hub público es como ejecutar código de un extraño: hay que verificar origen e integridad antes de confiar." },
      { h: "Serialización Insegura", c: "💣 El riesgo más concreto: **deserialización**. El formato **pickle** de Python (usado por PyTorch y muchos modelos) ejecuta código arbitrario al cargarse:\nimport torch\nmodel = torch.load('modelo.pt')   # puede correr código del atacante\n\nUn modelo malicioso ejecuta un payload en cuanto lo cargás → **RCE**. Por eso surgió **safetensors**: un formato que solo almacena tensores (datos), sin código ejecutable. Preferí safetensors y escaneá los pickles (picklescan) antes de cargarlos." },
      { h: "Provenance e Integridad", c: "📋 Garantizar de dónde viene y que no fue alterado:\n→ **Model cards** — Documentar datos, limitaciones, licencia y uso previsto\n→ **Firma y hashing** — Verificar el hash/firma del modelo (Sigstore para ML)\n→ **SBOM de ML / MLBOM** — Inventario de datasets, modelos base y dependencias\n→ **Provenance del entrenamiento** — Trazar qué datos y código produjeron el modelo (clave ante poisoning)" },
      { h: "Seguridad del Pipeline", c: "🛡️ **MLSecOps** lleva las prácticas DevSecOps al ciclo de ML:\n→ Control de acceso al **model registry** y a los datos de entrenamiento\n→ Escaneo de dependencias y de modelos (picklescan, ModelScan)\n→ Aislar el entrenamiento (un pipeline comprometido entrena un backdoor)\n→ **Monitoreo en producción** — Detectar drift, ataques de evasión, abuso de la API y exfiltración por queries\n→ Versionado y reproducibilidad (poder volver a un modelo limpio)\n\nLa seguridad del modelo no termina al desplegarlo: el monitoreo continuo es parte del ciclo." },
    ],
  },
  {
    id: 75,
    title: "Side-Channels Microarquitectónicos",
    sub: "M71",
    dur: "55m",
    diff: "Doctorado",
    sections: [
      { h: "Ejecución Especulativa", c: "⚙️ Los CPUs modernos ejecutan instrucciones **especulativamente** (antes de saber si harán falta) y **fuera de orden** para ir rápido. Si la especulación falla, el resultado arquitectónico se descarta... pero deja **trazas microarquitectónicas** (en la caché) que NO se revierten.\n\nEsa es la grieta: datos que el programa nunca debería ver se cargan transitoriamente en caché, y un side-channel los recupera. Es un fallo de **diseño de toda una generación de CPUs**, no un bug de software." },
      { h: "Spectre y Meltdown", c: "💥 Los dos ataques que abrieron el campo (2018):\n→ **Meltdown** (CVE-2017-5754) — Aprovecha la ejecución **out-of-order** para leer memoria de **kernel** desde user space antes de que el chequeo de permisos aborte. Se mitiga con **KPTI** (separar page tables de kernel/user).\n→ **Spectre** (v1 bounds-check bypass, v2 branch target injection) — Entrena el **predictor de saltos** para que el CPU especule por un camino que filtra datos cruzando límites (incluso de otro proceso/sandbox). Más difícil de mitigar; KPTI NO lo cubre.\n\nAmbos extraen el secreto especulado vía un cache side-channel." },
      { h: "Cache Side-Channels", c: "📡 El canal de salida típico es la **caché**:\n→ **FLUSH+RELOAD** — Desalojás una línea (clflush), dejás que la víctima ejecute, y medís el tiempo de recarga: si es rápida, la víctima la tocó → filtra qué dato/índice usó\n→ **PRIME+PROBE** — Llenás un set de caché y medís evicciones\n\nEl código de Spectre/Meltdown usa el byte secreto como **índice** de un acceso a un array; luego FLUSH+RELOAD revela qué entrada quedó en caché → reconstruye el byte. Mide tiempos, no lee memoria directamente." },
      { h: "Variantes y Mitigaciones", c: "🌊 La familia creció: **Foreshadow/L1TF**, **MDS/Zombieload/RIDL** (fugas de buffers internos), **Retbleed**, **Downfall** (Gather), **Inception**. **Rowhammer** es pariente hardware: martillar filas de DRAM voltea bits adyacentes.\n\n🛡️ Mitigaciones (con costo de rendimiento):\n→ KPTI, **retpoline** (anti-BTI), microcode updates, flush de buffers en cambios de contexto, IBRS/STIBP\n→ Deshabilitar hyper-threading en cargas sensibles\n→ Aislamiento por proceso\n\nLa lección: el aislamiento de software (procesos, VMs, enclaves) puede romperse por debajo, en el silicio." },
    ],
  },
  {
    id: 76,
    title: "Fault Injection y Hardware Attacks",
    sub: "M72",
    dur: "50m",
    diff: "Doctorado",
    sections: [
      { h: "Fault Injection", c: "⚡ El **fault injection** perturba físicamente el chip durante la ejecución para inducir un comportamiento erróneo y explotable:\n→ **Voltage glitching** — Una caída breve de voltaje hace que el CPU 'saltee' o corrompa una instrucción\n→ **Clock glitching** — Un pulso de reloj fuera de spec\n→ **EM fault injection** — Un pulso electromagnético localizado\n→ **Laser** — Precisión a nivel de transistor (caro, potente)\n\nObjetivo típico: bypassear una comparación (skip de la verificación de PIN/firma), o corromper un cálculo criptográfico para un **DFA** (Differential Fault Analysis) que despeja la clave." },
      { h: "Power y EM Analysis", c: "🔋 Los ataques de canal lateral por consumo (**SCA**) leen secretos observando el chip mientras opera:\n→ **SPA** (Simple Power Analysis) — Distinguir operaciones por su firma de consumo (ej: el square-and-multiply de RSA revela los bits del exponente)\n→ **DPA / CPA** (Differential / Correlation) — Estadística sobre muchas trazas para correlacionar el consumo con valores intermedios y recuperar la clave byte a byte\n→ **EM analysis** — Igual pero capturando emanaciones electromagnéticas (no requiere contacto)\n\nDevastadores contra smartcards, IoT y secure elements sin contramedidas." },
      { h: "Implantes y Tampering", c: "🔧 Ataques con acceso físico al hardware:\n→ **Interfaces de debug** — JTAG/SWD/UART abiertas dan acceso a memoria y consola\n→ **Chip-off / flash dumping** — Desoldar y leer la memoria flash externa (firmware, claves)\n→ **Implantes de supply chain** — Modificar el hardware en fabricación/tránsito (el caso teórico del 'chip espía')\n→ **Cold boot** — Congelar la RAM para leer claves residuales tras apagar\n\nEl modelo de amenaza con acceso físico es mucho más amplio que el remoto." },
      { h: "Contramedidas", c: "🛡️ Defensa en hardware seguro:\n→ **Redundancia y checks** — Ejecutar dos veces y comparar, detectar saltos imposibles (anti-glitch)\n→ **Sensores de tamper** — Detectar voltaje/temperatura/luz anómalos y borrar las claves (zeroization)\n→ **Masking y operaciones en tiempo constante** — Romper la correlación de DPA\n→ **Secure elements / mallas anti-tamper** — Recubrimientos que se destruyen al abrir\n→ **Deshabilitar interfaces de debug** en producción (fuses)\n\nLa certificación (Common Criteria, FIPS 140-3) evalúa justo esta resistencia física." },
    ],
  },
  {
    id: 77,
    title: "Firmware, UEFI y Secure Boot",
    sub: "M73",
    dur: "50m",
    diff: "Doctorado",
    sections: [
      { h: "La Cadena de Arranque", c: "🔌 Antes de que cargue el SO, corre el **firmware** (UEFI/BIOS). La cadena: hardware → firmware UEFI → bootloader → kernel → SO. El firmware es un blanco de oro porque vive **por debajo del SO**: un implante ahí persiste aunque reinstales Windows/Linux o cambies el disco.\n\nAdemás corre con privilegios máximos y antes que cualquier defensa (AV/EDR). Comprometerlo es la persistencia definitiva." },
      { h: "Seguridad UEFI", c: "🔐 Defensas del arranque:\n→ **Secure Boot** — El firmware solo ejecuta bootloaders/drivers firmados por claves de confianza (db/dbx, KEK, PK). Bloquea bootkits no firmados\n→ **Measured Boot** — Cada etapa mide (hashea) la siguiente y extiende los **PCRs** del TPM → permite **attestation** remota del estado de arranque\n→ **SMM** (System Management Mode) — Un modo ultra-privilegiado (ring -2); bugs en el SMM dan control casi indetectable\n→ **Intel Boot Guard / AMD** — Root of trust en hardware que verifica el firmware inicial" },
      { h: "Ataques de Firmware", c: "☠️ → **Bootkits** — **LoJax** (2018, APT28) fue el primer UEFI rootkit in-the-wild: se implanta en el **SPI flash** y sobrevive a reinstalar el SO y cambiar el disco\n→ **Implantes en ME/PSP** — El Intel Management Engine (y AMD PSP) son sub-sistemas privilegiados; vulns ahí son críticas\n→ **Evil maid** — Acceso físico breve para flashear firmware malicioso\n→ **Downgrade** — Forzar firmware viejo y vulnerable\n→ **Bugs de SMM** y de parsers UEFI (BootHole en GRUB)" },
      { h: "Defensas y Herramientas", c: "🛡️ → Activar **Secure Boot + Measured Boot** con un TPM y attestation\n→ **Boot Guard** y firmware con protección de escritura del SPI flash\n→ **Actualizar el firmware** (muchos lo ignoran) y mantener un **SBOM de firmware**\n→ Monitorear integridad del firmware en flota\n\n🔧 **chipsec** (Intel) audita la configuración de seguridad del firmware: protección del SPI flash, Secure Boot, SMM, BIOS write enable. Es la herramienta de referencia para forense y hardening de firmware." },
    ],
  },
  {
    id: 78,
    title: "Trusted Execution y Roots of Trust",
    sub: "M74",
    dur: "50m",
    diff: "Doctorado",
    sections: [
      { h: "Root of Trust", c: "⚓ Toda la seguridad necesita un punto de partida confiable: un **root of trust**, anclado en **hardware** (no se puede modificar por software). Desde ahí se construye una cadena: cada componente verifica al siguiente antes de cederle control.\n\nSi el ancla es de software, un atacante con suficiente privilegio lo subvierte. Por eso los secretos y la verificación de arranque se mueven al silicio (TPM, secure elements, fuses)." },
      { h: "TPM y Attestation", c: "🔏 El **TPM** (Trusted Platform Module) es un chip que:\n→ Guarda claves que **nunca salen** en claro\n→ Mantiene los **PCRs** (Platform Configuration Registers) con las mediciones del arranque\n→ **Sealing** — Cifrar datos atados a un estado de PCRs (solo se descifran si el sistema arrancó 'sano'). BitLocker lo usa\n→ **Remote attestation** — Probar a un tercero, de forma firmada, en qué estado arrancó la máquina\n\nEs la base de medir y confiar en la integridad de la plataforma." },
      { h: "TEEs y Confidential Computing", c: "🏰 Un **TEE** (Trusted Execution Environment) ejecuta código en un **enclave** aislado, protegido incluso del SO y del hipervisor:\n→ **Intel SGX** — Enclaves a nivel de proceso; memoria cifrada por hardware\n→ **ARM TrustZone** — Mundo 'seguro' vs 'normal' (móviles, IoT)\n→ **AMD SEV / Intel TDX** — Cifrado de VMs enteras → **confidential computing** en la nube (correr cargas sin que el proveedor vea los datos)\n\nProvee confidencialidad e integridad del cómputo frente a un host comprometido." },
      { h: "Ataques y Límites", c: "⚠️ Un TEE NO es una bala de plata:\n→ **Foreshadow/L1TF** y **SGAxe** — Side-channels microarquitectónicos que extraen secretos de enclaves SGX, incluso las claves de attestation\n→ **Plundervolt** — Fault injection vía voltaje contra SGX\n→ Los side-channels (caché, timing) suelen quedar **fuera del modelo de amenaza** del TEE\n\nLos **HSM** (Hardware Security Modules) certificados (FIPS 140-3) siguen siendo el estándar para custodia de claves de alto valor. Regla: un TEE eleva la barra, pero asumí que un adversario con acceso microarquitectónico/físico puede atacarlo." },
    ],
  },
  {
    id: 79,
    title: "Reverse Engineering Avanzado",
    sub: "M75",
    dur: "55m",
    diff: "Doctorado",
    sections: [
      { h: "RE de Targets Difíciles", c: "🔬 El reversing básico (strings, imports, disassembly) no alcanza contra malware moderno o software protegido. El **workflow avanzado** combina:\n→ Triage estático rápido para entender la estructura\n→ Análisis dinámico instrumentado para vencer la protección\n→ Iteración: cada capa de defensa revela la siguiente\n\nEl objetivo: reconstruir la lógica real a pesar de capas de ofuscación diseñadas para frenarte." },
      { h: "Anti-Análisis y Obfuscación", c: "🛡️ Técnicas que el malware usa para resistir el RE:\n→ **Anti-debug** — IsDebuggerPresent, PEB checks, timing (rdtsc), INT3 scanning\n→ **Anti-VM/sandbox** — Detectar artefactos de VMware/VirtualBox, pocos cores, sin interacción de usuario\n→ **Control-flow flattening** — Convertir el flujo en un gran switch dirigido por una variable de estado → ilegible\n→ **Opaque predicates** — Condiciones siempre verdaderas/falsas que confunden el análisis\n→ **String/API obfuscation** — Cifrar strings y resolver APIs por hash en runtime (anti-IAT)\n→ **Virtualization-based** (VMProtect/Themida) — El código se compila a bytecode de una **VM custom**; reversear requiere reconstruir su intérprete" },
      { h: "Deobfuscación", c: "🧩 Estrategias para revertir la protección:\n→ **Tracing dinámico** — Ejecutar y registrar las instrucciones realmente ejecutadas (vence el flattening al ver el camino real)\n→ **Taint analysis** — Seguir cómo fluyen los datos del atacante\n→ **Emulación** — Con **Unicorn Engine** ejecutás fragmentos en aislamiento para descifrar strings/desempaquetar sin correr el malware completo\n→ **Symbolic execution** — Despejar predicados opacos\n→ **Anti-anti-debug** — Parchear los checks (ScyllaHide, plugins)" },
      { h: "Tooling", c: "🧰 El arsenal del reverser avanzado:\n→ **Ghidra / IDA Pro / Binary Ninja** — Disassembler + decompiler, con scripting (Python) y plugins\n→ **Frida** — Instrumentación dinámica: enganchás funciones en runtime e inspeccionás/modificás argumentos en apps vivas (móvil incluido)\n→ **Unicorn / Qiling** — Emulación de CPU/OS para análisis controlado\n→ **x64dbg / WinDbg / TTD** — Debugging, incluido **time-travel** (grabar la ejecución y navegarla hacia atrás)\n→ **angr / Triton** — Análisis simbólico\n\nDominar scripting de Ghidra/Frida es lo que separa al reverser profesional." },
    ],
  },
  {
    id: 80,
    title: "Ejecución Simbólica y Concólica",
    sub: "M76",
    dur: "50m",
    diff: "Doctorado",
    sections: [
      { h: "Concepto", c: "🧮 La **ejecución simbólica** ejecuta un programa con entradas **simbólicas** (variables, no valores concretos). En cada rama, acumula las **restricciones de camino** (path constraints). Un **SMT solver** (Z3) luego resuelve esas restricciones para hallar entradas concretas que llegan a un punto deseado.\n\nEn vez de probar millones de inputs (fuzzing ciego), razona matemáticamente qué input satisface la condición. Ideal para flags de CTF, validadores y caminos profundos." },
      { h: "angr", c: "⚙️ **angr** es el framework de referencia (Python) para análisis simbólico de binarios:\nimport angr\nproj = angr.Project('./crackme')\nsimgr = proj.factory.simulation_manager()\n# explorar hasta una dirección 'éxito', evitando 'fallo'\nsimgr.explore(find=0x401337, avoid=0x401300)\nif simgr.found:\n    print(simgr.found[0].posix.dumps(0))  # el input válido\n\nManeja **estados**, memoria simbólica y constraints. Resuelve crackmes y encuentra inputs sin fuerza bruta." },
      { h: "Concólica (DSE)", c: "🔀 La ejecución puramente simbólica sufre **path explosion**: el número de caminos crece exponencialmente. La **ejecución concólica** (Dynamic Symbolic Execution) combina lo **concreto** + **simbólico**: ejecuta con valores reales por un camino y simboliza selectivamente, podando el árbol.\n\n→ **KLEE** (sobre LLVM) — DSE para generar tests de alta cobertura\n→ Híbridos **fuzzing + simbólico** (Driller, QSYM) — el fuzzer cubre lo fácil/rápido y el solver desbloquea los checks 'mágicos' (ej: if (input == 0xCAFEBABE)) que el fuzzer nunca adivinaría." },
      { h: "Aplicaciones y Límites", c: "🚀 Usos:\n→ **Descubrimiento de vulnerabilidades** — Hallar inputs que disparan crashes/aserciones\n→ **AEG** (Automatic Exploit Generation) — De un crash a un exploit, automáticamente (investigación)\n→ **Deobfuscación** — Despejar predicados opacos y devirtualizar\n→ **Verificación** — Probar que un camino (in)alcanzable\n\n⚠️ **Límites:** path explosion, memoria/loops simbólicos, llamadas a syscalls/entorno (se modelan o concretizan), y criptografía (un hash fuerte es irresoluble para el SMT — por diseño). No es magia: es una herramienta poderosa con fronteras claras." },
    ],
  },
  {
    id: 81,
    title: "Rootkits y Bootkits",
    sub: "M77",
    dur: "55m",
    diff: "Doctorado",
    sections: [
      { h: "Ocultar la Presencia", c: "👻 Un **rootkit** es código diseñado para **ocultar** su presencia (y la del atacante) y mantener acceso privilegiado. Cuanto más profundo opera, más difícil de detectar:\n→ **Userland** — Vive en procesos, manipula APIs (más fácil de detectar)\n→ **Kernel** — Vive en ring 0, puede mentirle a TODO el sistema operativo\n→ **Hypervisor / firmware** — Por debajo del SO (lo más sigiloso)\n\nLa premisa: si controlás la capa que reporta el estado, podés falsear lo que ve el defensor." },
      { h: "Técnicas Userland", c: "🪝 Manipular lo que ven los programas:\n→ **API hooking** — Interceptar funciones (IAT hooking, inline/trampoline) para filtrar resultados: ej. enganchar la enumeración de procesos para ocultar el propio\n→ **DLL injection** — Cargar una DLL maliciosa en otro proceso (CreateRemoteThread, SetWindowsHookEx)\n→ **LD_PRELOAD** (Linux) — Precargar una librería que reemplaza funciones de libc (ocultar archivos a `ls`, conexiones a `netstat`)\n\nDetectables comparando vistas (ej: enumerar procesos por dos métodos distintos y ver discrepancias)." },
      { h: "Rootkits de Kernel", c: "🧠 En ring 0 el rootkit es mucho más potente:\n→ **SSDT hooking** — Interceptar la tabla de syscalls\n→ **DKOM** (Direct Kernel Object Manipulation) — Desenlazar el EPROCESS del proceso de la lista enlazada del kernel → desaparece de la enumeración sin hook\n→ **BYOVD** (Bring Your Own Vulnerable Driver) — Cargar un driver **legítimo pero vulnerable** y explotarlo para ejecutar en kernel → así se carga código sin firma y se **desactiva el EDR** (técnica muy usada hoy por ransomware)\n\nWindows defiende con **DSE** (driver signing), **PatchGuard** (KPP) y la lista de drivers vulnerables bloqueados." },
      { h: "Bootkits y Detección", c: "🥾 Los **bootkits** persisten por debajo del SO (MBR/VBR clásicos, **UEFI** como LoJax). Sobreviven a reinstalar el SO porque cargan antes que él.\n\n🔍 **Detección de rootkits/bootkits:**\n→ **Memory forensics** (Volatility) — Comparar vistas, buscar hooks y objetos desenlazados\n→ **Verificación de integridad** del kernel/firmware y cross-view detection\n→ **ELAM** (Early Launch Anti-Malware) y **Measured Boot + attestation** (TPM)\n→ **chipsec** para firmware\n\nUn rootkit bien hecho exige analizar el sistema desde **afuera** (memoria volcada, booteo desde medio confiable), porque desde adentro te miente." },
    ],
  },
  {
    id: 82,
    title: "Implants, C2 y Evasión de EDR",
    sub: "M78",
    dur: "55m",
    diff: "Doctorado",
    sections: [
      { h: "Implants Modernos", c: "🛰️ Un **implant** (o beacon) es el malware que da acceso persistente y ejecuta órdenes. Los modernos son:\n→ **Modulares** — Un loader pequeño descarga capacidades on-demand\n→ **In-memory / fileless** — Se ejecutan en RAM sin tocar el disco (evaden el AV basado en archivos)\n→ **Staged** — Un stager mínimo trae el payload real\n\nFrameworks (de red team / uso autorizado): Cobalt Strike, Sliver, Mythic, Havoc. El estudio defensivo de cómo operan es clave para detectarlos." },
      { h: "Evasión de EDR", c: "🥷 Los **EDR** enganchan APIs de Windows en userland (ntdll) para inspeccionar el comportamiento. Los implants intentan evadir:\n→ **Unhooking** — Restaurar la ntdll original desde el disco/una copia limpia\n→ **Syscalls directas/indirectas** — Invocar el syscall sin pasar por la ntdll enganchada (Hell's Gate, SysWhispers)\n→ **AMSI/ETW bypass** — Parchear en memoria AmsiScanBuffer y EtwEventWrite para cegar al defensor\n→ **Process injection** — APC injection, process hollowing, module stomping para correr dentro de un proceso legítimo" },
      { h: "Command & Control", c: "📡 El **C2** es el canal entre el implant y el operador:\n→ **Beaconing** — El implant llama a casa periódicamente (con jitter para no ser regular)\n→ **Malleable profiles** — Disfrazar el tráfico C2 de algo legítimo (un GET a una CDN, tráfico tipo Slack)\n→ **Domain fronting** — Esconder el destino real detrás de un dominio de alta reputación (CDN)\n→ **Covert channels** — DNS tunneling, HTTPS, e incluso servicios legítimos (Telegram, GitHub) como C2\n→ **Redirectors** — Capas intermedias que ocultan el servidor real del operador" },
      { h: "Detección y Caza", c: "🔍 Frente a la evasión, la defensa se mueve a capas que el implant no controla:\n→ **Telemetría de kernel/ETW** — Detectar syscalls anómalas, inyección y unhooking desde un punto que userland no puede falsear\n→ **Detección por comportamiento** — Patrones de beaconing (RITA), relaciones parent-child raras, ejecución en memoria sin archivo\n→ **JA3/JARM** y análisis de TLS para C2 cifrado\n→ **Threat hunting** guiado por ATT&CK + threat intel de los frameworks conocidos\n\nEs un juego del gato y el ratón: cada evasión nueva motiva una detección nueva. Entender la ofensiva a este nivel es justo lo que hace a un buen defensor (y cierra el círculo con el track de Blue Team)." },
    ],
  },
  {
    id: 83,
    title: "Vulnerability Research y Fuzzing",
    sub: "M79",
    dur: "55m",
    diff: "Doctorado",
    sections: [
      { h: "La Mentalidad del Vuln Researcher", c: "🔬 El **vulnerability research** busca bugs **desconocidos** (0-days), no parchear CVEs existentes. Empieza por mapear la **superficie de ataque**: qué entradas procesa el target, qué parsers/formatos, qué código es viejo o complejo.\n\nLa selección de target importa: código que parsea datos no confiables (imágenes, fuentes, protocolos), recién escrito o poco auditado, suele rendir más. La pregunta guía: '¿dónde confía el desarrollador en datos que el atacante controla?'" },
      { h: "Fuzzing Coverage-Guided", c: "🎲 El **fuzzing** bombardea el programa con entradas mutadas buscando crashes. El salto cualitativo fue el **coverage-guided**: el fuzzer prioriza inputs que alcanzan código nuevo.\n→ **AFL++** — Mutation-based con feedback de cobertura por instrumentación\n→ **libFuzzer** — In-process, ideal para fuzzear una función (harness):\nextern \"C\" int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size) {\n  parse(data, size);   // la función bajo prueba\n  return 0;\n}\n→ **Sanitizers** — **ASAN** (memoria), **UBSAN**, **MSAN** convierten corrupciones silenciosas en crashes detectables. Fuzzing + sanitizers = la dupla que encuentra la mayoría de los bugs de memoria hoy." },
      { h: "Fuzzing Avanzado", c: "🚀 Para targets difíciles:\n→ **Structure-aware** — Generar inputs que respetan un formato (protobuf, grammar-based) para pasar los checks iniciales y llegar al código profundo\n→ **Snapshot fuzzing** — Restaurar el estado del proceso/VM para fuzzear rápido componentes con estado (kernels, parsers complejos)\n→ **Hybrid (fuzzing + concólico)** — El solver (angr/QSYM, Driller) desbloquea los checks 'mágicos' que el fuzzer no adivina\n→ **Harnessing** — El arte de aislar y alimentar la función objetivo correctamente (un mal harness no encuentra nada)\n→ Buen **corpus** inicial + dictionaries aceleran todo" },
      { h: "Triage y el Ciclo del 0-day", c: "🩺 Miles de crashes → hay que **triarlos**:\n→ **Deduplicación** — Agrupar por stack/causa raíz\n→ **Exploitability** — ¿Es un DoS o un bug de corrupción explotable? (write-what-where, control de PC)\n→ Minimizar el caso (reducir el input al mínimo que reproduce)\n\n🔄 **Ciclo del 0-day:** descubrir → analizar → (a) **disclosure responsable** al vendor, (b) bug bounty, o (c) uso ofensivo (mercado gris/gubernamental, con sus dilemas éticos y legales). El researcher ético reporta y coordina el parche." },
    ],
  },
  {
    id: 84,
    title: "Threat Intelligence y APT Tracking",
    sub: "M80",
    dur: "50m",
    diff: "Doctorado",
    sections: [
      { h: "Fundamentos de CTI", c: "🧭 La **Cyber Threat Intelligence (CTI)** convierte datos de amenazas en conocimiento accionable. Niveles:\n→ **Estratégica** — Para directivos: tendencias, riesgo de negocio, geopolítica\n→ **Operacional** — Campañas y actores que apuntan a tu sector\n→ **Táctica** — IoCs y TTPs para detección inmediata\n\nClave: **IoCs vs TTPs**. Los IoCs (IPs, hashes) son volátiles y baratos de cambiar; las **TTPs** (cómo opera el actor) son caras de cambiar → inteligencia más duradera (la Pyramid of Pain otra vez)." },
      { h: "Frameworks", c: "🗺️ Modelos para estructurar el análisis:\n→ **Diamond Model** — Cada intrusión se describe por 4 vértices: adversario, capacidad, infraestructura y víctima (pivotás de uno a otro)\n→ **Cyber Kill Chain** — Fases del ataque\n→ **MITRE ATT&CK** — El lenguaje común de TTPs\n\n⚠️ **Attribution** — Atribuir a un actor es difícil y se hace con cautela: los atacantes usan **false flags**, infra alquilada y reutilización de herramientas. La confianza se expresa en niveles, nunca como certeza absoluta." },
      { h: "APT Tracking", c: "🎯 Rastrear un **APT** (Advanced Persistent Threat) es clustering de actividad en el tiempo:\n→ Agrupar intrusiones por TTPs, malware, infraestructura y objetivos\n→ Nombrar el cluster (de ahí la sopa de nombres: APT29 = Cozy Bear = Nobelium...)\n→ **Infrastructure pivoting** — De un dominio/IP/certificado conocido, descubrir el resto de la infra del actor (passive DNS, Shodan, certificados)\n→ Mapear **campañas** y la evolución del actor\n\nEl objetivo: anticipar y detectar al adversario por cómo opera, no solo por sus IoCs de hoy." },
      { h: "Operacionalizar la CTI", c: "⚙️ Convertir inteligencia en defensa:\n→ **Feeds** y plataformas (MISP, OpenCTI) para gestionar IoCs/TTPs\n→ **STIX/TAXII** — Estándares para representar e intercambiar CTI de forma automatizable\n→ Integración con **SIEM/EDR** (detecciones) y **threat hunting** (hipótesis basadas en el actor)\n→ **Sharing** — ISACs sectoriales, comunidades; la defensa colectiva es más fuerte\n\nLa CTI mal operacionalizada es solo una lista de IoCs que envejece; bien hecha, dirige proactivamente la defensa." },
    ],
  },
  {
    id: 85,
    title: "Metodología de Security Research",
    sub: "M81",
    dur: "45m",
    diff: "Doctorado",
    sections: [
      { h: "Hacer Investigación", c: "🎓 La investigación de seguridad rigurosa se parece a la científica:\n→ **Pregunta/hipótesis** clara y un aporte novedoso\n→ **Prior work** — Conocer y citar lo previo (no reinventar)\n→ **Reproducibilidad** — Que otros puedan replicar tus resultados (PoCs, datasets, código)\n→ **Evaluación honesta** — Contra ataques/condiciones adaptativas, reportando limitaciones\n→ **Ética** — Minimizar daño, autorización, considerar el dual-use\n\nLa diferencia entre 'encontré un bug' y 'investigación' es el método, la generalidad del aporte y la honestidad de la evaluación." },
      { h: "Responsible Disclosure", c: "📢 Al hallar una vulnerabilidad, cómo divulgarla importa tanto como hallarla:\n→ **Coordinated Vulnerability Disclosure (CVD)** — Reportar al vendor en privado, acordar un plazo (típico 90 días) para parchear antes de publicar\n→ **Full disclosure** — Publicar todo de inmediato (presiona al vendor pero expone a los usuarios)\n→ **Bug bounty** — Programas que pagan por reportes responsables (HackerOne, Bugcrowd)\n→ **Embargo** — Período acordado de silencio mientras se prepara el parche\n\nEl debate full vs coordinated es viejo; el consenso moderno favorece la divulgación coordinada con un plazo razonable." },
      { h: "Ecosistema CVE/CVSS", c: "🏷️ Cómo se cataloga una vulnerabilidad:\n→ **CVE** — Identificador único (CVE-AÑO-NNNN), asignado por un **CNA** (CVE Numbering Authority: vendors, MITRE)\n→ **CVSS** — Score de severidad (ya visto)\n→ **CISA KEV** — Catálogo de vulns explotadas activamente (prioridad de parcheo)\n→ **Advisories** — El vendor publica el aviso + parche; el researcher suele publicar su análisis después\n\nEntender este flujo es parte de divulgar profesionalmente y de priorizar defensivamente." },
      { h: "Comunicar la Investigación", c: "🗣️ El impacto de la investigación depende de comunicarla:\n→ **Papers académicos** — Las top conferences: **IEEE S&P (Oakland), USENIX Security, ACM CCS, NDSS**\n→ **Conferencias de industria** — **Black Hat, DEF CON, REcon**\n→ **PoCs y writeups** — GitHub, blogs técnicos; reproducibles y claros\n→ **Construir reputación** — Una línea de trabajo coherente, CVEs, charlas\n\nLa carrera de research (académica, industria, bug bounty, red team) se construye sobre aportes públicos verificables, no sobre claims privados." },
    ],
  },
  {
    id: 86,
    title: "Formal Methods y Verificación",
    sub: "M82",
    dur: "50m",
    diff: "Doctorado",
    sections: [
      { h: "Probar la Ausencia de Bugs", c: "🧮 Dijkstra: 'el testing puede mostrar la presencia de bugs, nunca su ausencia'. Los **métodos formales** usan matemática para **probar** que un sistema cumple una especificación, descartando clases enteras de fallos.\n\nNo es para todo (es caro), pero en componentes críticos —kernels, criptografía, protocolos— donde un bug es catastrófico, la verificación formal aporta garantías que ninguna cantidad de testing puede dar." },
      { h: "Técnicas", c: "🔧 Dos grandes familias:\n→ **Model checking** — Explorar exhaustivamente todos los estados de un modelo para verificar propiedades (deadlocks, invariantes). Herramientas: **TLA+** (especificar sistemas concurrentes/distribuidos — usado en AWS), **SPIN**\n→ **Theorem proving** — Construir una prueba matemática (asistida por máquina) de que el código cumple su spec. Herramientas: **Coq, Isabelle/HOL, Lean, F***\n→ **Symbolic execution / abstract interpretation** — Análisis estático con garantías\n\nEl model checking es más automático pero sufre explosión de estados; el theorem proving es más potente pero requiere experto y esfuerzo manual." },
      { h: "Sistemas Verificados", c: "🏆 Hitos reales de software formalmente verificado:\n→ **seL4** — Microkernel con prueba de corrección funcional y de propiedades de seguridad (aislamiento). El primer kernel de uso general verificado\n→ **CompCert** — Un compilador C verificado (el código generado preserva la semántica)\n→ **HACL\\* / Fiat-Crypto** — Implementaciones criptográficas verificadas (usadas en Firefox, Linux, WireGuard)\n→ **miTLS / Project Everest** — Una pila TLS verificada\n→ **AWS** usa TLA+ y razonamiento automatizado para sus servicios core" },
      { h: "Límites y Práctica", c: "⚠️ La verificación formal no es magia:\n→ **La spec es el punto débil** — Probás que el código cumple la spec, pero si la spec está mal/incompleta, el bug pasa (la prueba es tan buena como la especificación)\n→ **Escalabilidad** — Verificar sistemas grandes es muy costoso en esfuerzo humano\n→ **Fuera de la prueba** — Side-channels, hardware, supuestos del entorno suelen quedar afuera\n→ **Costo/beneficio** — Se justifica en cripto, protocolos, kernels y aviónica; raramente en una app web típica\n\nEl futuro: herramientas más automáticas y razonamiento asistido por IA que acerquen los métodos formales al desarrollo cotidiano. Es la frontera donde matemática y seguridad se encuentran." },
    ],
  },
  {
    id: 87,
    title: "Gestión de Identidades y Accesos (IAM)",
    sub: "M83",
    dur: "20m",
    diff: "Intermedio",
    sections: [
      { h: "AAA y ciclo de vida", c: "🆔 **Identificación** — declarar quién sos (usuario).\n🔑 **Autenticación** — probarlo (algo que sabés/tenés/sos).\n✅ **Autorización** — qué podés hacer (permisos).\n📒 **Accounting** — registrar lo que hiciste.\n♻️ **Ciclo de vida:** alta (joiner) → cambios (mover) → baja (leaver). El *deprovisioning* a tiempo evita cuentas huérfanas." },
      { h: "Autenticación moderna", c: "🔐 **MFA** — 2+ factores; el resistente a phishing (FIDO2/passkeys) > OTP por SMS.\n🎫 **SSO** — un login para muchas apps (SAML, OIDC/OAuth2).\n🌐 **Federación** — confiar en un IdP externo (Entra ID, Google).\n🚫 **Passwordless** — passkeys/biometría eliminan la contraseña como secreto robable." },
      { h: "Autorización y privilegio", c: "👥 **RBAC** — permisos por rol.\n🏷️ **ABAC** — permisos por atributos/contexto (más granular).\n⬇️ **Menor privilegio** — solo lo necesario; revisión periódica (recertificación).\n👑 **PAM** — bóveda de credenciales, acceso *just-in-time* y grabación de sesión para cuentas privilegiadas.\n🧭 **IGA** — gobierno de identidades: solicitudes, aprobaciones y auditoría." },
      { h: "Los 5 factores de autenticación", c: "Un **factor** es una categoría de evidencia con la que probás quién sos. Los 5 modernos:\n\n1️⃣ **Conocimiento** — algo que sabés (contraseña, PIN). Débil: reusable, phishable.\n2️⃣ **Posesión** — algo que tenés (móvil, TOTP, llave FIDO2). Media–alta según el medio.\n3️⃣ **Inherencia** — algo que sos (huella, cara, iris). Media, no revocable.\n4️⃣ **Ubicación** — dónde estás (IP corporativa, geofence). Contextual.\n5️⃣ **Comportamiento** — cómo actuás (ritmo, patrón). Contextual y continuo.\n\n⚠️ **Regla de oro:** MFA real = combinar factores de **categorías distintas**. Dos contraseñas o dos preguntas de seguridad **NO son MFA**: es un solo factor repetido.\n\n💡 Los factores 4 y 5 sostienen la **autenticación adaptativa**, no reemplazan a un factor fuerte de posesión o inherencia en el login inicial." },
      { h: "Passkeys y FIDO2/WebAuthn", c: "🔑 Las **passkeys** son la evolución de la autenticación: criptografía asimétrica sin secreto compartido.\n\n**Cómo funciona:**\n→ **Registro** — el dispositivo genera un par (privada + pública). La privada **nunca sale del dispositivo**.\n→ **Login** — el servicio manda un *challenge*; el dispositivo lo firma con la privada; el servicio verifica con la pública.\n→ **Origin binding** — la credencial está atada al dominio (`banco.com`). Un dominio phishing (`banc0.com`) **no puede reutilizarla**.\n\n**Variantes:**\n• **Sync passkeys** — Google/Apple/1Password sincronizan; alta UX, buena recuperación.\n• **Device-bound** — YubiKey física; el secreto no sale del hardware.\n• **Attestation** — el servicio verifica al fabricante (banca, gobierno).\n\n💡 **WebAuthn** es la API del navegador; **FIDO2** el stack completo (CTAP2 + WebAuthn).\n🛡️ Son la **única MFA con inmunidad demostrada** al adversary-in-the-middle (evilginx): el proxy no puede replicar la firma porque el origen no coincide." },
      { h: "Passwordless en serio", c: "🚫 **Passwordless** = eliminar el secreto memorizable como credencial primaria.\n\n**Vías:**\n→ **Passkeys / FIDO2** — la referencia moderna, phishing-resistant.\n→ **Magic links** — enlace único por email; útil como fallback, débil como único método (depende del canal email).\n→ **One-tap push con number matching** — el servicio muestra un número; el usuario lo tipea en la app. Mitiga MFA fatigue.\n→ **Biometría local** — huella o cara desbloquean una clave local; el secreto **nunca deja el dispositivo**.\n→ **Certificados** (mTLS, smart card, PIV/CAC) — regulado, alto assurance.\n\n⚠️ **Trampa común:** *passwordless* no es lo mismo que *MFA fuerte*. Un magic link a un email comprometido es **más débil** que contraseña + passkey.\n\n💡 El objetivo no es \"no tener contraseña\", es que **no haya secreto reusable** que pueda ser robado, phisheado o filtrado en una brecha. Cuidar el **downgrade path** de recuperación es crítico: si la vuelta atrás es una pregunta de seguridad, tirás abajo toda la fortaleza." },
      { h: "Autenticación adaptativa y basada en riesgo", c: "🎯 En lugar de aplicar la **misma política** a todos los logins, el sistema **puntúa el riesgo** de cada intento y decide dinámicamente.\n\n**Señales que se evalúan:**\n• **Dispositivo** — reconocido, jailbroken, versión de SO, EDR presente.\n• **Red** — IP corporativa, VPN, país nuevo, proxy/Tor.\n• **Comportamiento** — hora habitual, ritmo, *impossible travel* (login en Madrid y Tokio en 10 min).\n• **Recurso** — un dashboard pesa menos que la consola de admin.\n• **Threat intel** — credenciales filtradas, cuentas en dumps.\n\n**Decisiones posibles:**\n| Puntaje | Acción |\n|---|---|\n| 🟢 Bajo | Login directo (SSO transparente) |\n| 🟡 Medio | Step-up: pedir factor adicional (MFA, passkey) |\n| 🔴 Alto | Bloquear + alertar al SOC |\n\n💡 **Conditional Access** de Entra ID y las policies de Okta/Ping son las implementaciones enterprise más maduras. Se combinan con **continuous authentication** (biometría comportamental durante la sesión).\n\n⚠️ Reglas mal calibradas generan fricción excesiva (usuarios evaden con VPN personal) o falsa sensación (permitir todo por IP corporativa cuando el atacante ya está adentro)." },
      { h: "Ataques a MFA", c: "🎯 La MFA no es infalible. Los vectores más frecuentes que usó el atacante en 2022–2025:\n\n1️⃣ **MFA fatigue / prompt bombing** — ya tiene la contraseña (dump o phishing) y **bombardea con pushes** hasta que un empleado cansado acepta. → **Uber (2022)** y **Cisco (2022)** cayeron por acá.\n\n2️⃣ **SIM swapping** — convence al carrier de portar el número a su SIM y recibe los **SMS OTP**. Clásico contra cripto y banca.\n\n3️⃣ **Adversary-in-the-middle (AiTM)** — **evilginx** o **Modlishka** proxean el sitio real, capturan credenciales **y el token de sesión post-MFA**. TOTP y push SMS caen; **FIDO2/passkeys no** (origin binding).\n\n4️⃣ **Consent phishing (illicit consent grant)** — engaña al usuario para que **conceda permisos OAuth** a una app maliciosa. Salta MFA porque no la necesita; tokens persistentes.\n\n5️⃣ **Push interception / token replay** — malware en el móvil que aprueba el push sin interacción del usuario.\n\n**🛡️ Contramedidas:**\n→ **Number matching** en push (Microsoft, Google) — el usuario tipea un número visible.\n→ **FIDO2 / passkeys** obligatorias para admins y accesos privilegiados.\n→ **Bloquear SMS OTP** para cuentas de alto valor.\n→ **Consent governance** — revisar apps con permisos peligrosos.\n→ **Verified push** atado a dispositivo confiable + señal de riesgo.\n\n💡 La lección de Uber/Cisco: MFA débil + un usuario cansado = compromiso. FIDO2 corta esa cadena." },
    ],
  },
  {
    id: 88,
    title: "Arquitectura de Seguridad y Patrones de Diseño",
    sub: "M84",
    dur: "22m",
    diff: "Avanzado",
    sections: [
      { h: "Principios de diseño seguro", c: "🧱 **Defensa en profundidad** — capas redundantes; si una falla, otra contiene.\n⬇️ **Menor privilegio** — por defecto, denegar.\n🛟 **Fail-safe / fail-secure** — ante error, quedar en estado seguro.\n🔍 **Mediación completa** — validar cada acceso, sin atajos.\n🧰 **Economía de mecanismo** — diseño simple = menos errores.\n🔓 **Diseño abierto** — la seguridad no depende del secreto del diseño (no security by obscurity)." },
      { h: "Patrones y secure by design", c: "🛡️ **Secure by design / by default** — la opción segura es la predeterminada.\n🚪 **Single point of entry** — un punto controlado de acceso.\n✅ **Input validation / output encoding** — frente a inyección y XSS.\n🧩 **Segmentación** — zonas (DMZ, redes internas) que limitan el blast radius.\n🔐 **Secrets management** — bóvedas en vez de credenciales en código.\n🧵 **Threat modeling** (STRIDE) en la fase de diseño, no después." },
      { h: "Zero Trust y marcos", c: "🚫 **ZTA (NIST 800-207)** — sin confianza implícita; verificar identidad + dispositivo + contexto en cada petición.\n🧠 **PDP/PEP** — el *Policy Decision Point* decide, el *Policy Enforcement Point* aplica.\n🧱 **Microsegmentación** — aislamiento por carga de trabajo.\n📐 **SABSA / NIST CSF** — marcos para alinear arquitectura con riesgo y negocio." },
    ],
  },
  {
    id: 89,
    title: "Gobernanza y Gestión de Riesgos",
    sub: "M85",
    dur: "20m",
    diff: "Intermedio",
    sections: [
      { h: "¿Qué es GRC?", c: "🏛️ **Gobernanza** — quién decide y rinde cuentas sobre la seguridad (roles, políticas, comité).\n🎲 **Riesgo** — identificar, analizar y tratar lo que puede salir mal.\n📜 **Cumplimiento** — satisfacer leyes y normas aplicables.\n🎯 **Apetito de riesgo** — cuánto riesgo está dispuesta a aceptar la organización; guía las decisiones." },
      { h: "Análisis de riesgos", c: "🧮 **Riesgo = probabilidad × impacto** (sobre un activo, vía amenaza + vulnerabilidad).\n📋 **Cualitativo** — escalas alto/medio/bajo (rápido).\n🔢 **Cuantitativo** — €/año (ALE = SLE × ARO); base de FAIR.\n🗂️ **Metodologías:** ISO 27005, MAGERIT (España), NIST RMF (SP 800-30/37).\n📊 **Mapa de calor** para priorizar." },
      { h: "Tratamiento del riesgo", c: "🛡️ **Mitigar** — aplicar controles para reducirlo.\n📤 **Transferir** — seguro / tercero.\n🚫 **Evitar** — no realizar la actividad.\n✅ **Aceptar** — asumirlo (dentro del apetito), documentado y aprobado.\n📈 **Riesgo residual** — lo que queda tras el control; debe quedar bajo el apetito.\n📉 **KRIs** — indicadores que alertan si el riesgo sube." },
    ],
  },
  {
    id: 90,
    title: "Cumplimiento Normativo y Auditoría",
    sub: "M86",
    dur: "22m",
    diff: "Avanzado",
    sections: [
      { h: "Marcos normativos", c: "🇪🇺 **RGPD/GDPR** — datos personales en la UE; derechos ARCO+, DPO, notificación de brechas en 72h, multas hasta 4% facturación.\n🏥 **HIPAA** — datos de salud (EE.UU.).\n💳 **PCI-DSS** — datos de tarjetas de pago.\n☁️ **SOC 2** — controles en proveedores de servicios (Trust Services Criteria).\n🛡️ **ENS** — Esquema Nacional de Seguridad (sector público español)." },
      { h: "ISO 27001 y SGSI", c: "📋 **ISO 27001** — norma certificable de un **SGSI** (Sistema de Gestión de Seguridad de la Información).\n♻️ **Ciclo PDCA** — Planificar, Hacer, Verificar, Actuar.\n📎 **Anexo A** — catálogo de controles (referenciado por ISO 27002).\n🎯 **Declaración de aplicabilidad (SoA)** — qué controles aplican y por qué.\n🤝 **ENS ↔ ISO 27001** — se complementan en organismos públicos." },
      { h: "Auditoría y evidencias", c: "🔍 **Auditoría** — verificar que los controles existen y funcionan.\n🧾 **Evidencias** — logs, capturas, políticas firmadas, registros.\n⚠️ **No conformidad** — mayor (falla sistémica del control) o menor (desviación puntual).\n🛠️ **Plan de acción correctiva (CAPA)** — corrige la causa raíz.\n🔄 **Type I vs Type II (SOC 2)** — diseño en un instante vs eficacia operativa durante un periodo." },
    ],
  },
];
export function getLesson(id: number): Lesson | undefined {
  return LESSONS.find((l) => l.id === id);
}
// Maps a module id (e.g. 1) to the lessons whose `sub` references that module ("M1").
export function lessonsForModule(moduleId: number): Lesson[] {
  const tag = `M${moduleId}`;
  return LESSONS.filter((l) => l.sub === tag);
}
// Primera lección (ordenada por id) sin quiz hecho, excluyendo la lección actual.
// Sirve para ofrecer "Continuar →" al terminar un quiz/examen.
export function nextPendingLesson(currentId: number, takenIds: Set<number>): Lesson | null {
  const sorted = [...LESSONS].sort((a, b) => a.id - b.id);
  return sorted.find((l) => l.id !== currentId && !takenIds.has(l.id)) ?? null;
}
