// Biblioteca de CyberSec Academy — catálogo curado de recursos GRATUITOS y
// legalmente distribuibles en español (open-access, Creative Commons, dominio
// público, documentación oficial y guías de organismos públicos como INCIBE /
// CCN-CERT). NO se incluyen PDFs con copyright; para esos, el usuario sube su
// propia copia vía el gestor de subidas (securities_library_uploads).
//
// Cada entrada apunta a la FUENTE OFICIAL (dominio estable). Verificá el enlace
// antes de depender de él; las guías de organismos rotan rutas ocasionalmente.
// `cat` se alinea con las categorías del syllabus para mapear lecturas a módulos.

export type LibraryFormat = "pdf" | "web";
export type LibraryLevel = "b" | "i" | "a" | "all";

export interface LibraryBook {
  id: number;
  title: string;
  author: string;
  cat: string;          // categoría (alineada al syllabus cuando aplica)
  level: LibraryLevel;  // dificultad orientativa
  format: LibraryFormat;
  url: string;          // fuente oficial gratuita
  license: string;      // licencia / origen
  year?: number;
  desc: string;
}

export const LIBRARY: LibraryBook[] = [
  // ── Fundamentos ──
  { id: 1, title: "Ciberseguridad para todos: la ciberseguridad al alcance de todos", author: "INCIBE", cat: "Fundamentos", level: "b", format: "pdf", url: "https://www.incibe.es/sites/default/files/docs/senior/guia_ciberseguridad_para_todos.pdf", license: "Publicación oficial gratuita (organismo público español)", desc: "Guía básica de conceptos esenciales de ciberseguridad y privacidad digital orientada al público general." },
  { id: 2, title: "Glosario de términos de ciberseguridad", author: "INCIBE", cat: "Fundamentos", level: "b", format: "web", url: "https://www.incibe.es/incibe-cert/glosario-de-terminos", license: "INCIBE (uso libre)", desc: "Glosario de referencia del Instituto Nacional de Ciberseguridad de España." },
  { id: 3, title: "Guía de ciberataques: todo lo que debes saber a nivel usuario", author: "INCIBE / OSI (Oficina de Seguridad del Internauta)", cat: "Fundamentos", level: "b", format: "pdf", url: "https://www.incibe.es/sites/default/files/docs/guia-ciberataques/osi-guia-ciberataques.pdf", license: "Publicación oficial gratuita (organismo público español)", desc: "Guía introductoria que explica los tipos de ciberataques y amenazas más comunes y cómo protegerse de ellos." },
  { id: 4, title: "Recursos de ciberseguridad para ciudadanía", author: "INCIBE", cat: "Fundamentos", level: "b", format: "pdf", url: "https://www.incibe.es/ciudadania/recursos", license: "INCIBE (uso libre)", desc: "Guías y materiales en PDF sobre privacidad, fraude online, redes sociales y dispositivos." },
  { id: 5, title: "OWASP Prácticas de Codificación Segura - Guía rápida de referencia (español)", author: "OWASP Foundation (capítulo OWASP Uruguay)", cat: "Fundamentos", level: "i", format: "web", url: "https://owasp.org/www-project-secure-coding-practices-quick-reference-guide/stable-es/01-introduction/05-introduction", license: "CC BY-SA", desc: "Checklist de prácticas de codificación segura organizada en 14 áreas temáticas, traducida al español." },
  { id: 6, title: "OWASP Secure Coding Practices Quick Reference Guide (proyecto)", author: "OWASP Foundation", cat: "Fundamentos", level: "i", format: "web", url: "https://owasp.org/www-project-secure-coding-practices-quick-reference-guide/", license: "CC BY-SA", desc: "Página oficial del proyecto con todas las versiones de la guía de prácticas de codificación segura." },
  { id: 7, title: "OWASP Top 10:2021 (edición en español)", author: "OWASP Foundation", cat: "Fundamentos", level: "i", format: "web", url: "https://owasp.org/Top10/2021/es/", license: "CC BY-SA 4.0", desc: "Lista de referencia de los diez riesgos de seguridad más críticos en aplicaciones web, traducida al español." },
  { id: 8, title: "OWASP Web Security Testing Guide (WSTG)", author: "OWASP Foundation", cat: "Fundamentos", level: "a", format: "web", url: "https://owasp.org/www-project-web-security-testing-guide/", license: "CC BY-SA 4.0", desc: "Guía integral y metodología para realizar pruebas de seguridad sobre aplicaciones y servicios web." },
  { id: 9, title: "Guías y estudios de ciberseguridad de INCIBE-CERT", author: "INCIBE (Instituto Nacional de Ciberseguridad de España)", cat: "Fundamentos", level: "all", format: "web", url: "https://www.incibe.es/incibe-cert/guias-y-estudios/guias", license: "Publicación oficial gratuita (organismo público español)", desc: "Repositorio oficial de guías de ciberseguridad de INCIBE-CERT sobre amenazas, malware, gestión de incidentes y buenas prácticas." },
  // ── Redes ──
  { id: 10, title: "El cortafuegos: qué es y cómo configurarlo", author: "INCIBE (Instituto Nacional de Ciberseguridad)", cat: "Redes", level: "b", format: "web", url: "https://www.incibe.es/ciudadania/tematicas/configuraciones-dispositivos/cortafuegos", license: "Contenido público INCIBE (Gobierno de España)", desc: "Introducción de INCIBE a los cortafuegos: funcionalidades (filtrado de contenido, reglas personalizadas, control de acceso) y guías para activarlo en Windows, macOS, Android e iOS." },
  { id: 11, title: "El modelo OSI y los protocolos de red (pila OSI)", author: "blyx.com", cat: "Redes", level: "b", format: "pdf", url: "https://blyx.com/public/docs/pila_OSI.pdf", license: "Documento técnico de acceso público", desc: "Documento que describe las capas del modelo OSI y los principales protocolos de red asociados." },
  { id: 12, title: "Introducción a la programación del lado servidor (MDN en español)", author: "Mozilla / comunidad MDN", cat: "Redes", level: "b", format: "web", url: "https://developer.mozilla.org/es/docs/Learn_web_development/Extensions/Server-side/First_steps/Introduction", license: "CC BY-SA 2.5 (docs oficiales MDN)", desc: "Guía oficial sobre programación del lado servidor, cliente vs servidor y arquitectura de sitios dinámicos." },
  { id: 13, title: "Introducción al modelo OSI y al modelo TCP/IP", author: "José Juan Sánchez (DAW)", cat: "Redes", level: "b", format: "pdf", url: "https://josejuansanchez.org/daw/introduccion_modelo_osi/index.pdf", license: "Material docente de acceso abierto", desc: "Material didáctico que introduce y compara el modelo OSI y el modelo TCP/IP por capas." },
  { id: 14, title: "Configuración básica de redes TCP/IP y modelo OSI (apuntes)", author: "Dpto. de Tecnología Electrónica, Universidad de Sevilla", cat: "Redes", level: "i", format: "pdf", url: "https://www.dte.us.es/personal/sivianes/TC/teorica.pdf", license: "Apuntes universitarios de acceso público", desc: "Apuntes universitarios que explican el modelo OSI y la configuración básica de redes TCP/IP." },
  { id: 15, title: "Configuración de ModSecurity (WAF) en Apache/Nginx", author: "CubePath Docs", cat: "Redes", level: "i", format: "web", url: "https://cubepath.com/docs/seguridad-del-servidor/configuracion-de-modsecurity-waf-en-apache-nginx", license: "Documentación pública CubePath", desc: "Guía en español del Web Application Firewall ModSecurity con OWASP Core Rule Set: instalación en Apache y Nginx, reglas personalizadas y hardening contra inyección SQL y XSS." },
  { id: 16, title: "Guía de referencia de Nmap (es)", author: "Gordon 'Fyodor' Lyon", cat: "Redes", level: "i", format: "web", url: "https://nmap.org/man/es/", license: "Nmap (documentación libre)", desc: "Página de manual de Nmap traducida al español: tipos de escaneo, flags y detección." },
  { id: 17, title: "Nftables, firewall de Linux: configuración y características", author: "RedesZone", cat: "Redes", level: "i", format: "web", url: "https://www.redeszone.net/tutoriales/seguridad/nftables-firewall-linux-configuracion/", license: "Copyright RedesZone (lectura libre)", desc: "Guía práctica de nftables, el sustituto moderno de iptables: diferencias de arquitectura, instalación, creación de tablas/cadenas/reglas y configuración de NAT (SNAT/DNAT)." },
  { id: 18, title: "Protocolos TCP/IP (capítulo de repositorio universitario)", author: "Repositorio Digital UTN (Universidad Técnica del Norte)", cat: "Redes", level: "i", format: "pdf", url: "https://repositorio.utn.edu.ec/bitstream/123456789/1096/5/04%20ISC%20019%20Capitulo%202%20TCP%20IP.pdf", license: "Repositorio universitario open-access", desc: "Capítulo académico que detalla la pila de protocolos TCP/IP (TCP, IP, HTTP, DNS, FTP, ARP, etc.)." },
  { id: 19, title: "Tutorial de iptables (netfilter) en español", author: "Oskar Andreasson (trad. Xavier Bartol)", cat: "Redes", level: "i", format: "web", url: "https://www.frozentux.net/iptables-tutorial/spanish/iptables-tutorial.html", license: "GNU Free Documentation License", desc: "Tutorial clásico y completo de iptables/netfilter: tablas, cadenas, seguimiento de estado de conexiones, NAT y scripts de cortafuegos de ejemplo. Referencia canónica para entender el filtrado de paquetes en Linux." },
  { id: 20, title: "Acceso seguro a SCI: arquitectura de red para accesos externos", author: "INCIBE-CERT", cat: "Redes", level: "a", format: "web", url: "https://www.incibe.es/incibe-cert/blog/acceso-seguro-sci-arquitectura-red-accesos-externos", license: "Contenido público INCIBE-CERT", desc: "Diseño de arquitectura de red segura con segmentación: modelo ISA-95, zonas y conductos, cortafuegos, VLANs, DMZ con máquinas de salto bastionadas y VPN con doble autenticación." },
  { id: 21, title: "Cortafuegos industriales, el principal elemento de defensa de tu SCI", author: "INCIBE-CERT", cat: "Redes", level: "a", format: "web", url: "https://www.incibe.es/incibe-cert/blog/cortafuegos-industriales-el-principal-elemento-defensa-tu-sci", license: "Contenido público INCIBE-CERT", desc: "Cortafuegos en entornos industriales (SCI/OT): modo transparente, inspección profunda de paquetes (DPI) sobre protocolos Modbus/DNP3/IEC104, inserción en VLAN y análisis de tráfico cifrado." },
  { id: 22, title: "Documentación de HTTP (MDN Web Docs en español)", author: "Mozilla / comunidad MDN", cat: "Redes", level: "all", format: "web", url: "https://developer.mozilla.org/es/docs/Web/HTTP", license: "CC BY-SA 2.5 (docs oficiales MDN)", desc: "Documentación oficial sobre el protocolo HTTP: mensajes, cabeceras, métodos, códigos de estado y caché." },
  // ── Sistemas ──
  { id: 23, title: "Curso: Introducción a GNU/Linux (notas)", author: "Dr. Jesús Emmanuel Solís Pérez (jesolisp)", cat: "Sistemas", level: "b", format: "pdf", url: "https://github.com/jesolisp/Curso-Introduccion-Linux", license: "GPL-3.0", desc: "Notas de un curso universitario de introducción a GNU/Linux en seis unidades, con PDF y notebooks." },
  { id: 24, title: "El Manual de BASH Scripting Básico para Principiantes", author: "Comunidad Wikilibros", cat: "Sistemas", level: "b", format: "web", url: "https://es.wikibooks.org/wiki/El_Manual_de_BASH_Scripting_B%C3%A1sico_para_Principiantes", license: "CC BY-SA 4.0", desc: "Manual de scripting en Bash para automatizar tareas de administración de sistemas: variables, condicionales y bucles." },
  { id: 25, title: "GNU/Linux (manual introductorio en Wikilibros)", author: "Comunidad Wikilibros", cat: "Sistemas", level: "b", format: "web", url: "https://es.wikibooks.org/wiki/GNU/Linux", license: "CC BY-SA 4.0", desc: "Libro colaborativo de introducción a GNU/Linux desde la perspectiva del usuario." },
  { id: 26, title: "Linux101 - Curso de introducción a GNU/Linux", author: "LIDSOL (emilio1625, basado en LFS101x de The Linux Foundation)", cat: "Sistemas", level: "b", format: "web", url: "https://github.com/emilio1625/Linux101", license: "CC BY 4.0", desc: "Curso introductorio a GNU/Linux en español con material derivado del curso oficial de The Linux Foundation." },
  { id: 27, title: "Introducción a la Administración de Sistemas Unix/Linux", author: "GSyC, Universidad Rey Juan Carlos (URJC)", cat: "Sistemas", level: "i", format: "pdf", url: "https://gsyc.urjc.es/~mortuno/lagrs/01-intro_linux.pdf", license: "CC BY-SA 4.0 (material docente URJC)", desc: "Transparencias docentes que introducen la administración de sistemas Unix/Linux." },
  { id: 28, title: "CCN-STIC 808 - Guía de seguridad de las TIC (verificación del cumplimiento del ENS)", author: "CCN-CERT / Centro Criptológico Nacional", cat: "Sistemas", level: "a", format: "pdf", url: "https://www.ismsforum.es/ficheros/descargas/ccn-stic-808.pdf", license: "Guía oficial pública (organismo público español)", desc: "Guía oficial sobre clasificación de medidas de protección y hardening de sistemas según el Esquema Nacional de Seguridad." },
  { id: 29, title: "Guías CCN-STIC", author: "CCN-CERT (Centro Criptológico Nacional)", cat: "Sistemas", level: "a", format: "pdf", url: "https://www.ccn-cert.cni.es/guias/guias-series-ccn-stic.html", license: "CCN-CERT (uso público)", desc: "Serie de guías técnicas de seguridad (hardening, ENS, configuración segura) del CCN español." },
  // ── Criptografía ──
  { id: 30, title: "Curso de Criptografía (Ciencias de la computación)", author: "Khan Academy", cat: "Criptografía", level: "b", format: "web", url: "https://es.khanacademy.org/computing/computer-science/cryptography", license: "Contenido educativo gratuito de Khan Academy (organización sin ánimo de lucro).", desc: "Curso introductorio gratuito en español: criptografía antigua (César, análisis de frecuencia), cifrados modernos, aritmética modular y aleatoriedad, base de los algoritmos actuales." },
  { id: 31, title: "Principios y recomendaciones básicas en Ciberseguridad (CCN-CERT BP/01)", author: "CCN-CERT (Centro Criptológico Nacional, España)", cat: "Criptografía", level: "b", format: "pdf", url: "https://www.ospi.es/images/documentos/archivos/CCN-CERT_BP_01_Principios_y_recomendaciones_basicas_de_seguridad_202103.pdf", license: "Informe oficial de buenas prácticas del CCN-CERT (organismo público español), distribución gratuita.", desc: "Guía oficial con principios básicos de ciberseguridad: cifrado, contraseñas, actualización y protección de la información. Útil como base previa a temas criptográficos." },
  { id: 32, title: "Criptografía y Seguridad en Computadores (5ª edición)", author: "Manuel José Lucena López (Universidad de Jaén)", cat: "Criptografía", level: "i", format: "pdf", url: "https://ccia.esei.uvigo.es/docencia/SSI/cripto.pdf", license: "Libro de libre distribución del autor (GNU FDL); copia docente alojada por la Universidad de Vigo.", desc: "Manual universitario clásico que parte de los fundamentos matemáticos y cubre cifrado simétrico y asimétrico, funciones hash, PGP, firma digital y protocolos. Texto de referencia en español." },
  { id: 33, title: "Crypt4you — Aula Virtual de Criptografía y Seguridad de la Información (MOOC)", author: "Jorge Ramió y Alfonso Muñoz (Criptored, UPM)", cat: "Criptografía", level: "i", format: "web", url: "http://www.criptored.upm.es/crypt4you/portada.html", license: "MOOC gratuito de la Red Temática Criptored (Universidad Politécnica de Madrid).", desc: "Primer MOOC en español de criptografía. Incluye cursos por lecciones como 'El algoritmo RSA' e 'Introducción a la seguridad informática y criptografía clásica'." },
  { id: 34, title: "Una función hash desde cero (TFG)", author: "Ana Isabel Toledo Navarro (Universidad Politécnica de Madrid)", cat: "Criptografía", level: "i", format: "pdf", url: "https://oa.upm.es/83727/1/TFG_ANA_ISABEL_TOLEDO_NAVARRO.pdf", license: "Acceso abierto — Archivo Digital UPM (oa.upm.es).", desc: "Trabajo de Fin de Grado open-access sobre el diseño y los fundamentos de las funciones hash en criptografía, partiendo desde la criptografía clásica." },
  { id: 35, title: "Libro Electrónico de Seguridad Informática y Criptografía (v4.1)", author: "Jorge Ramió Aguirre (Universidad Politécnica de Madrid / Criptored)", cat: "Criptografía", level: "all", format: "web", url: "https://www.criptored.es/guiateoria/gt_m001a.htm", license: "Libre distribución para fines educativos/personales manteniendo créditos del autor (Criptored, UPM).", desc: "Obra de referencia en español sobre seguridad informática y criptografía: gestión de la seguridad, criptografía clásica y moderna, cifrado de clave pública y privada. Más de 1100 diapositivas." },
  // ── Web Security ──
  { id: 36, title: "Análisis de ataques web (SQL injection, XSS, CSRF) con DVWA — TFG", author: "Javier Sánchez González (Universidad Politécnica de Madrid)", cat: "Web Security", level: "i", format: "pdf", url: "https://oa.upm.es/44509/1/TFG_JAVIER_SANCHEZ_GONZALEZ.pdf", license: "Acceso abierto — Archivo Digital UPM (oa.upm.es).", desc: "Trabajo de Fin de Grado open-access que detalla SQL Injection, XSS, CSRF, DDoS, LFI y RFI, sus variantes y prevención, con prácticas en el entorno DVWA." },
  { id: 37, title: "Desarrollo e integración segura (Guía del Desarrollador OWASP, español)", author: "OWASP Foundation", cat: "Web Security", level: "i", format: "web", url: "https://devguide.owasp.org/es/02-foundations/02-secure-development/", license: "Creative Commons Attribution-ShareAlike 4.0 (OWASP).", desc: "Capítulo de la Guía del Desarrollador OWASP sobre el ciclo de vida seguro de desarrollo (SDLC) y DevSecOps, con fases de seguridad integradas y recursos de verificación." },
  { id: 38, title: "Desarrollo Seguro usando OWASP", author: "OWASP Foundation", cat: "Web Security", level: "i", format: "pdf", url: "https://wiki.owasp.org/images/0/07/Desarrollo_Seguro_usando_OWASP.pdf", license: "Material OWASP de libre distribución (licencia abierta OWASP/BSD).", desc: "Presentación en español sobre desarrollo seguro de aplicaciones web aplicando OWASP: principales riesgos, gestión de sesiones, inyección de código y ciclo de desarrollo seguro." },
  { id: 39, title: "OWASP Top 10 — 2017 (Los diez riesgos más críticos en aplicaciones web)", author: "OWASP Foundation", cat: "Web Security", level: "i", format: "pdf", url: "https://wiki.owasp.org/images/5/5e/OWASP-Top-10-2017-es.pdf", license: "Creative Commons Attribution-ShareAlike 4.0 (OWASP).", desc: "Traducción oficial al español del OWASP Top 10 2017: inyección, autenticación rota, XSS, exposición de datos sensibles, control de acceso y más, con ejemplos y prevención." },
  { id: 40, title: "OWASP Top 10:2021 (es)", author: "OWASP Foundation", cat: "Web Security", level: "i", format: "web", url: "https://owasp.org/Top10/es/", license: "CC BY-SA 4.0", desc: "Los 10 riesgos más críticos en aplicaciones web, con la traducción oficial al español." },
  { id: 41, title: "OWASP Cheat Sheet Series", author: "OWASP Foundation", cat: "Web Security", level: "a", format: "web", url: "https://cheatsheetseries.owasp.org/", license: "CC BY 3.0", desc: "Guías concisas de implementación segura por tema (autenticación, XSS, SQLi, etc.)." },
  { id: 42, title: "OWASP Web Security Testing Guide (WSTG) — sección en español", author: "OWASP Foundation (Guía del Desarrollador OWASP)", cat: "Web Security", level: "a", format: "web", url: "https://devguide.owasp.org/es/06-verification/01-guides/01-wstg/", license: "Creative Commons Attribution-ShareAlike 4.0 (OWASP).", desc: "Metodología de OWASP para probar la seguridad de aplicaciones y servicios web: qué es la WSTG, por qué y cómo usarla en cada fase del desarrollo." },
  // ── Pentesting ──
  { id: 43, title: "Auditoría de seguridad: análisis y explotación de vulnerabilidades web (TFG)", author: "Álvaro Almonacid de Cárdenas (Universidad Politécnica de Madrid)", cat: "Pentesting", level: "i", format: "pdf", url: "https://oa.upm.es/56124/1/TFG_ALVARO_ALMONACID_DE_CARDENAS.pdf", license: "Acceso abierto — Archivo Digital UPM (oa.upm.es).", desc: "TFG open-access sobre auditoría técnica de seguridad: análisis y explotación de XSS, CSRF, SQL Injection y subida de ficheros, con metodología de pentesting aplicada." },
  { id: 44, title: "Estudio de herramientas para la actividad de reconocimiento", author: "INCIBE-CERT (Instituto Nacional de Ciberseguridad, España)", cat: "Pentesting", level: "i", format: "pdf", url: "https://www.incibe.es/sites/default/files/2023-11/INCIBE-CERT_ESTUDIO_DE_HERRAMIENTAS_DE_RECONOCIMIENTO_2023_v1.1.pdf", license: "Publicación oficial gratuita de INCIBE-CERT, reproducible citando la fuente.", desc: "Estudio técnico oficial sobre herramientas de reconocimiento (fase inicial del pentesting): recopilación de información y OSINT aplicados a auditorías de seguridad." },
  { id: 45, title: "Guía de referencia de Nmap (página de manual en español)", author: "Proyecto Nmap (trad. A. Busleiman, P. Fernández, J. Fernández-Sanguino)", cat: "Pentesting", level: "i", format: "web", url: "https://nmap.org/man/es/index.html", license: "Documentación oficial de Nmap (traducción no oficial publicada en nmap.org).", desc: "Manual de referencia de Nmap en español: especificación de objetivos, descubrimiento de sistemas, escaneo de puertos, detección de servicios/versiones y sistema operativo." },
  { id: 46, title: "Hacking Ético", author: "Carlos Tori", cat: "Pentesting", level: "i", format: "pdf", url: "https://openlibra.com/es/book/hacking-etico", license: "Edición gratuita liberada por el autor, alojada en OpenLibra (biblioteca de publicaciones libres).", desc: "Libro clásico en español sobre hacking ético y auditorías de seguridad (pentesting): recopilación de información, escaneo con Nmap, explotación con Metasploit y herramientas relacionadas." },
  { id: 47, title: "Metodología de Pentesting (TFG)", author: "Jaime Guardiola González (Universidad Politécnica de Madrid)", cat: "Pentesting", level: "i", format: "pdf", url: "https://oa.upm.es/64106/1/TFG_JAIME_GUARDIOLA_GONZALEZ.pdf", license: "Acceso abierto — Archivo Digital UPM (oa.upm.es).", desc: "Trabajo de Fin de Grado open-access que desarrolla una metodología de pentesting paso a paso: fases, herramientas y enfoque práctico para auditorías de seguridad." },
  { id: 48, title: "Metasploit Unleashed — Curso gratuito de hacking ético", author: "OffSec (Offensive Security)", cat: "Pentesting", level: "a", format: "web", url: "https://www.offsec.com/metasploit-unleashed/introduction/", license: "Curso online gratuito de OffSec (fines benéficos, acceso libre).", desc: "Curso de referencia sobre el framework Metasploit: fundamentos, recopilación de información, explotación, payloads y post-explotación. Está en inglés pero es la guía gratuita estándar del sector." },
  // ── Social Eng. ──
  { id: 49, title: "El ciclo de la Ingeniería Social", author: "INCIBE (Instituto Nacional de Ciberseguridad, España)", cat: "Social Eng.", level: "b", format: "pdf", url: "https://www.incibe.es/sites/default/files/docs/c14-pdf-ciclo-de-la-ingenieria-social.pdf", license: "Material oficial gratuito de INCIBE, reproducible citando la fuente.", desc: "Documento oficial que explica las fases del ciclo de la ingeniería social: recolección de información, generación de confianza, abuso de confianza y ejecución del ataque." },
  { id: 50, title: "El correo electrónico: principales fraudes y riesgos (documento formativo)", author: "INCIBE / OSI (copia formativa de la Universidad de Sevilla)", cat: "Social Eng.", level: "b", format: "pdf", url: "https://osi.us.es/sites/osi/files/doc/formacion/concienciacion/pildoras/04_documento_formativo_fraudes.pdf", license: "Material de concienciación gratuito basado en contenidos INCIBE/OSI (copia institucional Universidad de Sevilla).", desc: "Documento formativo sobre los principales fraudes por correo (phishing, suplantación de identidad), señales para reconocer correos fraudulentos y pautas de actuación." },
  { id: 51, title: "Kit de Concienciación — Phishing (RECUERDA)", author: "INCIBE (Instituto Nacional de Ciberseguridad, España)", cat: "Social Eng.", level: "b", format: "pdf", url: "https://si.ua.es/es/documentos/incibe/phising.pdf", license: "Material de concienciación gratuito de INCIBE (copia institucional de la Universidad de Alicante).", desc: "Ficha de concienciación sobre phishing como forma de ingeniería social: cómo el atacante suplanta a un tercero de confianza para obtener información confidencial y cómo prevenirlo." },
  { id: 52, title: "Técnicas de ingeniería social (infografía): ¿Cómo consiguen engañarnos?", author: "INCIBE (Instituto Nacional de Ciberseguridad, España)", cat: "Social Eng.", level: "b", format: "pdf", url: "https://www.incibe.es/sites/default/files/docs/c14_pdf_infografia-tecnicas-ingenieria-social.pdf", license: "Material oficial gratuito de INCIBE, reproducible citando la fuente.", desc: "Infografía oficial de INCIBE que resume las principales técnicas de ingeniería social usadas por los atacantes y cómo reconocerlas para no caer en el engaño." },
  { id: 53, title: "Buenas Prácticas en el uso del correo electrónico (CCN-CERT BP-02/16)", author: "CCN-CERT (Centro Criptológico Nacional, España)", cat: "Social Eng.", level: "i", format: "pdf", url: "https://www.burgos.es/sites/default/files/file/destacado/ccn-cert_bp-02-16_correo_electronico.pdf", license: "Informe oficial de buenas prácticas del CCN-CERT (organismo público), distribución gratuita.", desc: "Guía oficial sobre amenazas en el correo electrónico: campañas de phishing e ingeniería social, identificación de enlaces y adjuntos maliciosos y medidas de protección." },
  { id: 54, title: "Buenas Prácticas en Redes Sociales (CCN-CERT BP-02/17)", author: "CCN-CERT (Centro Criptológico Nacional, España)", cat: "Social Eng.", level: "i", format: "pdf", url: "https://www.ospi.es/images/documentos/archivos/CCN-CERT_BP-02-17_Redes-Sociales.pdf", license: "Informe oficial de buenas prácticas del CCN-CERT (organismo público), distribución gratuita.", desc: "Guía oficial sobre los riesgos de exposición de información personal en redes sociales y cómo los ciberdelincuentes la aprovechan para ataques de ingeniería social." },
  // ── Malware ──
  { id: 55, title: "Programa: Analisis de malware en Android", author: "INCIBE", cat: "Malware", level: "b", format: "web", url: "https://www.incibe.es/incibe/jornadas-incibe-espacios-ciberseguridad/estudiantes/programa-analisis-malware-android", license: "INCIBE (uso publico/educativo)", desc: "Programa formativo introductorio sobre seguridad en Android: fundamentos del sistema, lenguaje Java, tipos de malware movil, vulnerabilidades y mecanismos de defensa." },
  { id: 56, title: "Análisis dinámico de malware en entornos controlados", author: "UC3M (e-Archivo)", cat: "Malware", level: "i", format: "pdf", url: "https://e-archivo.uc3m.es/entities/publication/a4d91dcd-7c6d-4812-9d16-e3586168e292", license: "TFG open-access UC3M (e-Archivo)", desc: "Herramienta de análisis dinámico automatizado: ejecuta muestras en un entorno vulnerable y genera un informe estándar." },
  { id: 57, title: "Análisis estático y dinámico de malware", author: "Gomiz Barreda (UAH)", cat: "Malware", level: "i", format: "pdf", url: "https://ebuah.uah.es/dspace/bitstream/handle/10017/52493/TFG_Gomiz_Barreda_2022.pdf", license: "TFG open-access UAH (e_Buah)", desc: "Enfoques de análisis estático y dinámico de malware, diferencias y ventajas/inconvenientes." },
  { id: 58, title: "Análisis y ejecución de malware en un entorno controlado", author: "Pau Caro Avia (UPC)", cat: "Malware", level: "i", format: "pdf", url: "https://upcommons.upc.edu/handle/2117/372262", license: "TFG open-access UPC (CC BY-NC-ND 3.0 ES)", desc: "Montaje de un laboratorio de malware (VirtualBox, Windows 10, REMnux) con herramientas open source para análisis estático y dinámico." },
  { id: 59, title: "Creacion de un entorno controlado de analisis de Malware en Windows. Analisis y catalogacion de un malware", author: "Vicente Sanchez Cervera (RiuNet - UPV)", cat: "Malware", level: "i", format: "pdf", url: "https://riunet.upv.es/server/api/core/bitstreams/8f7d742b-7209-478c-80e8-48b7768d568c/content", license: "Acceso abierto (repositorio universitario UPV)", desc: "Trabajo academico de 84 paginas sobre el montaje de un laboratorio controlado de analisis de malware en Windows, incluyendo el analisis y catalogacion practica de una muestra real." },
  { id: 60, title: "Detección de malware con indicadores de compromiso: YARA y SNORT", author: "F. J. Ros Raposo (Univ. de Sevilla)", cat: "Malware", level: "i", format: "pdf", url: "https://ereding.etsi.us.es/bibing/proyectos/abreproy/94437/fichero/TFG+4437+Ros+Raposo,+Francisco+Javier.pdf", license: "TFG open-access Universidad de Sevilla (ETSI)", desc: "Detección de amenazas mediante indicadores de compromiso y reglas YARA y SNORT." },
  { id: 61, title: "Ejecución de malware en entornos controlados (TFG)", author: "Adolfo Gómiz Barreda - Universidad de Alcalá", cat: "Malware", level: "i", format: "pdf", url: "https://ebuah.uah.es/dspace/bitstream/handle/10017/52493/TFG_Gomiz_Barreda_2022.pdf?sequence=1&isAllowed=y", license: "CC BY-NC-ND 4.0", desc: "Trabajo Fin de Grado sobre tecnologías, herramientas y técnicas para ejecutar y analizar muestras maliciosas (ransomware, gusanos, Dorkbot) en entornos controlados de sandbox." },
  { id: 62, title: "Estudio del análisis de Grandoreiro", author: "INCIBE-CERT", cat: "Malware", level: "i", format: "pdf", url: "https://www.incibe.es/incibe-cert/publicaciones/guias-y-estudios/estudios/estudio-analisis-grandoreiro", license: "INCIBE-CERT (publicación pública gratuita)", desc: "Análisis paso a paso del troyano bancario Grandoreiro: infección, evasión, IOCs y reglas YARA." },
  { id: 63, title: "Estudio del análisis de LockBit", author: "INCIBE-CERT", cat: "Malware", level: "i", format: "pdf", url: "https://www.incibe.es/incibe-cert/publicaciones/guias-y-estudios/estudios/estudio-analisis-lockbit", license: "INCIBE-CERT (publicación pública gratuita)", desc: "Análisis estático y dinámico del ransomware LockBit 3.0 en entorno controlado, con reglas de detección." },
  { id: 64, title: "Ingeniería inversa para principiantes (Reverse Engineering for Beginners)", author: "Dennis Yurichev", cat: "Malware", level: "i", format: "pdf", url: "https://yurichev.com/tmp/RE4B-ES.pdf", license: "Creative Commons BY-NC-ND 3.0", desc: "Libro gratuito de ~1000 paginas sobre ingenieria inversa de codigo x86/x64, ARM y MIPS generado por compiladores C/C++. Base esencial para el analisis de malware compilado." },
  { id: 65, title: "Reglas YARA y la deteccion de malware basado en firmas", author: "Ruben Ramiro (ciberseguridad.blog)", cat: "Malware", level: "i", format: "web", url: "https://ciberseguridad.blog/reglas-yara-y-la-deteccion-de-malware-basado-en-firmas/", license: "Acceso libre (articulo de blog)", desc: "Articulo que explica como escribir reglas YARA personalizadas y usar repositorios externos para la deteccion de malware mediante firmas. Orientado a operaciones de seguridad." },
  { id: 66, title: "Tutorial YARA - Guia Completa", author: "bgonpin (Pildoras)", cat: "Malware", level: "i", format: "web", url: "https://bgonpin.github.io/pildoras/yara.html", license: "Acceso libre (contenido educativo)", desc: "Tutorial completo en espanol sobre YARA: instalacion, sintaxis de reglas, strings, condiciones, metadatos y tecnicas avanzadas para detectar y clasificar familias de malware por patrones." },
  { id: 67, title: "Análisis de características estáticas de ejecutables para la clasificación de malware (TFM)", author: "Richard Rivera Guevara - Universidad Politécnica de Madrid", cat: "Malware", level: "a", format: "pdf", url: "https://oa.upm.es/34343/", license: "CC BY-NC-ND", desc: "Tesis de máster sobre clasificación de malware a partir de características estáticas de ficheros PE, empleando técnicas como Imphash y Pehash para agrupar familias." },
  { id: 68, title: "Clasificación de malware Linux ARM por funcionalidad con aprendizaje automático (TFM)", author: "José Antonio Quevedo Muñoz - Universidad Politécnica de Madrid", cat: "Malware", level: "a", format: "pdf", url: "https://oa.upm.es/64465/", license: "CC BY-NC-ND", desc: "Tesis de máster que aplica aprendizaje automático supervisado y análisis estático/dinámico para clasificar por funcionalidad ejecutables maliciosos de arquitectura Linux ARM." },
  { id: 69, title: "Detección de malware de Linux con ML sobre datos de análisis estático", author: "Jose A. Quevedo Muñoz (UPM)", cat: "Malware", level: "a", format: "pdf", url: "https://oa.upm.es/51846/", license: "TFG open-access UPM (CC BY-NC-ND)", desc: "Aplicación de aprendizaje automático supervisado sobre features de análisis estático para clasificar goodware vs malware." },
  { id: 70, title: "Detección de malware mediante aprendizaje profundo (TFG)", author: "Gloria Zufiaurre Soto - UPV/EHU", cat: "Malware", level: "a", format: "pdf", url: "https://addi.ehu.es/handle/10810/36853", license: "CC BY-NC-ND 3.0", desc: "Trabajo Fin de Grado que construye clasificadores con machine learning tradicional y deep learning para distinguir aplicaciones móviles legítimas de malware." },
  { id: 71, title: "Estudio del analisis de malware en SCI: BlackEnergy", author: "INCIBE-CERT", cat: "Malware", level: "a", format: "pdf", url: "https://www.incibe.es/sites/default/files/2024-01/INCIBE-CERT_ESTUDIO_ANALISIS_SCI_BLACKENERGY_2024_v1.0.pdf", license: "INCIBE (uso publico/educativo)", desc: "Estudio que repasa la evolucion del malware BlackEnergy, sus vectores de ataque y los metodos de analisis estatico, dinamico e ingenieria inversa empleados para investigarlo." },
  { id: 72, title: "Estudio del análisis de malware en SCI: BlackEnergy", author: "INCIBE-CERT", cat: "Malware", level: "a", format: "pdf", url: "https://www.incibe.es/incibe-cert/publicaciones/guias-y-estudios/estudios/estudio-analisis-malware-sci-blackenergy", license: "INCIBE-CERT (publicación pública gratuita)", desc: "Estudio técnico de BlackEnergy contra sistemas de control industrial: metodología, herramientas, IOCs y reglas YARA." },
  { id: 73, title: "Reversing y análisis de un malware (TFG)", author: "Cristóbal Saraiba Torres - Universidad Complutense de Madrid", cat: "Malware", level: "a", format: "pdf", url: "https://docta.ucm.es/entities/publication/274ceb20-6fd0-488a-a6b6-b9607bc9cd26", license: "Acceso abierto (Docta Complutense UCM)", desc: "Trabajo Fin de Grado de ingeniería de software dedicado a la ingeniería inversa de una muestra de malware: metodología y herramientas de análisis de un binario malicioso real." },
  { id: 74, title: "Sistema de detección y clasificación de malware con machine learning (TFM)", author: "Alberto Domínguez Mellado - Universidad de Cádiz", cat: "Malware", level: "a", format: "pdf", url: "https://rodin.uca.es/handle/10498/37446", license: "CC BY-NC-ND 4.0", desc: "Tesis de máster que diseña un sistema de detección y clasificación de malware combinando algoritmos de machine learning y fuentes de datos diversas." },
  { id: 75, title: "Técnicas de evasión de antivirus y EDR (TFG)", author: "Andrés Jesús Moreno - Universidad Politécnica de Madrid", cat: "Malware", level: "a", format: "pdf", url: "https://oa.upm.es/75850/", license: "CC BY-NC-ND (Archivo Digital UPM)", desc: "Analiza técnicas que usan los desarrolladores de malware para evadir antivirus y EDR: ofuscación de código, anti-debug y métodos de evasión de análisis estático y dinámico." },
  // ── Forense ──
  { id: 76, title: "Análisis forense de la huella digital de un usuario", author: "Vicente Sánchez Cervera (UPV)", cat: "Forense", level: "i", format: "pdf", url: "https://riunet.upv.es/server/api/core/bitstreams/7d29a71c-afb7-4ac2-9af8-3a1ca59a4ac5/content", license: "TFG open-access RiuNet (UPV)", desc: "Cómo analizar forensemente las trazas y la actividad de un usuario en un sistema, con Autopsy y técnicas de preservación (121 págs)." },
  { id: 77, title: "Análisis Forense del Sistema Android (TFG)", author: "Universidad de Zaragoza (Zaguan)", cat: "Forense", level: "i", format: "pdf", url: "https://zaguan.unizar.es/record/99044/files/TAZ-TFG-2016-4034.pdf", license: "TFG open-access Zaguan (UNIZAR)", desc: "Análisis forense de dispositivos Android con Autopsy 4.1.1 sobre Kali Linux: adquisición y análisis del sistema de archivos." },
  { id: 78, title: "Analisis forense en Sistemas de Control Industrial (articulo)", author: "INCIBE-CERT", cat: "Forense", level: "i", format: "web", url: "https://www.incibe.es/incibe-cert/blog/analisis-forense-sistemas-control-industrial", license: "INCIBE (uso publico/educativo)", desc: "Articulo introductorio sobre la investigacion forense de incidentes en sistemas de control industrial: preguntas clave de la investigacion y metodologia de respuesta." },
  { id: 79, title: "El tratamiento de la evidencia digital: guía de adquisición", author: "Paúl Ochoa Arévalo (Dialnet)", cat: "Forense", level: "i", format: "pdf", url: "https://dialnet.unirioja.es/descarga/articulo/6745358.pdf", license: "Artículo open-access (Dialnet)", desc: "Marcos de buenas prácticas para el tratamiento de la evidencia digital: identificación, recolección y preservación (cadena de custodia)." },
  { id: 80, title: "Guía de toma de evidencias en entornos Windows", author: "INCIBE / INCIBE-CERT", cat: "Forense", level: "i", format: "pdf", url: "https://www.incibe.es/sites/default/files/contenidos/guias/doc/incibe_toma_evidencias_analisis_forense.pdf", license: "INCIBE (CC, descarga libre)", desc: "Proceso de adquisición de evidencias digitales en Windows: fases del análisis forense, metodología reproducible y recolección de artefactos." },
  { id: 81, title: "RFC 3227 - Directrices para la recopilacion de evidencias y su almacenamiento", author: "Asier Martinez (INCIBE-CERT)", cat: "Forense", level: "i", format: "web", url: "https://www.incibe.es/incibe-cert/blog/rfc3227", license: "INCIBE (uso publico/educativo)", desc: "Articulo que explica el marco de referencia RFC 3227 para el analisis forense: recopilacion de evidencias por orden de volatilidad y cadena de custodia transparente y reproducible." },
  { id: 82, title: "Analisis de firmware en dispositivos industriales (Estudio)", author: "INCIBE-CERT", cat: "Forense", level: "a", format: "pdf", url: "https://www.incibe.es/sites/default/files/2023-08/INCIBE-CERT_GUIA_ANALISIS_DE_FIRMWARE_SCI_2023_v1.0.pdf", license: "INCIBE (uso publico/educativo)", desc: "Estudio de 49 paginas sobre el analisis de firmware en dispositivos industriales: extraccion, inspeccion y deteccion de vulnerabilidades desde la base del dispositivo." },
  { id: 83, title: "Flipper Zero en el análisis forense digital (TFG)", author: "Carlos D. Estévez Sanz (UPM)", cat: "Forense", level: "a", format: "pdf", url: "https://oa.upm.es/90413/1/TFG_CARLOSDAVID_ESTEVEZ_SANZ.pdf", license: "TFG open-access UPM (CC BY-NC-ND)", desc: "Viabilidad del Flipper Zero como herramienta de apoyo forense, con foco en NFC y análisis del entorno." },
  { id: 84, title: "Apuntes de Ciberseguridad — Análisis Forense (RAM con Volatility)", author: "Mariano Sánchez Martín — IES San Clemente", cat: "Forense", level: "all", format: "web", url: "https://manuais.pages.iessanclemente.net/apuntes/ciberseguridad/forense/", license: "Material educativo abierto (CC BY-NC-SA)", desc: "Curso completo de forense: adquisición en vivo Windows/Linux, memoria RAM con Volatility, artefactos, Android, cloud e IoT (17 módulos)." },
  // ── Blue Team ──
  { id: 85, title: "¿Qué son y para qué sirven los SIEM, IDS e IPS?", author: "INCIBE", cat: "Blue Team", level: "b", format: "web", url: "https://www.incibe.es/empresas/blog/son-y-sirven-los-siem-ids-e-ips", license: "Contenido divulgativo gratuito de INCIBE", desc: "Diferencias entre SIEM, IDS e IPS, ventajas/desventajas y por qué implementarlos." },
  { id: 86, title: "Gestión de logs — Políticas de seguridad para la pyme", author: "INCIBE", cat: "Blue Team", level: "b", format: "pdf", url: "https://www.incibe.es/sites/default/files/contenidos/politicas/documentos/gestion-logs.pdf", license: "Publicación oficial gratuita de INCIBE", desc: "Guía práctica de gestión y monitorización de logs para detectar intrusiones y anomalías: qué registrar, retención y detección." },
  { id: 87, title: "Análisis de redes y vulnerabilidades (TFG)", author: "Javier Ríos Serrano - Universidad Politécnica de Madrid", cat: "Blue Team", level: "i", format: "pdf", url: "https://oa.upm.es/80516/", license: "CC BY-NC-ND", desc: "Trabajo Fin de Grado sobre análisis de redes en ciberseguridad: técnicas pasivas y activas, protocolos TCP/UDP/ARP/ICMP, vulnerabilidades CVE y sistemas de detección de intrusos (IDS/IPS)." },
  { id: 88, title: "Análisis de tráfico con Wireshark", author: "INTECO-CERT (hoy INCIBE-CERT)", cat: "Blue Team", level: "i", format: "pdf", url: "https://concienciat.gva.es/wp-content/uploads/2018/03/infor_cert_inf_seguridad_analisis_trafico_wireshark.pdf", license: "CC BY-NC-SA 3.0 España", desc: "Guía oficial del CERT español para auditar y monitorizar la red con Wireshark: captura de tráfico, análisis de protocolos y detección de actividad anómala." },
  { id: 89, title: "Buenas practicas: lecciones aprendidas en la identificacion de amenazas y respuesta a intrusiones", author: "INCIBE-CERT", cat: "Blue Team", level: "i", format: "web", url: "https://www.incibe.es/incibe-cert/blog/buenas-practicas-lecciones-aprendidas-en-la-identificacion-de-amenazas-y-respuesta", license: "INCIBE (uso publico/educativo)", desc: "Recomendaciones practicas de deteccion y respuesta a intrusiones: segmentacion de red, herramientas IDS/IPS, lecciones de casos como APT y WannaCry." },
  { id: 90, title: "Configuración de Microsoft Sentinel (ruta SC-200)", author: "Microsoft Learn", cat: "Blue Team", level: "i", format: "web", url: "https://learn.microsoft.com/es-es/training/paths/sc-200-configure-azure-sentinel-environment/", license: "Formación oficial gratuita de Microsoft Learn en español", desc: "Ruta de 6 módulos sobre Microsoft Sentinel (SIEM cloud): workspace, KQL, watchlists, threat intelligence e integración con Defender XDR." },
  { id: 91, title: "Diseño de paneles de control en Wazuh para supervisión de redes", author: "Ander Chueca Rodríguez (UniRioja)", cat: "Blue Team", level: "i", format: "pdf", url: "https://investigacion.unirioja.es/documentos/677ce83e6640ab12237120e4/f/677ce83e6640ab12237120e3.pdf", license: "CC BY-NC-ND 3.0 — repositorio UniRioja", desc: "Creación de dashboards de Wazuh para supervisar redes, detectar amenazas y visualizar eventos de seguridad (orientado a SOC)." },
  { id: 92, title: "Guía Nacional de Notificación y Gestión de Ciberincidentes", author: "INCIBE-CERT / CCN-CERT", cat: "Blue Team", level: "i", format: "pdf", url: "https://www.incibe.es/sites/default/files/contenidos/guias/doc/guia_nacional_notificacion_gestion_ciberincidentes.pdf", license: "Guía oficial gratuita de organismos públicos españoles", desc: "Taxonomía/clasificación de ciberincidentes y marco nacional de notificación y gestión (55 páginas)." },
  { id: 93, title: "Guías de ciberseguridad para empresas", author: "INCIBE", cat: "Blue Team", level: "i", format: "pdf", url: "https://www.incibe.es/empresas/guias", license: "INCIBE (uso libre)", desc: "Colección de guías prácticas en PDF: políticas, gestión de incidentes, protección de datos, etc." },
  { id: 94, title: "IDS/IPS en el curso de especialista en ciberseguridad (apuntes)", author: "Raúl Profesor (Curso Especialista en Ciberseguridad)", cat: "Blue Team", level: "i", format: "web", url: "https://raul-profesor.github.io/Curso-especialista-ciberseguridad/segdef/idps/", license: "Material docente público (MkDocs)", desc: "Módulo de seguridad defensiva centrado en Suricata como IDS/IPS: metodologías de detección, creación de reglas personalizadas y validación frente a tráfico de prueba." },
  { id: 95, title: "Implementación de un SIEM Open Source con Wazuh (ISO 27001 y NIS2)", author: "José A. Peñaranda Fajardo (UPV)", cat: "Blue Team", level: "i", format: "pdf", url: "https://riunet.upv.es/entities/publication/6700b61d-017d-4e3f-a2c6-74abc88dc2c5", license: "TFG open-access RiuNet (UPV)", desc: "Despliegue de un SIEM con Wazuh y Elastic Stack para monitorización, análisis de logs y cumplimiento normativo, con laboratorio paso a paso." },
  { id: 96, title: "Monitorización mediante IDS e IPS (apuntes SAD)", author: "Raúl Profesor (apuntes Seguridad y Alta Disponibilidad)", cat: "Blue Team", level: "i", format: "web", url: "https://raul-profesor.github.io/SAD/idps/", license: "Material docente público (MkDocs)", desc: "Apuntes de ciclo formativo sobre IDS/IPS: NIDS vs HIDS, detección por firmas/anomalías/protocolo, comparativa Suricata vs Snort y prácticas de instalación en Debian y Rocky Linux." },
  { id: 97, title: "Procedimiento de gestión de ciberincidentes para el sector privado", author: "INCIBE-CERT", cat: "Blue Team", level: "i", format: "pdf", url: "https://www.incibe.es/sites/default/files/contenidos/guias/doc/incibe-cert_gestion_ciberincidentes_sector_privado.pdf", license: "Guía oficial gratuita de INCIBE-CERT", desc: "Procedimiento completo de respuesta a incidentes: detección, clasificación, contención, erradicación y recuperación." },
  { id: 98, title: "Diseno y Configuracion de IPS, IDS y SIEM en Sistemas de Control Industrial", author: "INCIBE-CERT / CERTSI", cat: "Blue Team", level: "a", format: "pdf", url: "https://www.incibe.es/sites/default/files/contenidos/guias/doc/certsi_diseno_configuracion_ips_ids_siem_en_sci.pdf", license: "INCIBE (uso publico/educativo)", desc: "Estudio tecnico sobre sistemas de deteccion y prevencion de intrusiones (IDS/IPS) y recoleccion de eventos (SIEM), con funcionamiento de soluciones y recomendaciones de seguridad." },
  { id: 99, title: "Guía de análisis forense en Sistemas de Control Industrial (SCI)", author: "INCIBE", cat: "Blue Team", level: "a", format: "pdf", url: "https://www.incibe.es/sites/default/files/contenidos/guias/doc/incibe_guia_analisis_forense_sci.pdf", license: "Guía oficial gratuita de INCIBE", desc: "Metodología de análisis forense en entornos industriales con IDS/SIEM y sondas para recolección de evidencias." },
  { id: 100, title: "Plataforma de monitorización de seguridad informática (PFG, Suricata + Zeek + ELK)", author: "Víctor Paredes Gallego - Universidad Politécnica de Madrid", cat: "Blue Team", level: "a", format: "pdf", url: "https://oa.upm.es/68185/", license: "CC BY-NC-ND", desc: "Proyecto Fin de Grado que despliega una plataforma blue team con segmentación por VLANs, IDS/IPS (Suricata), NDR (Zeek), Sysmon y SIEM con la pila ELK (Elasticsearch/Logstash/Kibana)." },
  { id: 101, title: "Contenido SIEM de INCIBE-CERT (hub de articulos)", author: "INCIBE-CERT", cat: "Blue Team", level: "all", format: "web", url: "https://www.incibe.es/incibe-cert/tags/siem", license: "INCIBE (uso publico/educativo)", desc: "Indice tematico que agrupa los articulos y estudios de INCIBE-CERT sobre SIEM, monitorizacion y correlacion de eventos para equipos de defensa (Blue Team)." },
  { id: 102, title: "Guía completa del Centro de Operaciones de Seguridad (SOC)", author: "Elastic", cat: "Blue Team", level: "all", format: "web", url: "https://www.elastic.co/es/what-is/security-operations-center", license: "Documentación oficial gratuita de Elastic en español", desc: "Qué es un SOC, sus funciones (monitorización, threat hunting, IR), roles del equipo y tecnologías clave (SIEM, SOAR, XDR)." },
  // ── Cloud ──
  { id: 103, title: "Cloud computing: una guía de aproximación para el empresario", author: "INCIBE", cat: "Cloud", level: "b", format: "pdf", url: "https://www.incibe.es/empresas/guias/cloud-computing-guia-aproximacion-el-empresario", license: "Guía oficial INCIBE (acceso gratuito)", desc: "Guía introductoria al cloud computing: tipos de servicios, riesgos de seguridad y privacidad y recomendaciones de adopción." },
  { id: 104, title: "Introduccion a la seguridad de Azure", author: "Microsoft", cat: "Cloud", level: "b", format: "web", url: "https://learn.microsoft.com/es-es/azure/security/fundamentals/overview", license: "Documentacion oficial Microsoft Learn (uso publico)", desc: "Documento conceptual oficial que presenta los servicios de seguridad de Azure y como protegen identidades, redes, datos y cargas de trabajo en la nube." },
  { id: 105, title: "TemáTICas: Seguridad en la nube", author: "INCIBE", cat: "Cloud", level: "b", format: "web", url: "https://www.incibe.es/empresas/blog/tematicas-seguridad-nube", license: "Contenido oficial de INCIBE (gratuito)", desc: "Introducción a la seguridad en la nube: responsabilidad compartida, amenazas comunes y recomendaciones prácticas." },
  { id: 106, title: "Pilar de seguridad - AWS Well-Architected Framework", author: "Amazon Web Services", cat: "Cloud", level: "i", format: "pdf", url: "https://docs.aws.amazon.com/es_es/wellarchitected/latest/security-pillar/wellarchitected-security-pillar.pdf", license: "Documentacion oficial AWS (uso publico)", desc: "Guia oficial del pilar de seguridad de AWS: identidad y acceso, privilegio minimo, deteccion, proteccion de datos y respuesta a incidentes con buenas practicas (SEC01-SEC11)." },
  { id: 107, title: "Prácticas recomendadas de seguridad en IAM de AWS", author: "Amazon Web Services", cat: "Cloud", level: "i", format: "web", url: "https://docs.aws.amazon.com/es_es/IAM/latest/UserGuide/best-practices.html", license: "Documentación oficial de AWS en español", desc: "13 prácticas recomendadas de seguridad para IAM: federación, credenciales temporales, MFA, privilegio mínimo y Access Analyzer." },
  { id: 108, title: "Prácticas recomendadas para el usuario raíz de AWS", author: "Amazon Web Services", cat: "Cloud", level: "i", format: "web", url: "https://docs.aws.amazon.com/es_es/IAM/latest/UserGuide/root-user-best-practices.html", license: "Documentación oficial de AWS en español", desc: "Cómo proteger el usuario raíz: contraseñas robustas, MFA, sin claves de acceso, AWS Organizations y monitoreo con GuardDuty." },
  { id: 109, title: "Seguridad de Azure para aplicaciones nativas en la nube (.NET)", author: "Microsoft", cat: "Cloud", level: "i", format: "web", url: "https://learn.microsoft.com/es-es/dotnet/architecture/cloud-native/azure-security", license: "Documentacion oficial Microsoft Learn (uso publico)", desc: "Capitulo del ebook gratuito de arquitectura cloud-native: modelado de amenazas, privilegio minimo, RBAC, Key Vault, secretos de Kubernetes y cifrado en transito y en reposo." },
  { id: 110, title: "Seguridad en Amazon Elastic Container Service (ECS)", author: "Amazon Web Services", cat: "Cloud", level: "i", format: "web", url: "https://docs.aws.amazon.com/es_es/AmazonECS/latest/developerguide/security.html", license: "Documentacion oficial AWS (uso publico)", desc: "Documentacion oficial sobre seguridad de contenedores en Amazon ECS: modelo de responsabilidad compartida, IAM, registro de eventos, conformidad y FIPS." },
  { id: 111, title: "Arquitectura DevSecOps para pruebas de seguridad en contenedores", author: "Tristán Vaquero Povedano (UPM)", cat: "Cloud", level: "a", format: "pdf", url: "https://oa.upm.es/75213/", license: "TFG open-access UPM (CC BY-NC-ND)", desc: "Diseño de un pipeline DevSecOps que automatiza el escaneo de imágenes y el análisis de vulnerabilidades en aplicaciones Docker/Kubernetes." },
  { id: 112, title: "Introducción al Microsoft Cloud Security Benchmark (MCSB)", author: "Microsoft", cat: "Cloud", level: "a", format: "web", url: "https://learn.microsoft.com/es-es/security/benchmark/azure/introduction", license: "Microsoft Learn en español", desc: "Marco de controles para proteger cargas de trabajo en Azure y multinube (AWS, GCP), alineado con CIS, NIST y PCI-DSS." },
  { id: 113, title: "Practicas recomendadas para endurecer la seguridad del cluster (GKE)", author: "Google Cloud", cat: "Cloud", level: "a", format: "web", url: "https://docs.cloud.google.com/kubernetes-engine/docs/how-to/hardening-your-cluster?hl=es-419", license: "Documentacion oficial Google Cloud (uso publico)", desc: "Documentacion oficial de hardening de clusteres GKE: seguridad de red, configuracion de nodos, Workload Identity, RBAC, aislamiento de cargas y proteccion de datos." },
  { id: 114, title: "Uso seguro de cuentas de servicio en Google Cloud IAM", author: "Google Cloud", cat: "Cloud", level: "a", format: "web", url: "https://docs.cloud.google.com/iam/docs/best-practices-service-accounts?hl=es-419", license: "Documentación oficial de Google Cloud en español", desc: "Gestión segura de cuentas de servicio: federación de identidades, privilegio mínimo y auditoría." },
  { id: 115, title: "Centro de practicas recomendadas de seguridad de Google Cloud", author: "Google Cloud", cat: "Cloud", level: "all", format: "web", url: "https://cloud.google.com/security/best-practices?hl=es", license: "Documentacion oficial Google Cloud (uso publico)", desc: "Hub oficial de guias de seguridad de Google Cloud: estructura organizativa, autenticacion y autorizacion, jerarquia de recursos, redes, registros y controles de deteccion." },
  // ── Especializado ──
  { id: 116, title: "Guía básica teórica y práctica de uso de herramientas OSINT (presentación)", author: "osintux.org", cat: "Especializado", level: "b", format: "pdf", url: "https://www.osintux.org/wp-content/uploads/2021/05/Presentacion-OSINT-IES-Celia-Vinas.pdf", license: "Material divulgativo público en español publicado en osintux.org", desc: "Introducción a la inteligencia en fuentes abiertas (OSINT): conceptos, metodología y herramientas para la recopilación y análisis de información pública." },
  { id: 117, title: "Análisis de vulnerabilidades en aplicaciones Android", author: "Juan M. R. / Jaymon Security", cat: "Especializado", level: "i", format: "web", url: "https://jaymonsecurity.es/analisis-vulnerabilidades-app-android/", license: "Artículo público y gratuito de Jaymon Security (empresa española registrada en INCIBE)", desc: "Guía práctica de análisis estático de apps Android: laboratorio, ingeniería inversa y explotación de fallos comunes (logging y almacenamiento inseguro) con la app DIVA." },
  { id: 118, title: "OWASP Top 10 de riesgos en aplicaciones móviles (2024)", author: "Tarlogic Security", cat: "Especializado", level: "i", format: "web", url: "https://www.tarlogic.com/es/blog/owasp-top-10-riesgos-aplicaciones-moviles/", license: "Artículo público y gratuito del blog de Tarlogic Security (empresa española)", desc: "Análisis del OWASP Mobile Top 10 2024: credenciales, cadena de suministro, autenticación débil, comunicación insegura, criptografía débil y más. Mobile security." },
  { id: 119, title: "Análisis de OSINT aplicado a la detección de amenazas", author: "SEDICI - Universidad Nacional de La Plata", cat: "Especializado", level: "a", format: "pdf", url: "https://sedici.unlp.edu.ar/bitstream/handle/10915/129027/Documento_completo.pdf-PDFA.pdf?sequence=1&isAllowed=y", license: "Trabajo de acceso abierto del repositorio SEDICI (Universidad Nacional de La Plata)", desc: "Trabajo académico open-access sobre la aplicación de técnicas OSINT a la detección de amenazas y la inteligencia de ciberseguridad." },
  { id: 120, title: "Curso OSINT y Técnicas de Informática Forense (Cátedra de Ciberseguridad INCIBE-UEx-CUMe)", author: "Centro Universitario de Mérida (Universidad de Extremadura) e INCIBE", cat: "Especializado", level: "a", format: "web", url: "https://cume.unex.es/2025/09/15/el-centro-universitario-de-merida-inaugura-el-curso-osint-y-tecnicas-de-informatica-forense-para-la-policia-nacional-dentro-de-la-catedra-de-ciberseguridad-incibe-uex-cume/", license: "Información pública de la Cátedra de Ciberseguridad cofinanciada por INCIBE y la UEx", desc: "Programa universitario avanzado sobre OSINT y forense: investigación en redes sociales, correo, criptomonedas, blockchain y dark web. Referencia de temario especializado." },
  { id: 121, title: "Desarrollo de una plataforma de criptoanálisis por consumo (TFG, vertiente forense/avanzada)", author: "Universitat Politècnica de Catalunya (UPCommons)", cat: "Especializado", level: "a", format: "pdf", url: "https://upcommons.upc.edu/server/api/core/bitstreams/e285344f-6a19-499a-bee6-bc5449742337/content", license: "TFG open-access en UPCommons, licencia CC BY-NC-SA 3.0 España", desc: "Acceso alternativo al TFG de criptoanálisis por canal lateral; relevante como caso especializado de hardware hacking aplicado a la extracción de claves." },
  // ── Programación ──
  { id: 122, title: "Aprende Python", author: "Sergio Delgado Quintero (sdelquin)", cat: "Programación", level: "b", format: "web", url: "https://aprendepython.es/", license: "CC BY 4.0", desc: "Curso completo de Python en español con fundamentos del lenguaje, biblioteca estándar y paquetes de terceros." },
  { id: 123, title: "El Manual de Python", author: "Flavio Copes (trad. Cristian Sulbaran) - freeCodeCamp", cat: "Programación", level: "b", format: "web", url: "https://www.freecodecamp.org/espanol/news/el-manual-de-python/", license: "Open-access (freeCodeCamp, con atribución)", desc: "Manual conciso del núcleo de Python en español: variables, control de flujo, funciones, POO y decoradores." },
  { id: 124, title: "El Tutorial de Python (oficial)", author: "Python Software Foundation", cat: "Programación", level: "b", format: "web", url: "https://docs.python.org/es/3/tutorial/", license: "PSF License", desc: "Tutorial oficial de Python traducido al español. La documentación completa se puede descargar en PDF." },
  { id: 125, title: "Elementos básicos de JavaScript (MDN Web Docs en español)", author: "Mozilla / comunidad MDN", cat: "Programación", level: "b", format: "web", url: "https://developer.mozilla.org/es/docs/Learn_web_development/Core/Scripting", license: "CC BY-SA 2.5 (docs oficiales MDN)", desc: "Módulo de aprendizaje oficial de JavaScript: condicionales, bucles, funciones, valores de retorno y eventos." },
  { id: 126, title: "Introducción a la programación con Python", author: "Andrés Marzal e Isabel Gracia (Universitat Jaume I)", cat: "Programación", level: "b", format: "pdf", url: "http://persoal.citius.usc.es/eva.cernadas/informaticaparacientificos/material/libros/ippython.pdf", license: "Material universitario de acceso abierto (OCW UJI)", desc: "Libro universitario que enseña programación desde cero usando Python, con ejercicios y estructuras de datos." },
  { id: 127, title: "Python para todos", author: "Raúl González Duque", cat: "Programación", level: "b", format: "web", url: "https://mundogeek.net/tutorial-python/", license: "Libre (distribución gratuita)", desc: "Clásico libro introductorio de Python en español, de libre distribución." },
  { id: 128, title: "Documentación de Django (es)", author: "Django Software Foundation", cat: "Programación", level: "i", format: "web", url: "https://docs.djangoproject.com/es/stable/", license: "BSD (docs)", desc: "Documentación oficial del framework Django, parcialmente traducida al español." },
  { id: 129, title: "Documentación oficial de Python en español", author: "Python Software Foundation / python-docs-es", cat: "Programación", level: "all", format: "web", url: "https://docs.python.org/es/3/", license: "Docs oficiales (PSF License)", desc: "Página principal de la documentación oficial de Python: tutorial, referencia del lenguaje y de la biblioteca." },
  { id: 130, title: "Libros de programación gratis en español (librosgratis.dev)", author: "midudev y comunidad", cat: "Programación", level: "all", format: "web", url: "https://github.com/midudev/libros-programacion-gratis", license: "Lista open-source / recursos legales enlazados", desc: "Biblioteca viva de más de 100 libros y guías gratuitos de programación en español organizados por categorías." },
  { id: 131, title: "Lista de libros de programación gratis en español (free-programming-books)", author: "EbookFoundation", cat: "Programación", level: "all", format: "web", url: "https://github.com/EbookFoundation/free-programming-books/blob/main/books/free-programming-books-es.md", license: "CC BY 4.0 (lista) / recursos legales enlazados", desc: "Índice curado de libros y recursos gratuitos de programación en español (Python, JS, C, SQL, Go, Git y más)." },
  { id: 132, title: "MDN Web Docs (JavaScript y Web)", author: "Mozilla", cat: "Programación", level: "all", format: "web", url: "https://developer.mozilla.org/es/docs/Web/JavaScript", license: "CC BY-SA 2.5", desc: "Referencia abierta de JavaScript, HTML y CSS en español, mantenida por Mozilla." },
  { id: 133, title: "Pro Git (2ª edición)", author: "Scott Chacon & Ben Straub", cat: "Programación", level: "all", format: "pdf", url: "https://git-scm.com/book/es/v2", license: "CC BY-NC-SA 3.0", desc: "El libro de referencia de Git, completo y en español. Descargable en PDF desde la web oficial." },
  // ── Exploit Dev Avanzado ──
  { id: 134, title: "Introducción a la Ciberseguridad (materiales de cátedra)", author: "Facultad de Informática, Universidad Nacional de La Plata (UNLP)", cat: "Exploit Dev Avanzado", level: "b", format: "pdf", url: "https://www.info.unlp.edu.ar/wp-content/uploads/2018/05/Introduccion-a-la-ciberseguridad-2018.pdf", license: "Apuntes universitarios públicos de la Facultad de Informática de la UNLP", desc: "Material de cátedra que introduce competencias de seguridad tipo CTF: explotación binaria, ingeniería inversa y análisis forense. Punto de partida hacia exploiting." },
  { id: 135, title: "Guía de escritura de exploits: Buffer Overflow", author: "Teresa Alberto / Fundación Sadosky (STIC)", cat: "Exploit Dev Avanzado", level: "i", format: "web", url: "https://fundacion-sadosky.github.io/guia-escritura-exploits/buffer-overflow/", license: "CC BY-NC-SA — guía pública de la Fundación Sadosky en GitHub Pages", desc: "Guía progresiva en cuatro niveles sobre explotación de buffer overflow con teoría y ejercicios prácticos. Base imprescindible para iniciarse en el desarrollo de exploits." },
  { id: 136, title: "Técnicas de hacking ético en ciberseguridad", author: "Universidad de La Laguna (TFG, Ingeniería Informática)", cat: "Exploit Dev Avanzado", level: "i", format: "pdf", url: "https://riull.ull.es/xmlui/bitstream/handle/915/46802/Tecnicas%20de%20hacking%20etico%20enciberseguridad.pdf?sequence=1&isAllowed=y", license: "TFG open-access del repositorio institucional RIULL (Universidad de La Laguna)", desc: "Trabajo Fin de Grado que recorre metodologías de hacking ético y explotación de vulnerabilidades, útil como marco práctico para el desarrollo de exploits." },
  { id: 137, title: "Guía de escritura de exploits: Ataque return-to-libc (ROP)", author: "Fundación Sadosky (STIC)", cat: "Exploit Dev Avanzado", level: "a", format: "web", url: "https://fundacion-sadosky.github.io/guia-escritura-exploits/esoteric/6-ret2libc.html", license: "CC BY-NC-SA — guía pública de la Fundación Sadosky en GitHub Pages", desc: "Técnica avanzada return-to-libc/ROP para sortear protecciones W^X redirigiendo el retorno a funciones de libc como system(). Incluye construcción del layout de pila." },
  { id: 138, title: "Prevención de ataques ROP en ejecutables mediante instrumentación dinámica", author: "Universidad de Zaragoza (PFC/TFG)", cat: "Exploit Dev Avanzado", level: "a", format: "pdf", url: "https://webdiis.unizar.es/~ricardo/files/PFCs/PrevencionAtaquesROPDBI.pdf", license: "Proyecto fin de carrera open-access alojado en el servidor de la Universidad de Zaragoza", desc: "Estudio en profundidad de los ataques Return Oriented Programming (gadgets, encadenamiento, evasión de W^X/ASLR/stack cookies) y técnicas de mitigación mediante DBI." },
  { id: 139, title: "Programación, Reversing y Explotación avanzada de Buffer Overflow (BoF) con Shellcode manual", author: "Juan M. R. / Jaymon Security", cat: "Exploit Dev Avanzado", level: "a", format: "web", url: "https://jaymonsecurity.es/programacion-reversing-buffer-overflow-cliente-servidor-explotacion-shellcode-manual/", license: "Artículo público y gratuito de Jaymon Security (empresa española registrada en INCIBE)", desc: "Tutorial técnico end-to-end: crear un binario vulnerable, analizarlo con x32dbg, hallar badchars, eludir ASLR/DEP y construir shellcode manual para una reverse shell." },
  // ── Cripto Avanzada ──
  { id: 140, title: "¿Qué es una Zero Knowledge Proof o Prueba de Conocimiento Cero?", author: "Gabriela González / Criptopedia de CriptoNoticias", cat: "Cripto Avanzada", level: "i", format: "web", url: "https://www.criptonoticias.com/criptopedia/zero-knowledge-proof-o-prueba-de-conocimiento-cero/", license: "Contenido educativo público y gratuito de la Criptopedia de CriptoNoticias", desc: "Explicación detallada de las pruebas de conocimiento cero: propiedades (completitud, solidez, ZK), variantes zk-SNARK/zk-STARK/Bulletproofs y aplicaciones en blockchain." },
  { id: 141, title: "Criptografía Post-Cuántica (artículo de congreso CACIC)", author: "Diego Córdoba, Miguel Méndez-Garabetti et al. / SEDICI - UNLP", cat: "Cripto Avanzada", level: "i", format: "pdf", url: "https://sedici.unlp.edu.ar/bitstream/handle/10915/62685/Documento_completo.pdf-PDFA.pdf?sequence=1", license: "Artículo de acceso abierto del repositorio SEDICI (Universidad Nacional de La Plata)", desc: "Paper académico open-access que repasa el estado de la criptografía post-cuántica y los retos que plantea la computación cuántica para los sistemas actuales." },
  { id: 142, title: "Introducción a la Criptografía Post-Cuántica", author: "Lucía Liu Wang / Universidad Politécnica de Madrid (TFG)", cat: "Cripto Avanzada", level: "i", format: "pdf", url: "https://oa.upm.es/90220/1/TFG_LUCIA_LIU_WANG.pdf", license: "TFG open-access del Archivo Digital UPM (oa.upm.es)", desc: "Trabajo Fin de Grado que introduce la criptografía resistente a computación cuántica: amenaza cuántica a RSA/ECC y familias de algoritmos post-cuánticos." },
  { id: 143, title: "Introducción a la Criptografía Post-Cuántica", author: "David De Santiago Lafuente / Universidad Complutense de Madrid (TFG)", cat: "Cripto Avanzada", level: "i", format: "pdf", url: "https://docta.ucm.es/bitstreams/f549dee0-f6a1-41f7-8ac5-105df19cb0e5/download", license: "TFG open-access del repositorio DOCTA Complutense (UCM)", desc: "Trabajo Fin de Grado de la UCM sobre fundamentos y algoritmos de la criptografía post-cuántica de cara a la migración frente a ordenadores cuánticos." },
  { id: 144, title: "Desarrollo de una plataforma de criptoanálisis basada en medidas de consumo sobre el algoritmo DES", author: "Claudia Barreiro Mont / Universitat Politècnica de Catalunya (TFG)", cat: "Cripto Avanzada", level: "a", format: "pdf", url: "https://upcommons.upc.edu/bitstreams/e285344f-6a19-499a-bee6-bc5449742337/download", license: "TFG open-access en UPCommons, licencia CC BY-NC-SA 3.0 España", desc: "Criptoanálisis por canal lateral (análisis diferencial de consumo) contra DES usando modelos de peso de Hamming y correlación. Cruce de criptoanálisis y hardware." },
  { id: 145, title: "Integración de tecnologías de Distribución Cuántica de Claves (QKD) en protocolos criptográficos clásicos", author: "Jaime Sáez de Buruaga Brouns / Universidad Politécnica de Madrid (TFM)", cat: "Cripto Avanzada", level: "a", format: "pdf", url: "https://oa.upm.es/71914/3/TFM_Jaime_Saez_de_Buruaga.pdf", license: "TFM open-access del Archivo Digital UPM (oa.upm.es)", desc: "Tesis de máster sobre integración de QKD en protocolos clásicos (TLS 1.3), combinando seguridad teórica de la información con criptografía práctica." },
  { id: 146, title: "Introducción a la Criptografía Homomórfica", author: "Universidad de La Laguna (TFG)", cat: "Cripto Avanzada", level: "a", format: "pdf", url: "https://riull.ull.es/xmlui/bitstream/handle/915/30351/Introduccion%20a%20la%20Criptografia%20Homomorfica.pdf?sequence=1&isAllowed=y", license: "TFG open-access del repositorio institucional RIULL (Universidad de La Laguna)", desc: "Cifrado homomórfico (total, parcial) y esquemas modernos como CKKS para evaluar circuitos sobre datos cifrados. Tema avanzado de criptografía aplicada a la privacidad." },
  // ── AI/ML Security ──
  { id: 147, title: "Ataques adversarios en el aprendizaje automático: causas y una posible solución", author: "Laura Salguero Hinojosa (Universidad Politécnica de Madrid)", cat: "AI/ML Security", level: "i", format: "pdf", url: "https://oa.upm.es/70307/1/TFG_Laura_Salguero.pdf", license: "Creative Commons Reconocimiento-NoComercial-SinObraDerivada (repositorio open-access UPM)", desc: "TFG que explica qué son los ejemplos adversarios contra redes neuronales, cómo se construyen (50.000 imágenes) y propone PCA como defensa. Introducción clara y aplicada al adversarial ML en español." },
  { id: 148, title: "Impacto de la inteligencia artificial en los ciberataques", author: "Aura Dolores Zambrano Rendón (Revista Sinapsis, ITSUP)", cat: "AI/ML Security", level: "i", format: "pdf", url: "https://dialnet.unirioja.es/descarga/articulo/9642443.pdf", license: "Acceso abierto (Dialnet, ISSN-e 1390-9770)", desc: "Artículo que analiza cómo la IA transforma tanto la defensa como la ofensiva en ciberseguridad, con foco en amenazas potenciadas por aprendizaje automático." },
  { id: 149, title: "La inteligencia artificial en la seguridad informática: una revisión literaria", author: "Ortega Tenezaca, Rodríguez Carmona, Macías Farias y Cevallos Illicachi", cat: "AI/ML Security", level: "i", format: "pdf", url: "https://dialnet.unirioja.es/descarga/articulo/10343583.pdf", license: "Acceso abierto (Dialnet, revista científica con licencia abierta)", desc: "Artículo de revisión que sintetiza la literatura sobre uso de ML para detección de amenazas y ataques evasivos. Útil como mapa del estado del arte en IA aplicada a seguridad." },
  { id: 150, title: "Desarrollo de un modelo de clasificación de malware Linux ARM según su funcionalidad usando aprendizaje automático", author: "José Antonio Quevedo Muñoz (Máster en Ciberseguridad, UPM)", cat: "AI/ML Security", level: "a", format: "pdf", url: "https://oa.upm.es/64465/1/TESIS_MASTER_JOSE_ANTONIO_QUEVEDO_MUNOZ_2020.pdf", license: "Creative Commons Reconocimiento-NoComercial-SinObraDerivada (repositorio open-access UPM)", desc: "TFM que aplica ML supervisado (análisis estático+dinámico) para clasificar ejecutables Linux ARM por funcionalidad. Caso real de ML aplicado a seguridad ofensiva/defensiva." },
  { id: 151, title: "Sistema de detección y clasificación de malware usando algoritmos de machine learning y fuentes de datos diversas", author: "Alberto Domínguez Mellado (Máster en Seguridad Informática, Universidad de Cádiz)", cat: "AI/ML Security", level: "a", format: "pdf", url: "https://rodin.uca.es/bitstream/handle/10498/37446/TFM_DominguezMellado_Alberto.pdf?sequence=1&isAllowed=y", license: "Creative Commons BY-NC-ND 4.0 (repositorio RODIN, Universidad de Cádiz)", desc: "TFM que compara LightGBM, XGBoost, SVM y redes neuronales para detección de malware. Buen recorrido por pipelines de ML en seguridad y evaluación de modelos." },
  { id: 152, title: "OWASP Top 10 2025 de riesgos y mitigaciones para LLMs y aplicaciones de IA Generativa", author: "OWASP GenAI Security Project", cat: "AI/ML Security", level: "all", format: "pdf", url: "https://genai.owasp.org/download/46116/?tmstv=1741814891", license: "OWASP / Creative Commons (proyecto comunitario de acceso libre)", desc: "Traducción oficial al español del Top 10 de riesgos de seguridad en LLMs: prompt injection, envenenamiento de datos, fuga de información, etc. Referencia esencial para MLSecOps y seguridad de LLM." },
  // ── Hardware & Low-Level ──
  { id: 153, title: "Seguridad en la instalación y uso de dispositivos IoT: guía de aproximación para el empresario", author: "INCIBE (Instituto Nacional de Ciberseguridad)", cat: "Hardware & Low-Level", level: "b", format: "pdf", url: "https://www.incibe.es/sites/default/files/contenidos/guias/doc/guia-de-seguridad-iot.pdf", license: "Guía pública y gratuita publicada por INCIBE (organismo público español)", desc: "Guía oficial sobre amenazas y vectores de ataque a dispositivos IoT (fallos de implementación, configuraciones por defecto, cifrado) y medidas de protección." },
  { id: 154, title: "Arranque de Sistemas Operativos: BIOS, UEFI y gestión de particiones", author: "D. R. Organvídez / Universidad de Sevilla", cat: "Hardware & Low-Level", level: "i", format: "pdf", url: "https://personal.us.es/drorganvidez/wp-content/uploads/2026/02/Arranque_de_Sistemas_Operativos_BIOS__UEFI_y_gestion_de_particiones.pdf", license: "Apuntes docentes públicos de personal académico de la Universidad de Sevilla", desc: "Apuntes universitarios sobre el proceso de arranque a bajo nivel: BIOS, UEFI, Secure Boot y gestión de particiones. Fundamento para firmware y boot security." },
  { id: 155, title: "Distribución Cuántica de Claves con ruido realista (TFG)", author: "Universidad de Valladolid", cat: "Hardware & Low-Level", level: "a", format: "pdf", url: "https://uvadoc.uva.es/bitstream/handle/10324/78681/TFG-G7575.pdf?sequence=1", license: "TFG open-access del repositorio institucional UVaDOC (Universidad de Valladolid)", desc: "Trabajo Fin de Grado sobre el cálculo de tasa de clave en protocolos QKD bajo ruido realista; conecta la física del canal (hardware cuántico) con la seguridad." },
  { id: 156, title: "Fundamentos de la Distribución Cuántica de Claves (QKD) y experimentación con QKDNetSim (TFG)", author: "Universidad de Valladolid", cat: "Hardware & Low-Level", level: "a", format: "pdf", url: "https://uvadoc.uva.es/bitstream/handle/10324/79606/TFG-G7746.pdf?sequence=1", license: "TFG open-access del repositorio institucional UVaDOC (Universidad de Valladolid)", desc: "Trabajo Fin de Grado sobre fundamentos de QKD como tecnología estratégica de seguridad de la información y su experimentación con el simulador QKDNetSim." },
  { id: 157, title: "Protección contra ataques de canal lateral en microprocesadores (TFG)", author: "Francisco Miguel Monge Chamorro / Universidad Politécnica de Madrid", cat: "Hardware & Low-Level", level: "a", format: "pdf", url: "https://oa.upm.es/83902/1/TFG_FRANCISCO_MIGUEL_MONGE_CHAMORRO.pdf", license: "TFG open-access del Archivo Digital UPM (oa.upm.es)", desc: "Trabajo Fin de Grado sobre ataques por canal lateral (análisis de consumo) en microprocesadores y contramedidas a nivel hardware/microarquitectura." },
  { id: 158, title: "Secure Boot, Measured Boot y TPM: seguridad del arranque y del firmware (TFG)", author: "Sergio González de Castro / Universidad Politécnica de Madrid", cat: "Hardware & Low-Level", level: "a", format: "pdf", url: "https://oa.upm.es/44946/1/TFG_SERGIO_GONZALEZ_DECASTRO.pdf", license: "TFG open-access del Archivo Digital UPM (oa.upm.es)", desc: "Trabajo Fin de Grado sobre seguridad de bajo nivel: Secure Boot, Measured Boot, TPM, UEFI y protección del firmware frente a malware persistente en el arranque." },
  // ── Reversing Avanzado ──
  { id: 159, title: "Introducción a la Ingeniería Inversa (charla/diapositivas universitarias)", author: "Ricardo J. Rodríguez (Universidad de Zaragoza)", cat: "Reversing Avanzado", level: "i", format: "pdf", url: "http://webdiis.unizar.es/~ricardo/files/slides/invitedTalks/slides_MSc-DAS-11.pdf", license: "Material docente público de la Universidad de Zaragoza", desc: "Transparencias académicas en español que introducen los conceptos y herramientas de ingeniería inversa de software, impartidas en contexto de máster." },
  { id: 160, title: "Introducción a la ingeniería inversa x86 (UNLEARNING SECURITY)", author: "UNLEARNING SECURITY (mirror legal en Exploit-DB)", cat: "Reversing Avanzado", level: "i", format: "pdf", url: "https://www.exploit-db.com/docs/spanish/18568-%5Bspanish%5D-introduction-to-reverse-engineering.pdf", license: "Documento de libre distribución alojado en el archivo público de Exploit-DB", desc: "Guía introductoria en español a la ingeniería inversa sobre x86: registros, instrucciones (MOV, CALL), desensamblado y primeros pasos con depuradores." },
  { id: 161, title: "ABO++: ejercicios y teoría sobre explotación de binarios y búsqueda de vulnerabilidades", author: "Fundación Sadosky (división STIC)", cat: "Reversing Avanzado", level: "a", format: "web", url: "https://github.com/fundacion-sadosky/abopp", license: "Material educativo público de la Fundación Sadosky (repositorio abierto en GitHub)", desc: "Curso práctico en español sobre corrupción de memoria: infoleak, shellcode, stack overflow, mitigaciones, ROP, heap, seguridad en C++ y fuzzing. Ejercicios resueltos." },
  { id: 162, title: "Análisis de Binarios usando ejecución simbólica (angr y Manticore)", author: "Universidad Nacional de Córdoba (FaMAF)", cat: "Reversing Avanzado", level: "a", format: "pdf", url: "https://rdu.unc.edu.ar/server/api/core/bitstreams/a4033d00-2cf5-4b54-a46e-56e7e2b49db8/content", license: "Acceso abierto (Repositorio Digital Universitario, UNC)", desc: "Trabajo académico en español sobre análisis de binarios mediante ejecución simbólica, con uso práctico de angr y Manticore y el problema de explosión de caminos." },
  { id: 163, title: "Detección y Clasificación de Malware con el Sistema de Análisis Cuckoo", author: "Aroca Páez (TFG, Universidad de Sevilla, ETSI)", cat: "Reversing Avanzado", level: "a", format: "pdf", url: "https://ereding.etsi.us.es/bibing/proyectos/abreproy/94086/fichero/TFG-4086+Aroca+P%C3%A1ez.pdf", license: "Acceso abierto (repositorio de proyectos ETSI, Universidad de Sevilla)", desc: "TFG en español que monta un laboratorio de análisis de malware con Cuckoo Sandbox, evaluando firmas y clasificación sobre ~16K muestras. Análisis dinámico aplicado." },
  { id: 164, title: "Rootkits (trabajo de máster en Seguridad de Sistemas Informáticos)", author: "Pablo Iglesias Morales (Universidade da Coruña)", cat: "Reversing Avanzado", level: "a", format: "pdf", url: "http://sabia.tic.udc.es/docencia/ssi/old/2007-2008/docs/trabajos/04%20-%20Rootkits/04%20-%20Rootkits.pdf", license: "Material docente público (asignatura SSI, UDC)", desc: "Trabajo académico en español sobre rootkits: tipos (aplicación y kernel), técnicas de ocultación a bajo nivel y detección. Base para reversing de malware avanzado." },
  // ── Investigación ──
  { id: 165, title: "Glosario de términos de ciberseguridad (INCIBE)", author: "INCIBE (Instituto Nacional de Ciberseguridad, España)", cat: "Investigación", level: "b", format: "pdf", url: "https://www.incibe.es/sites/default/files/contenidos/guias/doc/guia_glosario_ciberseguridad_2021.pdf", license: "Documento público de INCIBE (acceso libre)", desc: "Glosario oficial en español que normaliza la terminología de ciberseguridad (amenazas, vulnerabilidades, threat intelligence). Referencia para metodología y redacción rigurosa." },
  { id: 166, title: "Principios y recomendaciones básicas en ciberseguridad (CCN-CERT BP/01)", author: "CCN-CERT (Centro Criptológico Nacional, España)", cat: "Investigación", level: "b", format: "pdf", url: "https://www.ucm.es/data/cont/media/www/pag-114974/CCN-CERT_BP_01.pdf", license: "Documento público del CCN-CERT (guía de buenas prácticas de acceso libre)", desc: "Guía oficial del CERT gubernamental español con principios base de ciberseguridad y gestión de incidentes. Marco institucional para investigación y respuesta a amenazas." },
  { id: 167, title: "Ciberseguridad e Inteligencia Artificial: un enfoque innovador para la protección de datos", author: "Chullo Mamani, Cori Herrera y Correa Abanto (Revista Sinapsis, ITSUP)", cat: "Investigación", level: "i", format: "pdf", url: "https://dialnet.unirioja.es/descarga/articulo/10566642.pdf", license: "Acceso abierto (Dialnet, revista científica)", desc: "Artículo de investigación que explora aplicaciones y retos de la IA en ciberseguridad. Sirve como ejemplo de metodología y redacción de investigación académica en el área." },
  { id: 168, title: "Threat Intelligence, Cyber Kill Chain y MITRE ATT&CK (TFG)", author: "Universidad de Valladolid (Escuela de Ingeniería Informática)", cat: "Investigación", level: "i", format: "pdf", url: "https://uvadoc.uva.es/bitstream/handle/10324/71429/TFG-G6957.pdf?sequence=1&isAllowed=y", license: "Acceso abierto (repositorio UVaDoc, Universidad de Valladolid)", desc: "TFG en español que relaciona inteligencia de amenazas con la Cyber Kill Chain y la matriz MITRE ATT&CK para identificar técnicas y fases de ataque. Base de threat intelligence." },
  { id: 169, title: "Análisis y optimización del uso avanzado de AFL++ para detección de vulnerabilidades de memoria mediante fuzzing dirigido por cobertura", author: "Javier Blasco Carmona (Máster en Ciberseguridad, UPV)", cat: "Investigación", level: "a", format: "web", url: "https://riunet.upv.es/entities/publication/82359be5-b276-4484-85d6-a0161d9b9379", license: "Acceso abierto (repositorio RiuNet, Universitat Politècnica de València)", desc: "TFM en español sobre fuzzing dirigido por cobertura con AFL++: LAF-Intel, CmpLog, instrumentación y métricas de descubrimiento de fallos reproducibles. Vulnerability research aplicada." },
  { id: 170, title: "Trust under threat: adversarial robustness in interpretable prototype models (TFM, con resumen en español)", author: "Silvia Arenales Muñoz (Máster en Inteligencia Artificial, UPM)", cat: "Investigación", level: "a", format: "pdf", url: "https://oa.upm.es/90997/1/TFM_SILVIA_ARENALES_MUNOZ.pdf", license: "Creative Commons Reconocimiento-NoComercial-SinObraDerivada (repositorio open-access UPM)", desc: "TFM de investigación sobre robustez adversaria en modelos interpretables, con planteamiento metodológico, hipótesis y evaluación experimental. Ejemplo de research en seguridad de ML." },
];

export const LIBRARY_CATEGORIES: string[] = [...new Set(LIBRARY.map((b) => b.cat))];

export function libraryByCategory(cat: string): LibraryBook[] {
  return LIBRARY.filter((b) => b.cat === cat);
}

export function getLibraryBook(id: number): LibraryBook | undefined {
  return LIBRARY.find((b) => b.id === id);
}
