import type { PracticeExercise } from "./types";

// Matching exercises. The user drags/clicks each `s` (statement) onto one of `opts` (answers).
export const PRACTICE: PracticeExercise[] = [
  {
    id: 1,
    lesson: 1,
    title: "Ramas de CyberSec",
    items: [
      { s: "Simular ataques", a: "Red Team" },
      { s: "Monitorear amenazas", a: "Blue Team" },
      { s: "Investigar post-incidente", a: "Forense Digital" },
      { s: "Compliance y riesgos", a: "GRC" },
      { s: "Seguridad en desarrollo", a: "DevSecOps" },
    ],
    opts: ["Red Team", "Blue Team", "Forense Digital", "GRC", "DevSecOps"],
  },
  {
    id: 2,
    lesson: 2,
    title: "Clasifica por CIA",
    items: [
      { s: "Hacker lee emails sin cifrar", a: "Confidencialidad" },
      { s: "Ransomware cifra archivos", a: "Disponibilidad" },
      { s: "Modifican notas en la DB", a: "Integridad" },
      { s: "DDoS tumba la web", a: "Disponibilidad" },
      { s: "Virus corrompe backups", a: "Integridad" },
    ],
    opts: ["Confidencialidad", "Integridad", "Disponibilidad"],
  },
  {
    id: 3,
    lesson: 3,
    title: "Identifica el Malware",
    items: [
      { s: "Se adjunta a PDF, necesita click", a: "Virus" },
      { s: "Se propaga solo por la red", a: "Gusano" },
      { s: "Parece un juego legítimo", a: "Troyano" },
      { s: "Cifra archivos y pide Bitcoin", a: "Ransomware" },
      { s: "Se oculta a nivel del kernel", a: "Rootkit" },
    ],
    opts: ["Virus", "Gusano", "Troyano", "Ransomware", "Rootkit"],
  },
  {
    id: 4,
    lesson: 5,
    title: "Capas OSI y Ataques",
    items: [
      { s: "SQL Injection", a: "Capa 7" },
      { s: "SYN Flood", a: "Capa 4" },
      { s: "ARP Poisoning", a: "Capa 2" },
      { s: "IP Spoofing", a: "Capa 3" },
      { s: "Wiretapping", a: "Capa 1" },
    ],
    opts: ["Capa 1", "Capa 2", "Capa 3", "Capa 4", "Capa 7"],
  },
  {
    id: 5,
    lesson: 6,
    title: "Protocolos → Puertos",
    items: [
      { s: "SSH", a: "22" },
      { s: "HTTP", a: "80" },
      { s: "HTTPS", a: "443" },
      { s: "DNS", a: "53" },
      { s: "FTP", a: "21" },
      { s: "SMB", a: "445" },
      { s: "RDP", a: "3389" },
    ],
    opts: ["21", "22", "53", "80", "443", "445", "3389"],
  },
  {
    id: 6,
    lesson: 9,
    title: "Python: Librería → Uso",
    items: [
      { s: "Manipular paquetes de red", a: "scapy" },
      { s: "HTTP requests", a: "requests" },
      { s: "Protocolos Windows", a: "impacket" },
      { s: "Cifrado", a: "pycryptodome" },
      { s: "Forense de memoria", a: "volatility3" },
    ],
    opts: ["scapy", "requests", "impacket", "pycryptodome", "volatility3"],
  },
  {
    id: 7,
    lesson: 11,
    title: "SQL: Tipo de Ataque",
    items: [
      { s: "' OR 1=1 --", a: "Basic SQLi" },
      { s: "' UNION SELECT ...", a: "UNION-based" },
      { s: "' AND IF(1=1,SLEEP(5),0)", a: "Time-based blind" },
      { s: "' AND SUBSTRING(...)='a'", a: "Boolean blind" },
    ],
    opts: ["Basic SQLi", "UNION-based", "Time-based blind", "Boolean blind"],
  },
  {
    id: 8,
    lesson: 14,
    title: "Linux: Comando → Función",
    items: [
      { s: "ss -tulpn", a: "Puertos en escucha" },
      { s: "find / -perm -4000", a: "Buscar binarios SUID" },
      { s: "cat /etc/shadow", a: "Hashes de passwords" },
      { s: "tail -f auth.log", a: "Logs en vivo" },
      { s: "chmod 600", a: "Solo dueño rw" },
    ],
    opts: ["Puertos en escucha", "Buscar binarios SUID", "Hashes de passwords", "Logs en vivo", "Solo dueño rw"],
  },
  {
    id: 9,
    lesson: 18,
    title: "Ataques a Active Directory",
    items: [
      { s: "Crackear cuentas de servicio (SPN)", a: "Kerberoasting" },
      { s: "Replicar hashes simulando un DC", a: "DCSync" },
      { s: "Forjar TGTs con el hash de krbtgt", a: "Golden Ticket" },
      { s: "Autenticar con el hash NTLM", a: "Pass-the-Hash" },
      { s: "Cuentas sin preauth Kerberos", a: "AS-REP Roasting" },
    ],
    opts: ["Kerberoasting", "DCSync", "Golden Ticket", "Pass-the-Hash", "AS-REP Roasting"],
  },
  {
    id: 10,
    lesson: 20,
    title: "Conceptos de Criptografía",
    items: [
      { s: "Cifra y autentica (AEAD)", a: "AES-GCM" },
      { s: "Inseguro: revela patrones", a: "ECB" },
      { s: "Asimétrico por factorización", a: "RSA" },
      { s: "Hash de passwords lento", a: "Argon2" },
      { s: "Intercambio de clave compartida", a: "Diffie-Hellman" },
    ],
    opts: ["AES-GCM", "ECB", "RSA", "Argon2", "Diffie-Hellman"],
  },
  {
    id: 11,
    lesson: 25,
    title: "OWASP Top 10 → Categoría",
    items: [
      { s: "Cambiar /user/1 por /user/2", a: "Broken Access Control" },
      { s: "Bucket S3 público / defaults", a: "Security Misconfiguration" },
      { s: "' OR 1=1 --", a: "Injection" },
      { s: "Log4Shell (Log4j)", a: "Vulnerable Components" },
      { s: "Leer 169.254.169.254", a: "SSRF" },
    ],
    opts: ["Broken Access Control", "Security Misconfiguration", "Injection", "Vulnerable Components", "SSRF"],
  },
  {
    id: 12,
    lesson: 29,
    title: "Herramienta OSINT → Uso",
    items: [
      { s: "Dispositivos expuestos en Internet", a: "Shodan" },
      { s: "Emails y subdominios", a: "theHarvester" },
      { s: "Enumeración de subdominios", a: "amass" },
      { s: "Visualizar relaciones", a: "Maltego" },
      { s: "Datos de registro de dominio", a: "whois" },
    ],
    opts: ["Shodan", "theHarvester", "amass", "Maltego", "whois"],
  },
  {
    id: 13,
    lesson: 30,
    title: "Flag de Nmap → Acción",
    items: [
      { s: "Ping sweep (hosts vivos)", a: "-sn" },
      { s: "Versión de servicios", a: "-sV" },
      { s: "Detección de sistema operativo", a: "-O" },
      { s: "Todos los 65535 puertos", a: "-p-" },
      { s: "Decoys para evadir IDS", a: "-D RND:10" },
    ],
    opts: ["-sn", "-sV", "-O", "-p-", "-D RND:10"],
  },
  {
    id: 14,
    lesson: 44,
    title: "Plugin de Volatility → Qué extrae",
    items: [
      { s: "Lista de procesos", a: "pslist" },
      { s: "Conexiones de red", a: "netscan" },
      { s: "Código inyectado", a: "malfind" },
      { s: "Argumentos de proceso", a: "cmdline" },
      { s: "Hashes de cuentas", a: "hashdump" },
    ],
    opts: ["pslist", "netscan", "malfind", "cmdline", "hashdump"],
  },
  {
    id: 15,
    lesson: 49,
    title: "Identifica el servicio, control o vector de AWS",
    items: [
      { s: "Identidad y permisos", a: "IAM" },
      { s: "Almacenamiento de objetos", a: "S3" },
      { s: "Auditoría de llamadas a la API", a: "CloudTrail" },
      { s: "Detección de amenazas", a: "GuardDuty" },
      { s: "Red virtual aislada", a: "VPC" },
      { s: "Endpoint interno (169.254.169.254) que expone credenciales del rol si hay SSRF", a: "IMDS" },
      { s: "Permiso IAM crítico que permite pasar un rol a un servicio (vía clásica de escalada)", a: "iam:PassRole" },
      { s: "UUID acordado con un proveedor SaaS multi-tenant para prevenir confused deputy", a: "sts:ExternalId" },
      { s: "Política a nivel de Organization/OU que actúa como techo máximo de permisos", a: "SCP" },
      { s: "Emisor de credenciales temporales para federación OIDC / SSO / MFA sessions", a: "AWS STS" },
    ],
    opts: ["IAM", "S3", "CloudTrail", "GuardDuty", "VPC", "IMDS", "iam:PassRole", "sts:ExternalId", "SCP", "AWS STS"],
  },
  {
    id: 16,
    lesson: 4,
    title: "Asocia el framework o estándar con su propósito",
    items: [
      { s: "Marco con funciones Identify, Protect, Detect, Respond, Recover", a: "NIST CSF" },
      { s: "Norma certificable para Sistemas de Gestión de Seguridad de la Información (SGSI)", a: "ISO 27001" },
      { s: "Lista de los 10 riesgos más críticos en aplicaciones web", a: "OWASP Top 10" },
      { s: "Estándar de seguridad para datos de tarjetas de pago", a: "PCI-DSS" },
      { s: "Catálogo de controles de seguridad para sistemas federales de EEUU", a: "NIST SP 800-53" },
    ],
    opts: ["NIST CSF", "ISO 27001", "OWASP Top 10", "PCI-DSS", "NIST SP 800-53"],
  },
  {
    id: 17,
    lesson: 7,
    title: "Clasifica el direccionamiento IP y subnetting",
    items: [
      { s: "Rango 10.0.0.0/8 reservado para uso interno", a: "IP privada" },
      { s: "Dirección 8.8.8.8 enrutable en Internet", a: "IP pública" },
      { s: "Máscara /24 que da 254 hosts utilizables", a: "Máscara de subred" },
      { s: "Dirección 192.168.1.0 que identifica a la red", a: "Dirección de red" },
      { s: "Dirección 192.168.1.255 para enviar a todos los hosts de la subred", a: "Dirección de broadcast" },
      { s: "Rango 127.0.0.0/8 para referirse al propio host", a: "Loopback" },
    ],
    opts: ["IP privada", "IP pública", "Máscara de subred", "Dirección de red", "Dirección de broadcast", "Loopback"],
  },
  {
    id: 18,
    lesson: 8,
    title: "Interpreta filtros y conceptos de Wireshark",
    items: [
      { s: "Filtro que muestra solo tráfico del protocolo HTTP", a: "http" },
      { s: "Filtro que muestra paquetes hacia o desde la IP 10.0.0.5", a: "ip.addr == 10.0.0.5" },
      { s: "Filtro que muestra solo tráfico TCP del puerto 443", a: "tcp.port == 443" },
      { s: "Reconstruir un flujo TCP completo entre dos hosts", a: "Follow TCP Stream" },
      { s: "Filtro que muestra paquetes con el flag SYN activo", a: "tcp.flags.syn == 1" },
    ],
    opts: ["http", "ip.addr == 10.0.0.5", "tcp.port == 443", "Follow TCP Stream", "tcp.flags.syn == 1"],
  },
  {
    id: 19,
    lesson: 10,
    title: "Identifica la vulnerabilidad o defensa web (JavaScript)",
    items: [
      { s: "Inyectar <script> malicioso que se ejecuta en el navegador de otra víctima", a: "Cross-Site Scripting (XSS)" },
      { s: "Forzar al navegador de la víctima a enviar una petición no deseada", a: "Cross-Site Request Forgery (CSRF)" },
      { s: "Cabecera que restringe los orígenes de scripts permitidos", a: "Content Security Policy (CSP)" },
      { s: "Atributo de cookie que impide su lectura desde JavaScript", a: "HttpOnly" },
      { s: "Sanitizar/escapar la entrada del usuario antes de renderizarla", a: "Output encoding" },
    ],
    opts: ["Cross-Site Scripting (XSS)", "Cross-Site Request Forgery (CSRF)", "Content Security Policy (CSP)", "HttpOnly", "Output encoding"],
  },
  {
    id: 20,
    lesson: 12,
    title: "Identifica la vulnerabilidad de bajo nivel (C/C++)",
    items: [
      { s: "Escribir más datos de los que cabe en un arreglo de la pila", a: "Stack buffer overflow" },
      { s: "Usar un puntero después de haber liberado su memoria", a: "Use-after-free" },
      { s: "Pasar entrada del usuario directamente como cadena de formato a printf", a: "Format string" },
      { s: "Resultado de una operación que excede el rango del tipo entero", a: "Integer overflow" },
      { s: "Protección que coloca un valor centinela antes del return address", a: "Stack canary" },
    ],
    opts: ["Stack buffer overflow", "Use-after-free", "Format string", "Integer overflow", "Stack canary"],
  },
  {
    id: 21,
    lesson: 13,
    title: "Asocia el concepto de seguridad WiFi",
    items: [
      { s: "Protocolo de cifrado WiFi obsoleto y trivialmente roto (RC4)", a: "WEP" },
      { s: "Estándar que usa AES-CCMP y handshake de 4 vías", a: "WPA2" },
      { s: "Último estándar con SAE (Simultaneous Authentication of Equals)", a: "WPA3" },
      { s: "Punto de acceso falso que suplanta a una red legítima", a: "Evil Twin" },
      { s: "Ataque que reinstala claves explotando el handshake de WPA2", a: "KRACK" },
    ],
    opts: ["WEP", "WPA2", "WPA3", "Evil Twin", "KRACK"],
  },
  {
    id: 22,
    lesson: 15,
    title: "Identifica el elemento de Bash scripting",
    items: [
      { s: "Primera línea que indica el intérprete: #!/bin/bash", a: "Shebang" },
      { s: "Variable especial que contiene el primer argumento posicional", a: "$1" },
      { s: "Variable que guarda el código de salida del último comando", a: "$?" },
      { s: "Captura la salida de un comando para asignarla a una variable", a: "Command substitution" },
      { s: "Recorre una lista de elementos ejecutando un bloque por cada uno", a: "Bucle for" },
      { s: "Encadena comandos enviando la salida de uno a la entrada del otro", a: "Pipe" },
    ],
    opts: ["Shebang", "$1", "$?", "Command substitution", "Bucle for", "Pipe"],
  },
  {
    id: 23,
    lesson: 16,
    title: "Clasifica el mecanismo de permisos y hardening en Linux",
    items: [
      { s: "Bit que ejecuta el binario con los privilegios del propietario del archivo", a: "SUID" },
      { s: "Permite a un usuario ejecutar comandos como otro usuario según /etc/sudoers", a: "sudo" },
      { s: "Sistema MAC con políticas estrictas y contextos de seguridad por defecto en RHEL", a: "SELinux" },
      { s: "Sistema MAC basado en perfiles por aplicación, común en Ubuntu/Debian", a: "AppArmor" },
      { s: "Benchmarks de configuración segura por sistema operativo y software", a: "CIS Benchmarks" },
    ],
    opts: ["SUID", "sudo", "SELinux", "AppArmor", "CIS Benchmarks"],
  },
  {
    id: 24,
    lesson: 17,
    title: "Componentes de seguridad de Windows",
    items: [
      { s: "HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run: persistencia de programas al iniciar sesión", a: "Registro de Windows" },
      { s: "Registro centralizado de eventos de seguridad, sistema y aplicación", a: "Event Viewer" },
      { s: "Despliegue centralizado de políticas de seguridad en un dominio AD", a: "GPO" },
      { s: "Interfaz que permite inspeccionar scripts/payloads en memoria antes de ejecutarlos", a: "AMSI" },
      { s: "Procesos en segundo plano gestionados por services.msc con cuentas como LocalSystem", a: "Servicios" },
      { s: "Antivirus integrado con protección en tiempo real y reglas ASR", a: "Windows Defender" },
    ],
    opts: ["Registro de Windows", "Event Viewer", "GPO", "AMSI", "Servicios", "Windows Defender"],
  },
  {
    id: 25,
    lesson: 19,
    title: "Cmdlets y técnicas de PowerShell",
    items: [
      { s: "Recupera entradas del registro de eventos de seguridad", a: "Get-WinEvent" },
      { s: "Descarga y ejecuta contenido remoto en memoria con DownloadString", a: "Invoke-Expression (IEX)" },
      { s: "Registra cada bloque de script ejecutado para auditoría/forense", a: "Script Block Logging" },
      { s: "Restringe qué scripts pueden ejecutarse (Restricted, RemoteSigned, Bypass)", a: "Execution Policy" },
      { s: "Lista procesos en ejecución con su PID y uso de memoria", a: "Get-Process" },
    ],
    opts: ["Get-WinEvent", "Invoke-Expression (IEX)", "Script Block Logging", "Execution Policy", "Get-Process"],
  },
  {
    id: 26,
    lesson: 21,
    title: "Criptografía asimétrica",
    items: [
      { s: "Seguridad basada en la dificultad de factorizar el producto de dos primos grandes", a: "RSA" },
      { s: "Misma seguridad que RSA con claves mucho más cortas usando curvas elípticas", a: "ECC" },
      { s: "Permite a dos partes acordar una clave compartida sobre un canal inseguro", a: "Diffie-Hellman" },
      { s: "Se cifra con la clave pública del destinatario, solo él descifra con la privada", a: "Cifrado de clave pública" },
      { s: "Se firma con la clave privada y cualquiera verifica con la pública", a: "Firma digital" },
    ],
    opts: ["RSA", "ECC", "Diffie-Hellman", "Cifrado de clave pública", "Firma digital"],
  },
  {
    id: 27,
    lesson: 22,
    title: "Hashing, KDF y PKI",
    items: [
      { s: "Función de hash de 256 bits ampliamente usada en certificados e integridad", a: "SHA-256" },
      { s: "Algoritmo de hashing de contraseñas con factor de coste configurable y salt", a: "bcrypt" },
      { s: "KDF resistente a GPU/ASIC con parámetros de memoria, tiempo y paralelismo", a: "argon2" },
      { s: "Entidad que emite y firma certificados digitales en una PKI", a: "CA" },
      { s: "Documento que vincula una clave pública a una identidad, firmado por una CA", a: "Certificado X.509" },
    ],
    opts: ["SHA-256", "bcrypt", "argon2", "CA", "Certificado X.509"],
  },
  {
    id: 28,
    lesson: 23,
    title: "TLS, IPsec y VPN",
    items: [
      { s: "Negociación inicial que acuerda cipher suite, intercambia claves y autentica con certificado", a: "TLS handshake" },
      { s: "Conjunto que define algoritmo de intercambio de claves, cifrado y MAC", a: "Cipher suite" },
      { s: "Suite que cifra/autentica tráfico IP con modos transporte y túnel (ESP/AH)", a: "IPsec" },
      { s: "VPN moderna basada en curvas (Curve25519) con configuración mínima", a: "WireGuard" },
      { s: "Propiedad por la que comprometer la clave privada no descifra sesiones pasadas", a: "Forward Secrecy" },
    ],
    opts: ["TLS handshake", "Cipher suite", "IPsec", "WireGuard", "Forward Secrecy"],
  },
  {
    id: 29,
    lesson: 24,
    title: "Fundamentos de seguridad web",
    items: [
      { s: "Atributo de cookie que impide su lectura desde JavaScript (document.cookie)", a: "HttpOnly" },
      { s: "Atributo de cookie que controla su envío en peticiones cross-site (Lax/Strict/None)", a: "SameSite" },
      { s: "Cabeceras que controlan qué orígenes pueden acceder a un recurso vía fetch/XHR", a: "CORS" },
      { s: "Cabecera que mitiga XSS restringiendo las fuentes de scripts y recursos", a: "CSP" },
      { s: "Atributo de cookie que la limita a conexiones HTTPS", a: "Secure" },
    ],
    opts: ["HttpOnly", "SameSite", "CORS", "CSP", "Secure"],
  },
  {
    id: 30,
    lesson: 26,
    title: "OWASP Top 10 (Parte 2)",
    items: [
      { s: "Uso de librerías o componentes con CVE conocidos y sin parchear", a: "Vulnerable and Outdated Components" },
      { s: "Gestión deficiente de sesiones, credenciales por defecto o falta de MFA", a: "Identification and Authentication Failures" },
      { s: "Falta de validación de integridad en actualizaciones o pipelines CI/CD", a: "Software and Data Integrity Failures" },
      { s: "Ausencia de logs y alertas que retrasa la detección de incidentes", a: "Security Logging and Monitoring Failures" },
      { s: "El servidor realiza peticiones a URLs controladas por el atacante", a: "Server-Side Request Forgery" },
    ],
    opts: ["Vulnerable and Outdated Components", "Identification and Authentication Failures", "Software and Data Integrity Failures", "Security Logging and Monitoring Failures", "Server-Side Request Forgery"],
  },
  {
    id: 31,
    lesson: 27,
    title: "SQL Injection y XSS",
    items: [
      { s: "' UNION SELECT username,password FROM users-- para extraer datos de otra tabla", a: "Union-based SQLi" },
      { s: "Inferir datos observando tiempos de respuesta con SLEEP() o WAITFOR", a: "Blind SQLi (time-based)" },
      { s: "Payload <script> que se devuelve inmediato en la respuesta de un parámetro", a: "Reflected XSS" },
      { s: "Payload malicioso almacenado en la BD y servido a otros usuarios", a: "Stored XSS" },
      { s: "Consultas parametrizadas que separan código de datos para prevenir SQLi", a: "Prepared Statements" },
    ],
    opts: ["Union-based SQLi", "Blind SQLi (time-based)", "Reflected XSS", "Stored XSS", "Prepared Statements"],
  },
  {
    id: 32,
    lesson: 28,
    title: "CSRF, SSRF y File Upload",
    items: [
      { s: "Forzar al navegador de la víctima a enviar una petición autenticada sin su consentimiento", a: "CSRF" },
      { s: "Hacer que el servidor pida http://169.254.169.254/ para leer metadata cloud", a: "SSRF" },
      { s: "Subir un .php con webshell saltando la validación de extensión", a: "Malicious File Upload" },
      { s: "Token impredecible por sesión incluido en formularios para frenar CSRF", a: "Anti-CSRF Token" },
      { s: "Validar Content-Type, extensión y renombrar archivos fuera del webroot", a: "Upload Hardening" },
    ],
    opts: ["CSRF", "SSRF", "Malicious File Upload", "Anti-CSRF Token", "Upload Hardening"],
  },
  {
    id: 33,
    lesson: 31,
    title: "Enumeración de servicios",
    items: [
      { s: "enum4linux y smbclient para listar shares y usuarios en el puerto 445", a: "SMB" },
      { s: "snmpwalk con community string 'public' para volcar la MIB del dispositivo", a: "SNMP" },
      { s: "ldapsearch con bind anónimo para enumerar la estructura del directorio", a: "LDAP" },
      { s: "Transferencia de zona (AXFR) con dig para listar todos los registros", a: "DNS" },
      { s: "Banner grabbing del puerto 25 con VRFY/EXPN para enumerar usuarios", a: "SMTP" },
    ],
    opts: ["SMB", "SNMP", "LDAP", "DNS", "SMTP"],
  },
  {
    id: 34,
    lesson: 32,
    title: "Análisis de vulnerabilidades",
    items: [
      { s: "Identificador único de una vulnerabilidad pública conocida (formato CVE-AÑO-XXXX)", a: "CVE" },
      { s: "Sistema de puntuación de severidad de 0.0 a 10.0 con vector base/temporal/ambiental", a: "CVSS" },
      { s: "Diccionario de tipos de debilidad de software (p. ej. CWE-89 = SQLi)", a: "CWE" },
      { s: "Scanner que evalúa hosts contra una base de plugins de vulnerabilidades", a: "Nessus" },
      { s: "Catálogo de vulnerabilidades activamente explotadas que prioriza la CISA", a: "KEV" },
    ],
    opts: ["CVE", "CVSS", "CWE", "Nessus", "KEV"],
  },
  {
    id: 35,
    lesson: 33,
    title: "Metasploit Framework",
    items: [
      { s: "Módulo que aprovecha una vulnerabilidad específica para ganar acceso", a: "exploit" },
      { s: "Código que se ejecuta tras el exploit, como meterpreter o un reverse shell", a: "payload" },
      { s: "Módulo de escaneo, fuzzing o enumeración que no entrega shell", a: "auxiliary" },
      { s: "Acciones post-explotación como hashdump, persistencia o pivoting", a: "post" },
      { s: "Base de datos de codificadores para evadir antivirus/firmas (ej. shikata_ga_nai)", a: "encoder" },
    ],
    opts: ["exploit", "payload", "auxiliary", "post", "encoder"],
  },
  {
    id: 36,
    lesson: 34,
    title: "Componentes de Burp Suite",
    items: [
      { s: "Captura, inspecciona y modifica el tráfico HTTP/S en tránsito entre el navegador y el servidor", a: "Proxy" },
      { s: "Reenvía y edita manualmente una sola petición repetidas veces para probar variaciones", a: "Repeater" },
      { s: "Automatiza ataques fuzzeando posiciones con payloads (sniper, pitchfork, cluster bomb)", a: "Intruder" },
      { s: "Realiza crawling y auditoría automatizada para detectar vulnerabilidades (solo en Pro)", a: "Scanner" },
      { s: "Decodifica y codifica datos en Base64, URL, HTML, hex de forma manual", a: "Decoder" },
      { s: "Compara visualmente dos respuestas resaltando diferencias palabra a palabra", a: "Comparer" },
    ],
    opts: ["Proxy", "Repeater", "Intruder", "Scanner", "Decoder", "Comparer"],
  },
  {
    id: 37,
    lesson: 35,
    title: "Vectores de PrivEsc en Linux",
    items: [
      { s: "Un binario con bit s habilitado que ejecuta con privilegios del dueño del archivo", a: "SUID" },
      { s: "Tarea programada ejecutada por root con un script de permisos débiles o PATH manipulable", a: "Cron job" },
      { s: "cap_setuid+ep asignada a un binario sin necesidad del bit SUID completo", a: "Capabilities" },
      { s: "Lista de binarios legítimos abusables para romper restricciones y escalar (find, vim, less)", a: "GTFOBins" },
      { s: "Permite ejecutar comandos específicos como root según reglas en /etc/sudoers", a: "Sudo" },
    ],
    opts: ["SUID", "Cron job", "Capabilities", "GTFOBins", "Sudo"],
  },
  {
    id: 38,
    lesson: 36,
    title: "PrivEsc en Windows",
    items: [
      { s: "Robo de un token de impersonación de un proceso de mayor privilegio (Potato attacks)", a: "Token impersonation" },
      { s: "Ruta de ejecutable de servicio sin comillas que permite secuestrar la ejecución", a: "Unquoted service path" },
      { s: "Permisos débiles sobre el binario o registro de un servicio que permiten reemplazarlo", a: "Weak service permissions" },
      { s: "Técnica que evita el prompt de elevación abusando de auto-elevación (fodhelper, eventvwr)", a: "UAC bypass" },
      { s: "Despliegue MSI con privilegios SYSTEM por política AlwaysInstallElevated habilitada", a: "AlwaysInstallElevated" },
    ],
    opts: ["Token impersonation", "Unquoted service path", "Weak service permissions", "UAC bypass", "AlwaysInstallElevated"],
  },
  {
    id: 39,
    lesson: 37,
    title: "Pivoting y movimiento lateral",
    items: [
      { s: "Fuerza herramientas CLI a enrutar su tráfico a través de un proxy SOCKS o HTTP", a: "proxychains" },
      { s: "Túnel dinámico que expone una red interna como un proxy genérico de capa de aplicación", a: "SOCKS proxy" },
      { s: "Autenticación contra un recurso usando el hash NTLM sin conocer la contraseña en claro", a: "Pass-the-Hash" },
      { s: "Reenvío de un puerto local hacia un host interno a través del host comprometido", a: "Port forwarding" },
      { s: "Reutilización de un ticket Kerberos TGT/TGS robado para autenticarse en otros servicios", a: "Pass-the-Ticket" },
    ],
    opts: ["proxychains", "SOCKS proxy", "Pass-the-Hash", "Port forwarding", "Pass-the-Ticket"],
  },
  {
    id: 40,
    lesson: 38,
    title: "Principios de ingeniería social",
    items: [
      { s: "Crear urgencia o miedo de quedarse fuera para forzar una decisión rápida", a: "Escasez/Urgencia" },
      { s: "Suplantar a un directivo o figura de poder para que la víctima obedezca sin cuestionar", a: "Autoridad" },
      { s: "Ofrecer un favor o regalo para generar sensación de deuda en la víctima", a: "Reciprocidad" },
      { s: "Mostrar que 'todos los demás ya lo hicieron' para inducir la misma conducta", a: "Prueba social" },
      { s: "Inventar un escenario falso creíble para obtener información (ej. soporte técnico)", a: "Pretexting" },
    ],
    opts: ["Escasez/Urgencia", "Autoridad", "Reciprocidad", "Prueba social", "Pretexting"],
  },
  {
    id: 41,
    lesson: 39,
    title: "Tipos y técnicas de phishing",
    items: [
      { s: "Ataque dirigido a una persona u organización concreta con información personalizada", a: "Spear phishing" },
      { s: "Compromiso de correo corporativo suplantando a un ejecutivo para ordenar transferencias", a: "BEC" },
      { s: "Spear phishing dirigido específicamente a altos ejecutivos de gran valor (C-level)", a: "Whaling" },
      { s: "Uso de homóglifos y dominios look-alike para que la URL parezca legítima", a: "Typosquatting" },
      { s: "Esconder el contenido malicioso del correo en una imagen para evadir filtros de texto", a: "Evasión por imagen" },
    ],
    opts: ["Spear phishing", "BEC", "Whaling", "Typosquatting", "Evasión por imagen"],
  },
  {
    id: 42,
    lesson: 40,
    title: "Tipos de malware",
    items: [
      { s: "Cifra archivos de la víctima y exige un rescate para descifrarlos", a: "Ransomware" },
      { s: "Se replica y propaga por la red de forma autónoma sin intervención del usuario", a: "Gusano (worm)" },
      { s: "Se disfraza de software legítimo para que el usuario lo ejecute voluntariamente", a: "Troyano" },
      { s: "Mantiene acceso persistente oculto al sistema escondiéndose del SO y del antivirus", a: "Rootkit" },
      { s: "Registra las pulsaciones del teclado para robar credenciales", a: "Keylogger" },
      { s: "Software que muestra publicidad no deseada y rastrea hábitos del usuario", a: "Adware" },
    ],
    opts: ["Ransomware", "Gusano (worm)", "Troyano", "Rootkit", "Keylogger", "Adware"],
  },
  {
    id: 43,
    lesson: 41,
    title: "Análisis estático de malware",
    items: [
      { s: "Extrae cadenas ASCII/Unicode legibles del binario para hallar URLs, IPs o rutas", a: "strings" },
      { s: "Estructura del ejecutable Windows que describe secciones, imports y entry point", a: "PE headers" },
      { s: "Comprime/ofusca el binario para dificultar el análisis; UPX es un ejemplo común", a: "Packer" },
      { s: "Huella criptográfica del archivo (MD5/SHA256) usada para buscarlo en VirusTotal", a: "Hashing" },
      { s: "Lista de funciones de la API de Windows que el binario importa de DLLs", a: "Import table (IAT)" },
    ],
    opts: ["strings", "PE headers", "Packer", "Hashing", "Import table (IAT)"],
  },
  {
    id: 44,
    lesson: 42,
    title: "Análisis dinámico de malware",
    items: [
      { s: "Entorno aislado donde se detona la muestra para observar su comportamiento de forma segura", a: "Sandbox" },
      { s: "Ejecución paso a paso del binario para inspeccionar registros y memoria en tiempo real", a: "Debugging" },
      { s: "Intercepta y registra las llamadas a la API del sistema que hace el malware (API Monitor)", a: "API monitoring" },
      { s: "Captura el tráfico de red para descubrir la comunicación con el servidor C2", a: "Análisis de red" },
      { s: "Compara el estado del sistema antes y después de la ejecución (Regshot)", a: "Snapshot diffing" },
    ],
    opts: ["Sandbox", "Debugging", "API monitoring", "Análisis de red", "Snapshot diffing"],
  },
  {
    id: 45,
    lesson: 43,
    title: "Fundamentos de forense digital",
    items: [
      { s: "Documentación que registra cada manejo de la evidencia para garantizar su admisibilidad legal", a: "Cadena de custodia" },
      { s: "Recolectar primero lo más efímero: registros y caché de CPU antes que el disco", a: "Orden de volatilidad" },
      { s: "Crear una copia idéntica bit a bit del medio original para no alterar la prueba", a: "Imagen forense" },
      { s: "Hash calculado antes y después para demostrar que la evidencia no fue modificada", a: "Verificación de integridad" },
      { s: "Dispositivo que impide cualquier escritura al medio original durante la adquisición", a: "Write blocker" },
    ],
    opts: ["Cadena de custodia", "Orden de volatilidad", "Imagen forense", "Verificación de integridad", "Write blocker"],
  },
  {
    id: 46,
    lesson: 45,
    title: "Herramientas de forense de red",
    items: [
      { s: "Captura completa de paquetes en disco analizable con Wireshark o tcpdump", a: "PCAP" },
      { s: "Metadatos de flujo (IP origen/destino, puertos, bytes) sin payload completo", a: "NetFlow" },
      { s: "Monitor de seguridad de red que genera logs estructurados de protocolos de alto nivel", a: "Zeek" },
      { s: "Sistema que inspecciona el tráfico y alerta ante firmas maliciosas conocidas (Snort/Suricata)", a: "IDS" },
      { s: "Reconstrucción del contenido de una sesión TCP a partir de los paquetes capturados", a: "Stream reassembly" },
    ],
    opts: ["PCAP", "NetFlow", "Zeek", "IDS", "Stream reassembly"],
  },
  {
    id: 47,
    lesson: 46,
    title: "Conceptos de SIEM",
    items: [
      { s: "Vincular eventos de fuentes distintas para detectar un patrón de ataque combinado", a: "Correlación" },
      { s: "Convertir logs heterogéneos a un formato común de campos antes de indexarlos", a: "Normalización/Parsing" },
      { s: "Lenguaje de consulta de Splunk para buscar y transformar eventos (SPL)", a: "SPL" },
      { s: "Stack Elasticsearch + Logstash + Kibana para ingesta, búsqueda y visualización", a: "ELK Stack" },
      { s: "Condición que dispara una alerta cuando se cumple un umbral o secuencia definida", a: "Regla de detección" },
    ],
    opts: ["Correlación", "Normalización/Parsing", "SPL", "ELK Stack", "Regla de detección"],
  },
  {
    id: 48,
    lesson: 47,
    title: "Fases del ciclo IR (NIST)",
    items: [
      { s: "Establecer capacidades, políticas, herramientas y entrenamiento antes del incidente", a: "Preparación" },
      { s: "Detectar, analizar y determinar el alcance y la severidad del incidente", a: "Detección y análisis" },
      { s: "Aislar sistemas afectados, eliminar la amenaza y restaurar las operaciones normales", a: "Contención, erradicación y recuperación" },
      { s: "Reunión post-mortem para documentar lecciones aprendidas y mejorar el proceso", a: "Actividad post-incidente" },
    ],
    opts: ["Preparación", "Detección y análisis", "Contención, erradicación y recuperación", "Actividad post-incidente"],
  },
  {
    id: 49,
    lesson: 48,
    title: "Threat hunting: IoC, IoA y Pyramid of Pain",
    items: [
      { s: "Artefacto observable de un compromiso ya ocurrido, como un hash o una IP maliciosa", a: "IoC" },
      { s: "Indicador del comportamiento o intención del atacante, independiente de las herramientas", a: "IoA" },
      { s: "En la pirámide, el nivel trivial de cambiar para el atacante (hash de archivo)", a: "Hash de archivo" },
      { s: "En la pirámide, lo más doloroso de cambiar para el atacante: sus técnicas (TTPs)", a: "TTPs" },
      { s: "Hipótesis de búsqueda proactiva de amenazas no detectadas por las alertas existentes", a: "Hunt hypothesis" },
    ],
    opts: ["IoC", "IoA", "Hash de archivo", "TTPs", "Hunt hypothesis"],
  },
  {
    id: 50,
    lesson: 50,
    title: "Identidad y acceso en Azure y GCP",
    items: [
      { s: "Servicio de identidad central de Azure que reemplazó a Azure AD para emitir tokens OAuth2/OIDC", a: "Microsoft Entra ID" },
      { s: "Credencial sin secretos rotada automáticamente por la plataforma para que una VM acceda a otros recursos de Azure", a: "Managed Identity" },
      { s: "Cuenta no humana de GCP cuya clave JSON filtrada permite suplantar cargas de trabajo", a: "Service Account de GCP" },
      { s: "Mecanismo de GCP que federa identidades externas (GitHub Actions, AWS) sin claves de larga duración", a: "Workload Identity Federation" },
      { s: "Asignación de permisos en Azure que vincula un principal a un rol sobre un scope (subscription/RG/recurso)", a: "Azure RBAC role assignment" },
      { s: "Tenant separado de Entra diseñado para identidades de clientes (millones, social login, GDPR)", a: "Azure AD B2C (CIAM)" },
      { s: "Ataque que convence al usuario de conceder permisos OAuth a una app maliciosa (evade MFA)", a: "Consent phishing" },
      { s: "Perímetro lógico de GCP que bloquea la exfiltración a servicios como BigQuery aunque el IAM sea válido", a: "VPC Service Controls" },
      { s: "Restricción sobre workload_identity_provider (attribute.repository == 'org/repo') que previene impersonación cross-repo", a: "attribute_condition" },
      { s: "Sucesor de Pod Identity en AKS que usa OIDC federation por pod (alineado con estándares cross-cloud)", a: "Azure AD Workload Identity" },
    ],
    opts: ["Microsoft Entra ID", "Managed Identity", "Service Account de GCP", "Workload Identity Federation", "Azure RBAC role assignment", "Azure AD B2C (CIAM)", "Consent phishing", "VPC Service Controls", "attribute_condition", "Azure AD Workload Identity"],
  },
  {
    id: 51,
    lesson: 51,
    title: "Aislamiento y endurecimiento de contenedores",
    items: [
      { s: "Función del kernel que restringe qué syscalls puede invocar un proceso del contenedor mediante una BPF filter", a: "seccomp" },
      { s: "Mecanismo que particiona PID, mount, net y user dando la ilusión de un sistema aislado", a: "namespaces" },
      { s: "Montar /var/run/docker.sock dentro del contenedor permite este escape al host", a: "Docker socket escape" },
      { s: "Subsistema del kernel que limita CPU, memoria e I/O por contenedor", a: "cgroups" },
      { s: "En Kubernetes, vincula un ServiceAccount a verbos sobre recursos vía Role/RoleBinding", a: "K8s RBAC" },
      { s: "Conjunto de privilegios granulares (CAP_SYS_ADMIN, CAP_NET_RAW) que debe dropearse para reducir superficie", a: "Linux capabilities" },
      { s: "Anotación EKS que vincula un ServiceAccount a un rol IAM vía OIDC federation por pod", a: "IRSA (IAM Roles for Service Accounts)" },
      { s: "Herramienta que intercepta requests al API server y rechaza pods no conformes con política declarativa (Rego o YAML)", a: "Admission controller (OPA/Kyverno)" },
      { s: "Sistema de runtime detection que observa syscalls con eBPF y alerta comportamiento anómalo (shell en pod prod)", a: "Falco" },
      { s: "Firma criptográfica keyless de imágenes con OIDC del CI + transparency log público (Rekor)", a: "cosign / Sigstore" },
      { s: "Provider CSI que monta secrets desde HashiCorp Vault directamente en el pod sin tocar etcd", a: "Vault CSI Provider" },
    ],
    opts: ["seccomp", "namespaces", "Docker socket escape", "cgroups", "K8s RBAC", "Linux capabilities", "IRSA (IAM Roles for Service Accounts)", "Admission controller (OPA/Kyverno)", "Falco", "cosign / Sigstore", "Vault CSI Provider"],
  },
  {
    id: 52,
    lesson: 52,
    title: "Controles de DevSecOps en el pipeline",
    items: [
      { s: "Analiza el código fuente o bytecode sin ejecutarlo para detectar vulnerabilidades de inyección", a: "SAST" },
      { s: "Lanza peticiones contra la aplicación corriendo para hallar fallos en runtime", a: "DAST" },
      { s: "Inventario firmado de todos los componentes y dependencias de un artefacto (CycloneDX/SPDX)", a: "SBOM" },
      { s: "Escaneo que detecta tokens, claves API y credenciales hardcodeadas en el repo", a: "Secrets scanning" },
      { s: "Análisis de dependencias de terceros para CVEs conocidos en librerías", a: "SCA" },
      { s: "Mecanismo que federa la identidad OIDC del CI con la nube para obtener credenciales STS sin secrets long-lived", a: "OIDC federation en CI/CD" },
      { s: "API REST estandarizada (RFC 7644) para provisionar/deprovisionar usuarios cross-SaaS desde el IdP", a: "SCIM" },
      { s: "Framework de 4 niveles que garantiza integridad y procedencia de un artefacto (build hermético, provenance no falsificable)", a: "SLSA" },
      { s: "Ataque que publica un package con nombre interno en el registry público con versión mayor (Alex Birsan 2021)", a: "Dependency confusion" },
      { s: "Trigger de GitHub Actions con acceso a secrets del base; peligroso si se hace checkout del head del PR", a: "pull_request_target" },
    ],
    opts: ["SAST", "DAST", "SBOM", "Secrets scanning", "SCA", "OIDC federation en CI/CD", "SCIM", "SLSA", "Dependency confusion", "pull_request_target"],
  },
  {
    id: 53,
    lesson: 53,
    title: "Vectores en IoT y Mobile",
    items: [
      { s: "Extracción del binario de un dispositivo IoT vía SPI flash o UART para análisis estático", a: "Firmware dumping" },
      { s: "Ataque de sniffing/spoofing sobre el protocolo de baja energía de wearables y sensores", a: "BLE attack" },
      { s: "Estándar de OWASP que define requisitos de seguridad verificables para apps móviles", a: "OWASP MASVS" },
      { s: "Almacenamiento inseguro de claves en SharedPreferences o NSUserDefaults en texto plano", a: "Insecure data storage" },
      { s: "Interfaz de depuración de hardware que da acceso de bajo nivel a la CPU del chip", a: "JTAG debugging" },
    ],
    opts: ["Firmware dumping", "BLE attack", "OWASP MASVS", "Insecure data storage", "JTAG debugging"],
  },
  {
    id: 54,
    lesson: 54,
    title: "Certificaciones y metodología profesional",
    items: [
      { s: "Certificación 100% práctica de Offensive Security con examen de 24h de explotación hands-on", a: "OSCP" },
      { s: "Certificación gerencial de (ISC)² basada en 8 dominios de gobernanza y gestión de riesgo", a: "CISSP" },
      { s: "Sección del reporte de pentest que cuantifica probabilidad e impacto usando CVSS", a: "Risk rating" },
      { s: "Estándar de ejecución de pruebas de penetración con 7 fases (PTES)", a: "PTES" },
      { s: "Sección ejecutiva del informe dirigida a stakeholders no técnicos sin jerga", a: "Executive summary" },
    ],
    opts: ["OSCP", "CISSP", "Risk rating", "PTES", "Executive summary"],
  },
  {
    id: 55,
    lesson: 55,
    title: "Primitivas de Python ofensivo",
    items: [
      { s: "Modelo de concurrencia de un solo hilo con event loop ideal para scanners masivos de red", a: "asyncio" },
      { s: "Módulo de la stdlib para invocar funciones de librerías C nativas y manipular structs", a: "ctypes" },
      { s: "Framework de instrumentación dinámica que inyecta JavaScript en procesos en runtime", a: "frida" },
      { s: "Librería de manipulación e inyección de paquetes capa 2/3 para crafting personalizado", a: "scapy" },
      { s: "Empaqueta el corutina y la programa cooperativamente en el event loop con await", a: "asyncio" },
    ],
    opts: ["asyncio", "ctypes", "frida", "scapy"],
  },
  {
    id: 56,
    lesson: 56,
    title: "Go para herramientas de seguridad",
    items: [
      { s: "Modelo de concurrencia ligero de Go ideal para fuzzers y scanners de alta paralelización", a: "goroutines" },
      { s: "Compilación que produce un único ejecutable portable sin dependencias dinámicas para droppers", a: "Static binary" },
      { s: "Primitiva de sincronización para pasar datos entre goroutines de forma segura", a: "channels" },
      { s: "Sintaxis '// +build windows' o GOOS=windows para generar payloads multiplataforma", a: "Cross-compilation" },
      { s: "Paquete de la stdlib usado para construir clientes y servidores de red en herramientas C2", a: "net package" },
    ],
    opts: ["goroutines", "Static binary", "channels", "Cross-compilation", "net package"],
  },
  {
    id: 57,
    lesson: 57,
    title: "Desarrollo de módulos en Metasploit",
    items: [
      { s: "Tipo de módulo que entrega el payload y dispara la vulnerabilidad contra el objetivo", a: "Exploit module" },
      { s: "Código que se ejecuta tras la explotación, p.ej. una reverse shell o Meterpreter", a: "Payload" },
      { s: "Módulo que escanea, enumera o realiza fuzzing sin entregar shell", a: "Auxiliary module" },
      { s: "Mixin de Ruby que agrega capacidades HTTP a un módulo de Metasploit", a: "HttpClient mixin" },
      { s: "Sección Ruby del módulo que define name, options, targets y references", a: "Module metadata" },
    ],
    opts: ["Exploit module", "Payload", "Auxiliary module", "HttpClient mixin", "Module metadata"],
  },
  {
    id: 58,
    lesson: 58,
    title: "Ataques y defensas en el frontend",
    items: [
      { s: "Inyección que ejecuta script manipulando el DOM en el cliente sin tocar el servidor", a: "DOM-based XSS" },
      { s: "Cabecera/política que restringe orígenes de scripts y mitiga XSS en navegador", a: "Content Security Policy" },
      { s: "Superponer un iframe invisible para engañar al usuario y secuestrar clics", a: "Clickjacking" },
      { s: "Librería que limpia HTML potencialmente malicioso antes de insertarlo en el DOM", a: "DOMPurify" },
      { s: "Cabecera X-Frame-Options o frame-ancestors que evita el embebido en iframes hostiles", a: "Frame busting" },
    ],
    opts: ["DOM-based XSS", "Content Security Policy", "Clickjacking", "DOMPurify", "Frame busting"],
  },
  {
    id: 59,
    lesson: 59,
    title: "Explotación de heap en glibc",
    items: [
      { s: "Caché LIFO por hilo de glibc 2.26+ que agrupa chunks pequeños liberados sin protecciones de doble-free fuertes", a: "tcache" },
      { s: "Uso de un puntero a memoria ya liberada que permite hijack de la estructura del chunk", a: "Use-after-free" },
      { s: "Corrupción del campo de tamaño del chunk siguiente al escribir más allá del buffer", a: "Heap overflow" },
      { s: "Técnica que envenena el puntero fd de un chunk libre para retornar un puntero arbitrario en malloc", a: "tcache poisoning" },
      { s: "Liberar dos veces el mismo chunk para corromper las listas de chunks libres", a: "Double free" },
    ],
    opts: ["tcache", "Use-after-free", "Heap overflow", "tcache poisoning", "Double free"],
  },
  {
    id: 60,
    lesson: 60,
    title: "Explotación de kernel y mitigaciones",
    items: [
      { s: "Mitigación que impide al kernel ejecutar código ubicado en páginas de userland", a: "SMEP" },
      { s: "Mitigación que impide al kernel acceder (leer/escribir) datos de userland salvo flag explícito", a: "SMAP" },
      { s: "Interfaz por la que userland solicita servicios privilegiados al kernel y superficie de ataque clave", a: "syscall" },
      { s: "Técnica que reescribe el puntero de credenciales (commit_creds(prepare_kernel_cred(0))) para root", a: "Credential overwrite" },
      { s: "Aleatorización de la dirección base del kernel para dificultar ROP, derrotada por leaks", a: "KASLR" },
    ],
    opts: ["SMEP", "SMAP", "syscall", "Credential overwrite", "KASLR"],
  },
  {
    id: 61,
    lesson: 61,
    title: "Explotación de navegadores",
    items: [
      { s: "Compilador del motor JS que genera código nativo y blanco frecuente de bugs de optimización", a: "JIT compiler" },
      { s: "Bug donde el motor trata un objeto como un tipo distinto al real, dando primitivas de R/W", a: "Type confusion" },
      { s: "Aislamiento de proceso que confina el renderer; debe romperse para comprometer el host", a: "Sandbox" },
      { s: "Engañar al optimizador para que elimine un bounds check y permita acceso OOB en arrays", a: "Bounds check elimination" },
      { s: "Primitivas addrof/fakeobj que convierten un bug en lectura/escritura arbitraria en el heap del motor", a: "addrof/fakeobj" },
    ],
    opts: ["JIT compiler", "Type confusion", "Sandbox", "Bounds check elimination", "addrof/fakeobj"],
  },
  {
    id: 62,
    lesson: 62,
    title: "Cadenas de reutilización de código y bypass",
    items: [
      { s: "Encadenar gadgets que terminan en 'ret' usando datos en la pila para ejecutar código sin inyectar", a: "ROP" },
      { s: "Variante que encadena gadgets terminados en saltos indirectos (jmp/call reg) evadiendo CFI de retornos", a: "JOP" },
      { s: "Mitigación de páginas no ejecutables que obliga a reutilizar código existente en vez de shellcode", a: "DEP/NX" },
      { s: "Aleatorización del layout de memoria derrotada típicamente con un info leak", a: "ASLR" },
      { s: "Integridad de flujo de control que valida destinos indirectos contra un set permitido", a: "CFI" },
    ],
    opts: ["ROP", "JOP", "DEP/NX", "ASLR", "CFI"],
  },
  {
    id: 63,
    lesson: 63,
    title: "Técnicas de criptoanálisis",
    items: [
      { s: "Analiza cómo diferencias controladas en la entrada se propagan a la salida de un cifrado de bloque", a: "Criptoanálisis diferencial" },
      { s: "Aproxima la S-box con relaciones lineales probabilísticas entre bits de entrada, salida y clave", a: "Criptoanálisis lineal" },
      { s: "Explota mensajes de error de padding (PKCS#7) en modo CBC para descifrar sin la clave", a: "Padding oracle" },
      { s: "Mide tiempo de ejecución para inferir bits de la clave en comparaciones no constantes", a: "Timing attack" },
      { s: "Recupera la clave probando todas las combinaciones, factible solo con espacios pequeños", a: "Fuerza bruta" },
    ],
    opts: ["Criptoanálisis diferencial", "Criptoanálisis lineal", "Padding oracle", "Timing attack", "Fuerza bruta"],
  },
  {
    id: 64,
    lesson: 64,
    title: "Amenaza cuántica y esquemas PQC",
    items: [
      { s: "Algoritmo cuántico que factoriza enteros en tiempo polinómico, rompiendo RSA y ECC", a: "Algoritmo de Shor" },
      { s: "Algoritmo cuántico que da speedup cuadrático en búsqueda, reduciendo seguridad simétrica a la mitad", a: "Algoritmo de Grover" },
      { s: "KEM estandarizado por NIST (ML-KEM) basado en module-LWE sobre retículos", a: "Kyber" },
      { s: "Esquema de firma digital estandarizado por NIST (ML-DSA) basado en retículos", a: "Dilithium" },
      { s: "Problema matemático duro (SVP/CVP) base de la criptografía post-cuántica de retículos", a: "Problema de retículos" },
    ],
    opts: ["Algoritmo de Shor", "Algoritmo de Grover", "Kyber", "Dilithium", "Problema de retículos"],
  },
  {
    id: 65,
    lesson: 65,
    title: "Pruebas de conocimiento cero y MPC",
    items: [
      { s: "Prueba sucinta no interactiva que requiere un trusted setup (CRS) y verificación en ms", a: "zk-SNARK" },
      { s: "Prueba transparente sin trusted setup, post-cuántica, basada en hashes, con pruebas más grandes", a: "zk-STARK" },
      { s: "Esquema de Shamir que reparte un secreto en n shares recuperable con un umbral t", a: "Secret sharing" },
      { s: "Cómputo conjunto sobre datos privados sin que las partes revelen sus entradas", a: "MPC" },
      { s: "Propiedad de un ZKP que garantiza que el verificador no aprende nada salvo la validez", a: "Zero-knowledge" },
    ],
    opts: ["zk-SNARK", "zk-STARK", "Secret sharing", "MPC", "Zero-knowledge"],
  },
  {
    id: 66,
    lesson: 66,
    title: "Cifrado homomórfico y sus esquemas",
    items: [
      { s: "Permite evaluar circuitos arbitrarios (sumas y productos ilimitados) sobre cifrados", a: "FHE" },
      { s: "Esquema de FHE para aritmética exacta sobre enteros, eficiente en operaciones modulares", a: "BFV" },
      { s: "Esquema de FHE que soporta aritmética aproximada de números reales/complejos, ideal para ML", a: "CKKS" },
      { s: "Operación que reduce el ruido de un cifrado para permitir más operaciones, costosa en tiempo", a: "Bootstrapping" },
      { s: "Cantidad que crece con cada operación homomórfica y eventualmente impide descifrar", a: "Ruido" },
    ],
    opts: ["FHE", "BFV", "CKKS", "Bootstrapping", "Ruido"],
  },
  {
    id: 67,
    lesson: 67,
    title: "Ataques adversariales contra modelos ML",
    items: [
      { s: "Inyectar muestras manipuladas en el dataset de entrenamiento para degradar o sesgar el modelo", a: "Poisoning" },
      { s: "Perturbación adversarial de un solo paso usando el signo del gradiente de la pérdida", a: "FGSM" },
      { s: "Ataque iterativo de múltiples pasos con proyección sobre una bola de norma acotada", a: "PGD" },
      { s: "Modificar la entrada en inferencia para que el modelo ya entrenado clasifique mal", a: "Evasion" },
      { s: "Insertar un patrón gatillo que activa un comportamiento malicioso solo ante un trigger", a: "Backdoor" },
    ],
    opts: ["Poisoning", "FGSM", "PGD", "Evasion", "Backdoor"],
  },
  {
    id: 68,
    lesson: 68,
    title: "Ataques de privacidad sobre modelos entrenados",
    items: [
      { s: "Determinar si un registro específico formó parte del conjunto de entrenamiento", a: "Membership inference" },
      { s: "Reconstruir características representativas de una clase a partir de las salidas del modelo", a: "Model inversion" },
      { s: "Extraer datos memorizados literalmente (ej. PII) de un modelo generativo", a: "Training data extraction" },
      { s: "Garantía formal que acota la influencia de un único registro mediante ruido calibrado", a: "Differential privacy" },
      { s: "Replicar la funcionalidad de un modelo solo consultando su API de predicción", a: "Model extraction" },
    ],
    opts: ["Membership inference", "Model inversion", "Training data extraction", "Differential privacy", "Model extraction"],
  },
  {
    id: 69,
    lesson: 69,
    title: "Riesgos de seguridad en LLMs (OWASP LLM Top 10)",
    items: [
      { s: "Texto en datos externos recuperados que altera las instrucciones del sistema sin que el usuario lo escriba", a: "Indirect prompt injection" },
      { s: "El usuario fuerza al modelo a ignorar sus salvaguardas y políticas de seguridad", a: "Jailbreak" },
      { s: "El modelo expone secretos del system prompt o datos de otra sesión en su respuesta", a: "Sensitive information disclosure" },
      { s: "La salida del LLM se ejecuta sin validar, permitiendo XSS o ejecución de código aguas abajo", a: "Insecure output handling" },
      { s: "Consumo deliberado de contexto/recursos para degradar el servicio del modelo", a: "Unbounded consumption" },
    ],
    opts: ["Indirect prompt injection", "Jailbreak", "Sensitive information disclosure", "Insecure output handling", "Unbounded consumption"],
  },
  {
    id: 70,
    lesson: 70,
    title: "Amenazas en la cadena de suministro de ML",
    items: [
      { s: "Serializar un modelo de forma que __reduce__ ejecute código arbitrario al deserializar", a: "Pickle deserialization RCE" },
      { s: "Firmar criptográficamente y registrar el origen verificable de un artefacto de modelo", a: "Model provenance" },
      { s: "Subir un modelo malicioso con nombre similar a uno legítimo en un hub público", a: "Typosquatting en model hub" },
      { s: "Manifiesto que enumera datasets, dependencias y pesos para auditar la composición", a: "ML-BOM" },
      { s: "Formato de serialización seguro que solo almacena tensores sin código ejecutable", a: "Safetensors" },
    ],
    opts: ["Pickle deserialization RCE", "Model provenance", "Typosquatting en model hub", "ML-BOM", "Safetensors"],
  },
  {
    id: 71,
    lesson: 71,
    title: "Side-channels microarquitectónicos",
    items: [
      { s: "Ejecución especulativa que entrena el predictor de saltos para leer memoria cross-domain", a: "Spectre" },
      { s: "Lectura de memoria de kernel explotando ejecución fuera de orden antes del fault", a: "Meltdown" },
      { s: "Flips de bits en filas vecinas de DRAM por acceso repetido (hammering)", a: "Rowhammer" },
      { s: "Medir el tiempo de recarga de una línea de caché expulsada para inferir el acceso de la víctima", a: "Flush+Reload" },
      { s: "Fuga de datos en buffers internos de la CPU mediante carga especulativa (MDS)", a: "RIDL/Fallout" },
    ],
    opts: ["Spectre", "Meltdown", "Rowhammer", "Flush+Reload", "RIDL/Fallout"],
  },
  {
    id: 72,
    lesson: 72,
    title: "Inyección de fallos y ataques de hardware",
    items: [
      { s: "Introducir un pulso fuera de especificación en la alimentación para saltar una instrucción", a: "Voltage glitching" },
      { s: "Inducir fallos con un pulso de reloj demasiado corto que viola el timing del setup", a: "Clock glitching" },
      { s: "Correlacionar el consumo de potencia con bits de la clave usando análisis estadístico", a: "DPA" },
      { s: "Acceder al puerto de depuración del chip para volcar memoria o controlar la CPU", a: "JTAG debug" },
      { s: "Inyectar fallos puntuales mediante un disparo láser sobre el die descapsulado", a: "Laser fault injection" },
    ],
    opts: ["Voltage glitching", "Clock glitching", "DPA", "JTAG debug", "Laser fault injection"],
  },
  {
    id: 73,
    lesson: 73,
    title: "Firmware, UEFI y arranque seguro",
    items: [
      { s: "Memoria no volátil externa donde reside la imagen del firmware UEFI", a: "SPI flash" },
      { s: "Fase de UEFI donde se cargan la mayoría de drivers y se establece el entorno de boot", a: "DXE" },
      { s: "Verificación de firmas de cada componente del boot contra claves del fabricante", a: "Secure Boot" },
      { s: "Extender hashes de cada etapa en PCRs del TPM para attestation posterior", a: "Measured Boot" },
      { s: "Ancla de confianza inmutable grabada en ROM que valida la primera etapa", a: "Hardware Root of Trust" },
    ],
    opts: ["SPI flash", "DXE", "Secure Boot", "Measured Boot", "Hardware Root of Trust"],
  },
  {
    id: 74,
    lesson: 74,
    title: "Ejecución confiable y raíces de confianza",
    items: [
      { s: "Chip discreto que almacena claves y mantiene PCRs para measured boot", a: "TPM" },
      { s: "Enclave de Intel que aísla código y datos cifrados del resto del sistema, incluido el OS", a: "SGX" },
      { s: "Partición del SoC ARM en mundo seguro y mundo normal para aislar firmware crítico", a: "TrustZone" },
      { s: "Prueba criptográfica remota de que un enclave ejecuta el código esperado", a: "Remote attestation" },
      { s: "Clave única e inmutable por dispositivo, base de la cadena de derivación de claves", a: "Fused device key" },
    ],
    opts: ["TPM", "SGX", "TrustZone", "Remote attestation", "Fused device key"],
  },
  {
    id: 75,
    lesson: 75,
    title: "Reversing avanzado y anti-análisis",
    items: [
      { s: "Detectar la presencia de un depurador leyendo flags como BeingDebugged en el PEB", a: "Anti-debug" },
      { s: "Transformar el flujo de control en un autómata plano con un dispatcher central", a: "Control-flow flattening" },
      { s: "Descifrar el código real solo en tiempo de ejecución para ocultar el binario en disco", a: "Packing" },
      { s: "Reconstruir pseudocódigo C de alto nivel a partir del ensamblador en Ghidra/IDA", a: "Decompilation" },
      { s: "Insertar instrucciones inútiles que no alteran la semántica para confundir al analista", a: "Junk code insertion" },
    ],
    opts: ["Anti-debug", "Control-flow flattening", "Packing", "Decompilation", "Junk code insertion"],
  },
  {
    id: 76,
    lesson: 76,
    title: "Ejecución simbólica y concólica",
    items: [
      { s: "Representar entradas como variables lógicas y explorar rutas resolviendo restricciones", a: "Symbolic execution" },
      { s: "Combinar ejecución concreta y simbólica para guiar la exploración de caminos", a: "Concolic execution" },
      { s: "Crecimiento exponencial de rutas que satura el motor al ramificar en cada condición", a: "Path explosion" },
      { s: "Motor que decide la satisfacibilidad de las fórmulas de ruta (ej. Z3)", a: "SMT solver" },
      { s: "Framework binario de análisis simbólico para reversing y resolución de retos", a: "angr" },
    ],
    opts: ["Symbolic execution", "Concolic execution", "Path explosion", "SMT solver", "angr"],
  },
  {
    id: 77,
    lesson: 77,
    title: "Rootkits y bootkits de kernel",
    items: [
      { s: "Manipular directamente estructuras del kernel para desvincular un proceso de la lista activa", a: "DKOM" },
      { s: "Sobrescribir punteros de la tabla de servicios del sistema para interceptar syscalls", a: "SSDT hooking" },
      { s: "Infectar la etapa de arranque para cargarse antes del kernel y subvertir el OS", a: "Bootkit" },
      { s: "Reemplazar la dirección de retorno en una función del kernel para redirigir el flujo", a: "Inline hooking" },
      { s: "Inyectar un driver malicioso sin firmar abusando de un driver vulnerable legítimo", a: "BYOVD" },
    ],
    opts: ["DKOM", "SSDT hooking", "Bootkit", "Inline hooking", "BYOVD"],
  },
  {
    id: 78,
    lesson: 78,
    title: "Implants, C2 y evasión de EDR",
    items: [
      { s: "Parchear amsi.dll en memoria para que AmsiScanBuffer devuelva limpio siempre", a: "AMSI bypass" },
      { s: "Invocar syscalls del kernel directamente desde ensamblador para evitar hooks en ntdll", a: "Direct syscalls" },
      { s: "Implant que se comunica con su servidor a intervalos con jitter para mimetizar tráfico", a: "Beacon" },
      { s: "Reescribir la copia limpia de ntdll desde disco para eliminar los hooks del EDR en memoria", a: "Unhooking" },
      { s: "Asignar memoria ejecutable solo durante la ejecución del shellcode y luego cifrarla", a: "Sleep obfuscation" },
    ],
    opts: ["AMSI bypass", "Direct syscalls", "Beacon", "Unhooking", "Sleep obfuscation"],
  },
  {
    id: 79,
    lesson: 79,
    title: "Vulnerability research y fuzzing",
    items: [
      { s: "Fuzzer guiado por cobertura que usa instrumentación y mutación genética de inputs", a: "AFL" },
      { s: "Instrumentación que detecta accesos fuera de límites y use-after-free en tiempo de ejecución", a: "AddressSanitizer" },
      { s: "Fuzzing in-process basado en una función objetivo enlazada con la biblioteca", a: "libFuzzer" },
      { s: "Reducir un input que crashea hasta el conjunto mínimo de bytes que reproduce el fallo", a: "Test case minimization" },
      { s: "Conjunto inicial de entradas válidas que siembran la exploración del fuzzer", a: "Corpus/seed" },
    ],
    opts: ["AFL", "AddressSanitizer", "libFuzzer", "Test case minimization", "Corpus/seed"],
  },
  {
    id: 80,
    lesson: 80,
    title: "Threat intelligence y tracking de APTs",
    items: [
      { s: "Modelo de cuatro vértices: adversario, capacidad, infraestructura y víctima", a: "Diamond Model" },
      { s: "Atribuir actividad a un actor por correlación de TTPs, infraestructura y artefactos", a: "Attribution" },
      { s: "Pirámide que jerarquiza indicadores; los TTPs son los más costosos de cambiar", a: "Pyramid of Pain" },
      { s: "Marco que cataloga técnicas y tácticas adversarias observadas en el mundo real", a: "MITRE ATT&CK" },
      { s: "Secuencia de fases del ataque desde reconocimiento hasta acciones sobre objetivos", a: "Cyber Kill Chain" },
    ],
    opts: ["Diamond Model", "Attribution", "Pyramid of Pain", "MITRE ATT&CK", "Cyber Kill Chain"],
  },
  {
    id: 81,
    lesson: 81,
    title: "Metodología de security research y disclosure",
    items: [
      { s: "Reportar la falla al proveedor en privado y publicar tras un plazo acordado de arreglo", a: "Coordinated disclosure" },
      { s: "Identificador único asignado a una vulnerabilidad pública para su seguimiento", a: "CVE" },
      { s: "Código mínimo que demuestra de forma reproducible la explotabilidad del bug", a: "Proof of Concept" },
      { s: "Sistema que puntúa la severidad de una vulnerabilidad con métricas estandarizadas", a: "CVSS" },
      { s: "Publicar los detalles sin previo aviso al proveedor, dejando a los usuarios expuestos", a: "Full disclosure" },
    ],
    opts: ["Coordinated disclosure", "CVE", "Proof of Concept", "CVSS", "Full disclosure"],
  },
  {
    id: 82,
    lesson: 82,
    title: "Métodos formales y verificación",
    items: [
      { s: "Explorar exhaustivamente los estados de un sistema para verificar propiedades temporales", a: "Model checking" },
      { s: "Lenguaje de especificación de sistemas concurrentes y distribuidos con su checker TLC", a: "TLA+" },
      { s: "Microkernel con prueba formal de corrección funcional respecto a su especificación", a: "seL4" },
      { s: "Demostrar manualmente teoremas sobre el programa con asistente de pruebas (Coq/Isabelle)", a: "Theorem proving" },
      { s: "Propiedad que afirma que algo malo nunca ocurre durante la ejecución", a: "Safety property" },
    ],
    opts: ["Model checking", "TLA+", "seL4", "Theorem proving", "Safety property"],
  },
  {
    id: 83,
    lesson: 83,
    title: "Identifica el control, factor o ataque de auth",
    items: [
      { s: "Exigir app autenticadora además de contraseña", a: "MFA" },
      { s: "Un login para Gmail, Slack y Jira", a: "SSO" },
      { s: "Bóveda con rotación para la cuenta de admin de dominio", a: "PAM" },
      { s: "Permisos según el rol 'Contabilidad'", a: "RBAC" },
      { s: "Revisar trimestralmente quién tiene acceso a qué", a: "Recertificación" },
      { s: "Huella dactilar o reconocimiento facial", a: "Factor de inherencia" },
      { s: "Credencial de clave asimétrica ligada al dominio, sin secreto compartido", a: "Passkey / FIDO2" },
      { s: "Bombardear al usuario con notificaciones push hasta que acepte una", a: "MFA fatigue" },
      { s: "Evaluar dispositivo, red y comportamiento para pedir factor extra solo cuando el riesgo sube", a: "Autenticación adaptativa" },
      { s: "Proxy que replica el sitio real y roba credenciales + token de sesión post-MFA (evilginx)", a: "AiTM phishing" },
    ],
    opts: ["MFA", "SSO", "PAM", "RBAC", "Recertificación", "Factor de inherencia", "Passkey / FIDO2", "MFA fatigue", "Autenticación adaptativa", "AiTM phishing"],
  },
  {
    id: 84,
    lesson: 84,
    title: "Empareja el principio de diseño",
    items: [
      { s: "Por defecto, denegar el acceso", a: "Menor privilegio" },
      { s: "Capas redundantes de control", a: "Defensa en profundidad" },
      { s: "Ante un fallo, quedar denegando", a: "Fail-secure" },
      { s: "No confiar en el secreto del diseño", a: "Diseño abierto" },
      { s: "Verificar cada acceso sin atajos", a: "Mediación completa" },
    ],
    opts: ["Menor privilegio", "Defensa en profundidad", "Fail-secure", "Diseño abierto", "Mediación completa"],
  },
  {
    id: 85,
    lesson: 85,
    title: "Clasifica el tratamiento del riesgo",
    items: [
      { s: "Instalar un WAF para reducir ataques web", a: "Mitigar" },
      { s: "Contratar un ciberseguro", a: "Transferir" },
      { s: "Cancelar un servicio demasiado riesgoso", a: "Evitar" },
      { s: "Asumir un riesgo bajo, documentado y aprobado", a: "Aceptar" },
      { s: "Externalizar el pago con tarjeta a una pasarela certificada", a: "Transferir" },
    ],
    opts: ["Mitigar", "Transferir", "Evitar", "Aceptar"],
  },
  {
    id: 86,
    lesson: 86,
    title: "Asocia la norma con su ámbito",
    items: [
      { s: "Datos personales en la Unión Europea", a: "RGPD" },
      { s: "Datos de tarjetas de pago", a: "PCI-DSS" },
      { s: "Datos de salud en EE.UU.", a: "HIPAA" },
      { s: "Controles en proveedores SaaS (Type II)", a: "SOC 2" },
      { s: "Sector público español", a: "ENS" },
      { s: "SGSI certificable", a: "ISO 27001" },
    ],
    opts: ["RGPD", "PCI-DSS", "HIPAA", "SOC 2", "ENS", "ISO 27001"],
  },
];

export function getPractice(id: number): PracticeExercise | undefined {
  return PRACTICE.find((p) => p.id === id);
}
