import type { PracticeExercise } from "./types";

// Matching exercises. The user drags/clicks each `s` (statement) onto one of `opts` (answers).
export const PRACTICE: PracticeExercise[] = [
  {
    id: 1,
    lesson: 1,
    title: "Ramas de CyberSec",
    items: [
      { s: "Simular ataques", a: "Red Team" },
      { s: "Monitorear amenazas", a: "Blue Team" },
      { s: "Investigar post-incidente", a: "Forense Digital" },
      { s: "Compliance y riesgos", a: "GRC" },
      { s: "Seguridad en desarrollo", a: "DevSecOps" },
    ],
    opts: ["Red Team", "Blue Team", "Forense Digital", "GRC", "DevSecOps"],
  },
  {
    id: 2,
    lesson: 2,
    title: "Clasifica por CIA",
    items: [
      { s: "Hacker lee emails sin cifrar", a: "Confidencialidad" },
      { s: "Ransomware cifra archivos", a: "Disponibilidad" },
      { s: "Modifican notas en la DB", a: "Integridad" },
      { s: "DDoS tumba la web", a: "Disponibilidad" },
      { s: "Virus corrompe backups", a: "Integridad" },
    ],
    opts: ["Confidencialidad", "Integridad", "Disponibilidad"],
  },
  {
    id: 3,
    lesson: 3,
    title: "Identifica el Malware",
    items: [
      { s: "Se adjunta a PDF, necesita click", a: "Virus" },
      { s: "Se propaga solo por la red", a: "Gusano" },
      { s: "Parece un juego legítimo", a: "Troyano" },
      { s: "Cifra archivos y pide Bitcoin", a: "Ransomware" },
      { s: "Se oculta a nivel del kernel", a: "Rootkit" },
    ],
    opts: ["Virus", "Gusano", "Troyano", "Ransomware", "Rootkit"],
  },
  {
    id: 4,
    lesson: 5,
    title: "Capas OSI y Ataques",
    items: [
      { s: "SQL Injection", a: "Capa 7" },
      { s: "SYN Flood", a: "Capa 4" },
      { s: "ARP Poisoning", a: "Capa 2" },
      { s: "IP Spoofing", a: "Capa 3" },
      { s: "Wiretapping", a: "Capa 1" },
    ],
    opts: ["Capa 1", "Capa 2", "Capa 3", "Capa 4", "Capa 7"],
  },
  {
    id: 5,
    lesson: 6,
    title: "Protocolos → Puertos",
    items: [
      { s: "SSH", a: "22" },
      { s: "HTTP", a: "80" },
      { s: "HTTPS", a: "443" },
      { s: "DNS", a: "53" },
      { s: "FTP", a: "21" },
      { s: "SMB", a: "445" },
      { s: "RDP", a: "3389" },
    ],
    opts: ["21", "22", "53", "80", "443", "445", "3389"],
  },
  {
    id: 6,
    lesson: 9,
    title: "Python: Librería → Uso",
    items: [
      { s: "Manipular paquetes de red", a: "scapy" },
      { s: "HTTP requests", a: "requests" },
      { s: "Protocolos Windows", a: "impacket" },
      { s: "Cifrado", a: "pycryptodome" },
      { s: "Forense de memoria", a: "volatility3" },
    ],
    opts: ["scapy", "requests", "impacket", "pycryptodome", "volatility3"],
  },
  {
    id: 7,
    lesson: 11,
    title: "SQL: Tipo de Ataque",
    items: [
      { s: "' OR 1=1 --", a: "Basic SQLi" },
      { s: "' UNION SELECT ...", a: "UNION-based" },
      { s: "' AND IF(1=1,SLEEP(5),0)", a: "Time-based blind" },
      { s: "' AND SUBSTRING(...)='a'", a: "Boolean blind" },
    ],
    opts: ["Basic SQLi", "UNION-based", "Time-based blind", "Boolean blind"],
  },
  {
    id: 8,
    lesson: 14,
    title: "Linux: Comando → Función",
    items: [
      { s: "ss -tulpn", a: "Puertos en escucha" },
      { s: "find / -perm -4000", a: "Buscar binarios SUID" },
      { s: "cat /etc/shadow", a: "Hashes de passwords" },
      { s: "tail -f auth.log", a: "Logs en vivo" },
      { s: "chmod 600", a: "Solo dueño rw" },
    ],
    opts: ["Puertos en escucha", "Buscar binarios SUID", "Hashes de passwords", "Logs en vivo", "Solo dueño rw"],
  },
  {
    id: 9,
    lesson: 18,
    title: "Ataques a Active Directory",
    items: [
      { s: "Crackear cuentas de servicio (SPN)", a: "Kerberoasting" },
      { s: "Replicar hashes simulando un DC", a: "DCSync" },
      { s: "Forjar TGTs con el hash de krbtgt", a: "Golden Ticket" },
      { s: "Autenticar con el hash NTLM", a: "Pass-the-Hash" },
      { s: "Cuentas sin preauth Kerberos", a: "AS-REP Roasting" },
    ],
    opts: ["Kerberoasting", "DCSync", "Golden Ticket", "Pass-the-Hash", "AS-REP Roasting"],
  },
  {
    id: 10,
    lesson: 20,
    title: "Conceptos de Criptografía",
    items: [
      { s: "Cifra y autentica (AEAD)", a: "AES-GCM" },
      { s: "Inseguro: revela patrones", a: "ECB" },
      { s: "Asimétrico por factorización", a: "RSA" },
      { s: "Hash de passwords lento", a: "Argon2" },
      { s: "Intercambio de clave compartida", a: "Diffie-Hellman" },
    ],
    opts: ["AES-GCM", "ECB", "RSA", "Argon2", "Diffie-Hellman"],
  },
  {
    id: 11,
    lesson: 25,
    title: "OWASP Top 10 → Categoría",
    items: [
      { s: "Cambiar /user/1 por /user/2", a: "Broken Access Control" },
      { s: "Bucket S3 público / defaults", a: "Security Misconfiguration" },
      { s: "' OR 1=1 --", a: "Injection" },
      { s: "Log4Shell (Log4j)", a: "Vulnerable Components" },
      { s: "Leer 169.254.169.254", a: "SSRF" },
    ],
    opts: ["Broken Access Control", "Security Misconfiguration", "Injection", "Vulnerable Components", "SSRF"],
  },
  {
    id: 12,
    lesson: 29,
    title: "Herramienta OSINT → Uso",
    items: [
      { s: "Dispositivos expuestos en Internet", a: "Shodan" },
      { s: "Emails y subdominios", a: "theHarvester" },
      { s: "Enumeración de subdominios", a: "amass" },
      { s: "Visualizar relaciones", a: "Maltego" },
      { s: "Datos de registro de dominio", a: "whois" },
    ],
    opts: ["Shodan", "theHarvester", "amass", "Maltego", "whois"],
  },
  {
    id: 13,
    lesson: 30,
    title: "Flag de Nmap → Acción",
    items: [
      { s: "Ping sweep (hosts vivos)", a: "-sn" },
      { s: "Versión de servicios", a: "-sV" },
      { s: "Detección de sistema operativo", a: "-O" },
      { s: "Todos los 65535 puertos", a: "-p-" },
      { s: "Decoys para evadir IDS", a: "-D RND:10" },
    ],
    opts: ["-sn", "-sV", "-O", "-p-", "-D RND:10"],
  },
  {
    id: 14,
    lesson: 44,
    title: "Plugin de Volatility → Qué extrae",
    items: [
      { s: "Lista de procesos", a: "pslist" },
      { s: "Conexiones de red", a: "netscan" },
      { s: "Código inyectado", a: "malfind" },
      { s: "Argumentos de proceso", a: "cmdline" },
      { s: "Hashes de cuentas", a: "hashdump" },
    ],
    opts: ["pslist", "netscan", "malfind", "cmdline", "hashdump"],
  },
  {
    id: 15,
    lesson: 49,
    title: "Servicio AWS → Función",
    items: [
      { s: "Identidad y permisos", a: "IAM" },
      { s: "Almacenamiento de objetos", a: "S3" },
      { s: "Auditoría de llamadas a la API", a: "CloudTrail" },
      { s: "Detección de amenazas", a: "GuardDuty" },
      { s: "Red virtual aislada", a: "VPC" },
    ],
    opts: ["IAM", "S3", "CloudTrail", "GuardDuty", "VPC"],
  },
];

export function getPractice(id: number): PracticeExercise | undefined {
  return PRACTICE.find((p) => p.id === id);
}
