import type { QuizQuestion } from "./types";

// Quizzes keyed by lesson id. Each one is short (4-5 questions) so users can
// finish in a couple minutes. `c` is the index of the correct option in `o`.
export const QUIZZES: Record<number, QuizQuestion[]> = {
  1: [
    { q: "La ciberseguridad combina:", o: ["HW, SW, Cloud", "Tecnología, Procesos, Personas", "Ataque, Defensa, Análisis"], c: 1, e: "Tecnología + Procesos + Personas." },
    { q: "¿Qué equipo simula ataques?", o: ["Blue Team", "Red Team", "SOC"], c: 1, e: "Red Team = ofensivo." },
    { q: "En el Cyber Kill Chain, ¿qué fase es enviar el exploit?", o: ["Reconnaissance", "Delivery", "Exploitation"], c: 1, e: "Delivery = entregar el payload al objetivo." },
    { q: "WannaCry afectó:", o: ["10K equipos", "230K+ en 150 países", "1M en 50 países"], c: 1, e: "230K+ en 150 países." },
    { q: "DevSecOps integra seguridad en:", o: ["Redes", "Desarrollo de software", "Hardware"], c: 1, e: "DevSecOps = Security en Dev + Ops." },
  ],
  2: [
    { q: "Tríada CIA:", o: ["Cifrado, Internet, Auth", "Confidencialidad, Integridad, Disponibilidad", "Control, Inspección, Análisis"], c: 1, e: "CIA." },
    { q: "DDoS viola:", o: ["Confidencialidad", "Integridad", "Disponibilidad"], c: 2, e: "Impide acceso = disponibilidad." },
    { q: "Zero Trust significa:", o: ["Confiar en red interna", "Never trust, always verify", "Solo confiar en admins"], c: 1, e: "Verificar todo, confiar en nada." },
    { q: "MFA combina:", o: ["Dos contraseñas", "2+ tipos de verificación", "Antivirus + firewall"], c: 1, e: "Factores diferentes." },
    { q: "Menor privilegio:", o: ["Admin para todos", "Solo permisos mínimos necesarios", "Rotar permisos diario"], c: 1, e: "Mínimos permisos." },
  ],
  3: [
    { q: "Gusano vs virus:", o: ["Iguales", "Gusano se propaga solo", "Virus se propaga solo"], c: 1, e: "Gusano no necesita interacción." },
    { q: "APT de Corea del Norte:", o: ["APT28", "APT41", "Lazarus Group"], c: 2, e: "Lazarus = NK." },
    { q: "MITRE ATT&CK cataloga:", o: ["Certificaciones", "TTPs de atacantes", "Vulnerabilidades"], c: 1, e: "Framework de tácticas y técnicas." },
    { q: "Rootkit se caracteriza por:", o: ["Cifrar archivos", "Ocultarse profundamente", "Registrar teclas"], c: 1, e: "Extremadamente difícil de detectar." },
    { q: "RaaS significa:", o: ["Recovery as a Service", "Ransomware as a Service", "Risk as a Service"], c: 1, e: "Modelo de negocio criminal." },
  ],
  4: [
    { q: "Funciones NIST CSF:", o: ["Atacar, Defender, Reportar, Parchear, Auditar", "Identificar, Proteger, Detectar, Responder, Recuperar", "Planear, Ejecutar, Verificar, Actuar, Mejorar"], c: 1, e: "NIST: ID, PR, DE, RS, RC." },
    { q: "Certificación inicial recomendada:", o: ["OSCP", "Security+", "CISSP"], c: 1, e: "Security+ = puerta de entrada." },
    { q: "ISO 27001 define:", o: ["Top 10 web vulns", "SGSI", "Reglas de tarjetas"], c: 1, e: "Sistema de Gestión de SI." },
    { q: "PCI-DSS es para:", o: ["Cloud", "Tarjetas de crédito", "Salud"], c: 1, e: "Payment Card Industry." },
  ],
  5: [
    { q: "OSI tiene:", o: ["4", "5", "7"], c: 2, e: "7 capas." },
    { q: "HTTP opera en capa:", o: ["3", "4", "7"], c: 2, e: "Capa 7 (Aplicación)." },
    { q: "ARP Poisoning ataca capa:", o: ["1", "2", "4"], c: 1, e: "Capa 2 (Enlace)." },
    { q: "SYN Flood ataca capa:", o: ["2", "4", "7"], c: 1, e: "Capa 4 (Transporte)." },
  ],
  6: [
    { q: "TCP vs UDP:", o: ["TCP es más rápido", "UDP garantiza entrega", "TCP garantiza entrega, UDP no"], c: 2, e: "TCP = fiable con handshake." },
    { q: "Puerto 443:", o: ["HTTP", "SSH", "HTTPS"], c: 2, e: "443 = HTTPS." },
    { q: "DNS usa puerto:", o: ["22", "53", "80"], c: 1, e: "DNS = 53." },
    { q: "SMB puerto 445 fue explotado por:", o: ["Heartbleed", "WannaCry", "Log4Shell"], c: 1, e: "EternalBlue → SMBv1." },
  ],
  7: [
    { q: "192.168.1.1 es IP:", o: ["Pública", "Privada", "Localhost"], c: 1, e: "192.168.x.x = privada." },
    { q: "/24 = hosts usables:", o: ["24", "128", "254"], c: 2, e: "2^8 - 2 = 254." },
    { q: "NAT traduce:", o: ["DNS→IP", "IP privada→pública", "MAC→IP"], c: 1, e: "Privada a pública." },
  ],
  8: [
    { q: "Wireshark captura:", o: ["Contraseñas", "Paquetes de red", "Malware"], c: 1, e: "Analizador de protocolos." },
    { q: "Filtro para solo HTTP:", o: ["port 80", "http", "filter:http"], c: 1, e: "Display filter: http" },
    { q: "tcpdump se usa en:", o: ["Windows GUI", "CLI Linux", "Navegador"], c: 1, e: "Línea de comandos." },
  ],
  9: [
    { q: "Python es popular en ciberseg por:", o: ["Es el más rápido", "Simplicidad y enormes librerías", "Solo sirve para web"], c: 1, e: "Sintaxis simple + ecosistema enorme." },
    { q: "Scapy sirve para:", o: ["Cifrar archivos", "Manipular paquetes de red", "Crear GUIs"], c: 1, e: "Packet crafting y sniffing." },
    { q: "¿Qué librería se usa para protocolos Windows?", o: ["requests", "impacket", "beautifulsoup"], c: 1, e: "Impacket = SMB, NTLM, Kerberos." },
  ],
  10: [
    { q: "XSS permite inyectar:", o: ["SQL en bases de datos", "JavaScript en páginas web", "Binarios en servidores"], c: 1, e: "Cross-Site Scripting = JS injection." },
    { q: "document.cookie permite:", o: ["Borrar cookies", "Leer cookies del navegador", "Crear cookies seguras"], c: 1, e: "Accede a las cookies." },
    { q: "CSP header sirve para:", o: ["Cifrar tráfico", "Controlar qué scripts pueden ejecutarse", "Bloquear SQL injection"], c: 1, e: "Content Security Policy." },
  ],
  11: [
    { q: "SQL Injection básico:", o: ["<script>alert(1)</script>", "' OR 1=1 --", "sudo rm -rf /"], c: 1, e: "Tautología SQL clásica." },
    { q: "Prepared statements previenen:", o: ["XSS", "SQL Injection", "DDoS"], c: 1, e: "Separan datos de código SQL." },
    { q: "Blind SQLi usa:", o: ["Mensajes de error visibles", "Respuestas true/false o tiempo", "Archivos del servidor"], c: 1, e: "Boolean o time-based inference." },
  ],
  12: [
    { q: "Buffer overflow sobrescribe:", o: ["El disco duro", "La return address en el stack", "La RAM completa"], c: 1, e: "Sobrescribe EIP/RIP para redirigir ejecución." },
    { q: "ASLR protege contra:", o: ["XSS", "Predicción de direcciones de memoria", "SQL Injection"], c: 1, e: "Randomiza layout de memoria." },
    { q: "La mayoría de malware está escrito en:", o: ["Python", "JavaScript", "C/C++"], c: 2, e: "C/C++ = bajo nivel, acceso a memoria." },
  ],
  13: [
    { q: "¿Qué estándar WiFi usa SAE (Dragonfly)?", o: ["WEP", "WPA2", "WPA3"], c: 2, e: "WPA3 reemplaza el PSK handshake por SAE." },
    { q: "Un ataque de deauth sirve para:", o: ["Crackear el password directo", "Tirar clientes y forzar reconexión", "Clonar la MAC del router"], c: 1, e: "Los frames de deauth no están cifrados en WPA2." },
    { q: "Evil Twin es:", o: ["Un AP falso con el mismo SSID", "Un virus de router", "Un tipo de cifrado"], c: 0, e: "Suplanta la red legítima para capturar credenciales." },
    { q: "KRACK (2017) atacó:", o: ["WEP", "El 4-way handshake de WPA2", "WPS"], c: 1, e: "Key Reinstallation Attack reinstala una clave usada." },
  ],
  14: [
    { q: "¿Dónde están los hashes de contraseñas en Linux?", o: ["/etc/passwd", "/etc/shadow", "/var/log/auth.log"], c: 1, e: "/etc/shadow (solo root) guarda los hashes." },
    { q: "tail -f se usa para:", o: ["Borrar logs", "Ver logs en tiempo real", "Cifrar archivos"], c: 1, e: "Sigue el archivo a medida que crece." },
    { q: "¿Qué distro trae 600+ herramientas de pentesting?", o: ["Ubuntu Server", "Kali Linux", "Tails"], c: 1, e: "Kali está orientada a seguridad ofensiva." },
    { q: "ss -tulpn o netstat -tulpn muestra:", o: ["Usuarios logueados", "Puertos y conexiones de red", "Permisos de archivos"], c: 1, e: "Sockets/puertos en escucha y conexiones." },
  ],
  15: [
    { q: "El shebang #!/bin/bash indica:", o: ["Un comentario", "El intérprete del script", "Una variable"], c: 1, e: "Define qué programa ejecuta el script." },
    { q: "Para extraer la primera columna de /etc/passwd (separada por :) usás:", o: ["grep", "awk -F:", "sed"], c: 1, e: "awk con field separator ':'." },
    { q: "Para contar logins fallidos: grep 'Failed password' auth.log | ___", o: ["wc -l", "rm -f", "chmod 777"], c: 0, e: "wc -l cuenta las líneas coincidentes." },
    { q: "for i in $(seq 1 254) sirve típicamente para:", o: ["Un ping sweep", "Cifrar un disco", "Crear usuarios"], c: 0, e: "Itera la última octeto para barrer una /24." },
  ],
  16: [
    { q: "chmod 600 da permisos:", o: ["rwxr-xr-x", "rw------- (solo dueño)", "rwxrwxrwx"], c: 1, e: "6=rw para dueño, 0 para grupo y otros." },
    { q: "El bit SUID hace que el binario corra como:", o: ["El usuario que lo ejecuta", "El dueño del archivo", "root siempre"], c: 1, e: "Con permisos del dueño → riesgo de escalada si es root." },
    { q: "Para encontrar binarios SUID:", o: ["find / -perm -4000 -type f", "ls -la /etc", "chmod -R 777 /"], c: 0, e: "Busca el bit SUID (4000)." },
    { q: "SELinux y AppArmor implementan:", o: ["Cifrado de disco", "Control de acceso obligatorio (MAC)", "Un firewall"], c: 1, e: "Confinan procesos aunque sean comprometidos." },
  ],
  17: [
    { q: "El Event ID 4625 en Windows registra:", o: ["Logon exitoso", "Logon fallido", "Servicio nuevo"], c: 1, e: "4625 = fallo de autenticación (brute force)." },
    { q: "El Event ID 7045 suele indicar:", o: ["Cambio de password", "Instalación de un servicio nuevo", "Apagado del sistema"], c: 1, e: "Usado por PsExec y malware para persistencia." },
    { q: "AMSI sirve para:", o: ["Cifrar el disco", "Inspeccionar scripts en memoria antes de ejecutar", "Gestionar usuarios"], c: 1, e: "Antimalware Scan Interface; los atacantes intentan bypassearlo." },
    { q: "Las claves de registro Run/RunOnce se usan comúnmente para:", o: ["Persistencia de malware", "Cifrado", "Backups"], c: 0, e: "Ejecutan programas al inicio de sesión." },
  ],
  18: [
    { q: "El servidor que aloja Active Directory se llama:", o: ["Domain Controller", "Proxy", "Bastion"], c: 0, e: "DC = Domain Controller." },
    { q: "Kerberoasting explota:", o: ["Cuentas de servicio con SPN", "Puertos abiertos", "Contraseñas en texto plano"], c: 0, e: "Pedís el TGS y crackeás el hash offline." },
    { q: "Un Golden Ticket se forja con el hash de:", o: ["Administrator", "krbtgt", "El usuario víctima"], c: 1, e: "Con krbtgt forjás TGTs válidos para cualquiera." },
    { q: "DCSync abusa de:", o: ["La replicación entre Domain Controllers", "Un buffer overflow", "DNS"], c: 0, e: "Simula ser un DC para pedir hashes." },
  ],
  19: [
    { q: "Los cmdlets de PowerShell siguen el patrón:", o: ["Sustantivo-Verbo", "Verbo-Sustantivo", "solo-minúsculas"], c: 1, e: "Get-Process, Set-Item, etc." },
    { q: "El pipeline de PowerShell pasa:", o: ["Texto plano", "Objetos", "Bytes"], c: 1, e: "A diferencia de bash, pasa objetos .NET." },
    { q: "Script Block Logging (Event ID 4104) sirve para:", o: ["Acelerar scripts", "Auditar el código PowerShell ejecutado", "Cifrar scripts"], c: 1, e: "Clave para detectar PowerShell ofensivo." },
    { q: "IEX (New-Object Net.WebClient).DownloadString(...) suele indicar:", o: ["Una actualización normal", "Descarga y ejecución en memoria (sospechoso)", "Un backup"], c: 1, e: "Técnica fileless común en ataques." },
  ],
  20: [
    { q: "La criptografía simétrica usa:", o: ["Dos claves (pública y privada)", "La misma clave para cifrar y descifrar", "Ninguna clave"], c: 1, e: "Misma clave; rápida pero hay que distribuirla con cuidado." },
    { q: "¿Por qué ECB es inseguro?", o: ["Es muy lento", "Bloques iguales producen cifrado igual (revela patrones)", "No usa clave"], c: 1, e: "El 'pingüino cifrado' sigue visible." },
    { q: "¿Qué modo cifra Y autentica (AEAD)?", o: ["ECB", "CBC", "GCM"], c: 2, e: "GCM detecta manipulación además de cifrar." },
    { q: "Reutilizar un nonce/IV con la misma clave:", o: ["Mejora el rendimiento", "Rompe la seguridad de GCM/CTR", "No tiene efecto"], c: 1, e: "Nunca repitas nonce con la misma clave." },
  ],
  21: [
    { q: "En cifrado asimétrico, cifrás con la clave ___ y descifrás con la ___:", o: ["privada / pública", "pública / privada", "misma / misma"], c: 1, e: "Pública cifra, privada descifra." },
    { q: "ECC ofrece, frente a RSA:", o: ["Misma seguridad con claves más cortas", "Menos seguridad", "Solo sirve para firmas"], c: 0, e: "ECC 256 ≈ RSA 3072." },
    { q: "Diffie-Hellman sirve para:", o: ["Hashear passwords", "Acordar una clave compartida sobre canal público", "Firmar binarios"], c: 1, e: "Key exchange; ECDHE da forward secrecy." },
    { q: "El algoritmo de Shor (cuántico) amenaza a:", o: ["AES-256", "RSA y ECC", "SHA-3"], c: 1, e: "Por eso NIST estandarizó PQC (Kyber/Dilithium)." },
  ],
  22: [
    { q: "Una función hash es:", o: ["Reversible con la clave", "Unidireccional", "Un cifrado simétrico"], c: 1, e: "No se revierte; determinista." },
    { q: "El salt en password hashing sirve para:", o: ["Acelerar el login", "Frustrar rainbow tables y hashes iguales", "Cifrar la DB"], c: 1, e: "Valor único por usuario." },
    { q: "¿Cuál es el algoritmo recomendado hoy para passwords?", o: ["MD5", "SHA-256 simple", "Argon2"], c: 2, e: "Argon2 (o bcrypt/scrypt): lentos a propósito." },
    { q: "En PKI, ¿quién emite y firma certificados?", o: ["El navegador", "La Certificate Authority (CA)", "El servidor DNS"], c: 1, e: "Cadena de confianza CA raíz → intermedia → sitio." },
  ],
  23: [
    { q: "HTTPS es:", o: ["HTTP sobre TLS", "Un firewall", "Un tipo de VPN"], c: 0, e: "TLS cifra la comunicación HTTP." },
    { q: "TLS 1.3 frente a 1.2:", o: ["Es más lento e inseguro", "Más rápido y exige forward secrecy", "Es idéntico"], c: 1, e: "Eliminó ciphers inseguros, 1-RTT." },
    { q: "HSTS previene:", o: ["SQL Injection", "SSL stripping (degradar a HTTP)", "Buffer overflow"], c: 1, e: "Fuerza HTTPS en el navegador." },
    { q: "WireGuard se caracteriza por:", o: ["Ser viejo y pesado", "Código mínimo y criptografía moderna fija", "No cifrar"], c: 1, e: "VPN moderna (ChaCha20, Curve25519)." },
  ],
  24: [
    { q: "HTTP es:", o: ["Stateful por defecto", "Stateless (estado vía cookies/tokens)", "Cifrado por defecto"], c: 1, e: "Cada request es independiente." },
    { q: "¿Qué header frena principalmente el XSS?", o: ["Content-Security-Policy", "X-Frame-Options", "Referrer-Policy"], c: 0, e: "CSP controla qué scripts/recursos cargan." },
    { q: "La cookie con flag HttpOnly:", o: ["Solo viaja por HTTP no HTTPS", "No es accesible desde JavaScript", "Expira en 1 hora"], c: 1, e: "Mitiga el robo de cookies vía XSS." },
    { q: "Same-Origin Policy:", o: ["Permite leer cualquier origen", "Restringe el acceso entre orígenes distintos", "Es un cifrado"], c: 1, e: "CORS la relaja de forma controlada." },
  ],
  25: [
    { q: "El #1 actual de OWASP Top 10 es:", o: ["Injection", "Broken Access Control", "SSRF"], c: 1, e: "A01 — control de acceso roto." },
    { q: "IDOR es un ejemplo de:", o: ["Broken Access Control", "Cryptographic Failures", "Misconfiguration"], c: 0, e: "Acceder a objetos ajenos cambiando el ID." },
    { q: "Insecure Design (A04) se corrige:", o: ["Con un parche puntual", "Repensando el diseño / threat modeling", "Reiniciando el servidor"], c: 1, e: "Es una falla de diseño, no de implementación." },
    { q: "Un bucket S3 público es un caso de:", o: ["Injection", "Security Misconfiguration", "Auth Failure"], c: 1, e: "A05 — mala configuración." },
  ],
  26: [
    { q: "Log4Shell es un ejemplo de:", o: ["SSRF", "Vulnerable and Outdated Components", "CSRF"], c: 1, e: "A06 — componente vulnerable (Log4j)." },
    { q: "Falta de logs y alertas corresponde a:", o: ["A09 Logging & Monitoring Failures", "A03 Injection", "A01 Access Control"], c: 0, e: "Los ataques pasan desapercibidos." },
    { q: "Leer http://169.254.169.254 desde el servidor es típico de:", o: ["XSS", "SSRF (A10)", "CSRF"], c: 1, e: "Metadata cloud; caso Capital One." },
    { q: "Deserialización insegura cae bajo:", o: ["A08 Integrity Failures", "A02 Crypto Failures", "A07 Auth"], c: 0, e: "Confiar en datos sin verificar integridad." },
  ],
  27: [
    { q: "' OR 1=1 -- es un payload de:", o: ["XSS", "SQL Injection", "CSRF"], c: 1, e: "Tautología que evade el WHERE." },
    { q: "La defensa principal contra SQLi es:", o: ["Un WAF", "Prepared statements / consultas parametrizadas", "Renombrar tablas"], c: 1, e: "Separan datos de código SQL." },
    { q: "<img src=x onerror=alert(document.cookie)> es:", o: ["SQLi", "Stored XSS", "SSRF"], c: 1, e: "Inyecta JS que roba cookies." },
    { q: "HttpOnly + CSP + output encoding mitigan:", o: ["SQLi", "XSS", "Buffer overflow"], c: 1, e: "Defensa en capas contra XSS." },
  ],
  28: [
    { q: "CSRF funciona porque el navegador:", o: ["Ejecuta SQL", "Adjunta las cookies automáticamente", "Ignora HTTPS"], c: 1, e: "La sesión de la víctima se reutiliza." },
    { q: "El flag de cookie que mitiga CSRF es:", o: ["HttpOnly", "SameSite", "Secure"], c: 1, e: "SameSite=Lax/Strict limita envío cross-site." },
    { q: "IDOR se previene:", o: ["Ocultando el ID en el cliente", "Verificando autorización por objeto en el servidor", "Usando HTTPS"], c: 1, e: "En AlphaLog lo cubre RLS de Supabase." },
    { q: "Validar uploads por extensión (.jpg) en vez de contenido:", o: ["Es suficiente", "Es bypasseable (shell.php.jpg, magic bytes)", "Mejora el rendimiento"], c: 1, e: "Validá por contenido real, no por nombre." },
  ],
  29: [
    { q: "El reconocimiento pasivo se caracteriza por:", o: ["Escanear puertos del objetivo", "No tocar al objetivo (solo fuentes públicas)", "Explotar vulnerabilidades"], c: 1, e: "OSINT; es indetectable." },
    { q: "Shodan es:", o: ["Un antivirus", "Un buscador de dispositivos/servicios expuestos en Internet", "Un cifrador"], c: 1, e: "Mapea la superficie expuesta." },
    { q: "site:ejemplo.com filetype:pdf es un ejemplo de:", o: ["SQL Injection", "Google Dorking", "Un payload XSS"], c: 1, e: "Operadores de búsqueda para recon." },
    { q: "theHarvester sirve para obtener:", o: ["Hashes de passwords", "Emails, subdominios y hosts", "Exploits"], c: 1, e: "Recolección OSINT." },
  ],
  30: [
    { q: "nmap -sn realiza:", o: ["UDP scan", "Ping sweep (qué hosts están vivos)", "OS detection"], c: 1, e: "Descubrimiento de hosts." },
    { q: "Para detectar la versión de los servicios usás:", o: ["-sV", "-sn", "-f"], c: 0, e: "Clave para luego buscar CVEs." },
    { q: "El SYN scan (-sS) es:", o: ["El más ruidoso", "Sigiloso (half-open), requiere root", "Solo para UDP"], c: 1, e: "No completa el handshake." },
    { q: "-D RND:10 en Nmap agrega:", o: ["10 puertos", "Decoys (IPs señuelo) para evadir IDS", "10 segundos de delay"], c: 1, e: "Técnica de evasión." },
  ],
  31: [
    { q: "snmpwalk con community 'public' suele:", o: ["Estar siempre bloqueado", "Exponer mucha información del dispositivo", "Cifrar el tráfico"], c: 1, e: "SNMP mal configurado filtra datos." },
    { q: "dig axfr intenta:", o: ["Un ping", "Una transferencia de zona DNS", "Un brute force"], c: 1, e: "Zone transfer revela registros DNS internos." },
    { q: "enum4linux se usa para enumerar:", o: ["Servidores web", "SMB/Windows (usuarios, shares)", "Bases de datos SQL"], c: 1, e: "Enumeración de Samba/Windows." },
    { q: "El dicho del pentester sobre enumeración es:", o: ["'menos es más'", "'enumeration is key'", "'shoot first'"], c: 1, e: "Cuanto más enumerás, más vectores hallás." },
  ],
  32: [
    { q: "Un vulnerability scanner como Nessus:", o: ["Explota automáticamente todo", "Correlaciona servicios/versiones con CVEs", "Cifra la red"], c: 1, e: "Detecta, no necesariamente explota." },
    { q: "CVSS mide:", o: ["El precio de un exploit", "La severidad de una vulnerabilidad (0-10)", "La velocidad de la red"], c: 1, e: "Score base con AV/AC/PR/UI/S/CIA." },
    { q: "Para priorizar parches conviene mirar si el CVE está en:", o: ["Wikipedia", "CISA KEV (explotado activamente)", "Reddit"], c: 1, e: "Explotabilidad real + exposición." },
    { q: "Antes de reportar un hallazgo de scanner conviene:", o: ["Confiar ciegamente", "Validarlo manualmente (falsos positivos)", "Ignorarlo"], c: 1, e: "El scanner es un punto de partida." },
  ],
  33: [
    { q: "En Metasploit, el 'payload' es:", o: ["La vulnerabilidad", "Lo que se ejecuta tras explotar (ej: shell)", "El escáner"], c: 1, e: "Exploit abre la puerta, payload actúa." },
    { q: "Meterpreter corre principalmente:", o: ["En disco", "En memoria", "En la BIOS"], c: 1, e: "Payload avanzado en memoria." },
    { q: "msfvenom sirve para:", o: ["Escanear puertos", "Generar payloads standalone", "Crackear hashes"], c: 1, e: "Genera payloads fuera de msfconsole." },
    { q: "¿Dónde se practica Metasploit legalmente?", o: ["Cualquier IP de Internet", "Metasploitable / HackTheBox / labs propios", "El router del vecino"], c: 1, e: "Solo con autorización." },
  ],
  34: [
    { q: "Burp Suite se sitúa:", o: ["En el servidor", "Como proxy entre tu navegador y el servidor", "En el router"], c: 1, e: "Intercepta y modifica el tráfico web." },
    { q: "Para reenviar y modificar un request manualmente usás:", o: ["Intruder", "Repeater", "Sequencer"], c: 1, e: "Ideal para probar SQLi/IDOR." },
    { q: "Intruder se usa para:", o: ["Cifrar tráfico", "Automatizar fuzzing/brute force", "Ver el sitemap"], c: 1, e: "Payloads en posiciones definidas." },
    { q: "Para ver tráfico HTTPS en Burp necesitás:", o: ["Nada extra", "Instalar su certificado CA", "Desactivar el firewall"], c: 1, e: "Si no, el navegador alerta por el MITM." },
  ],
  35: [
    { q: "LinPEAS sirve para:", o: ["Cifrar archivos", "Automatizar la búsqueda de vectores de privesc", "Escanear puertos"], c: 1, e: "Enumeración local en Linux." },
    { q: "sudo -l muestra:", o: ["Los usuarios del sistema", "Qué comandos podés ejecutar como root", "Los puertos abiertos"], c: 1, e: "Binarios sudo abusables → shell." },
    { q: "GTFOBins documenta:", o: ["CVEs de Windows", "Binarios Unix abusables para escapar restricciones", "Reglas de firewall"], c: 1, e: "SUID/sudo/capabilities explotables." },
    { q: "Un kernel viejo (uname -a) puede permitir:", o: ["Mejor rendimiento", "Kernel exploits (Dirty COW/Pipe)", "Cifrado más fuerte"], c: 1, e: "Riesgoso pero efectivo si está sin parchear." },
  ],
  36: [
    { q: "En Windows el objetivo de la escalada es llegar a:", o: ["guest", "SYSTEM/Administrator", "anonymous"], c: 1, e: "Máximo privilegio." },
    { q: "La familia 'Potato' (JuicyPotato, PrintSpoofer) abusa de:", o: ["SeImpersonatePrivilege / COM-NTLM", "DNS", "TLS"], c: 0, e: "Escala de servicio a SYSTEM." },
    { q: "Un 'unquoted service path' se explota cuando:", o: ["El servicio usa HTTPS", "La ruta tiene espacios sin comillas", "El servicio está detenido"], c: 1, e: "Windows busca binarios en rutas intermedias." },
    { q: "Mimikatz se usa para:", o: ["Escanear puertos", "Dumpear credenciales de memoria", "Compilar exploits"], c: 1, e: "sekurlsa::logonpasswords." },
  ],
  37: [
    { q: "El pivoting consiste en:", o: ["Borrar logs", "Usar un host comprometido como trampolín a otras redes", "Cifrar el disco"], c: 1, e: "Acceder a redes no alcanzables directamente." },
    { q: "ssh -D crea:", o: ["Un local forward", "Un proxy SOCKS dinámico", "Un backup"], c: 1, e: "Combinado con proxychains." },
    { q: "Pass-the-Hash permite:", o: ["Autenticar con el hash NTLM sin la password", "Crackear AES", "Saltar el firewall físico"], c: 0, e: "Movimiento lateral en redes Windows." },
    { q: "chisel y ligolo-ng sirven para:", o: ["Escanear webs", "Crear túneles/pivoting (a veces sobre HTTP)", "Hashear passwords"], c: 1, e: "Tunneling para bypassear firewalls." },
  ],
  38: [
    { q: "La ingeniería social explota principalmente:", o: ["Bugs de software", "La psicología de las personas", "Puertos abiertos"], c: 1, e: "El humano es el eslabón más débil." },
    { q: "Hacerse pasar por el CEO usa el principio de:", o: ["Escasez", "Autoridad", "Reciprocidad"], c: 1, e: "Cialdini: autoridad." },
    { q: "Dejar un USB infectado para que alguien lo conecte es:", o: ["Tailgating", "Baiting", "Vishing"], c: 1, e: "Cebo que explota la curiosidad." },
    { q: "La mejor defensa contra ingeniería social es:", o: ["Un firewall más caro", "Capacitación y verificación out-of-band", "Cifrar el disco"], c: 1, e: "La cultura y la conciencia." },
  ],
  39: [
    { q: "Spear phishing se diferencia del phishing en que es:", o: ["Masivo y genérico", "Dirigido a una persona específica (con OSINT)", "Solo por SMS"], c: 1, e: "Personalizado, más creíble." },
    { q: "BEC significa:", o: ["Basic Email Cipher", "Business Email Compromise", "Backend Encryption Control"], c: 1, e: "Suplantar a un directivo para ordenar pagos." },
    { q: "micros0ft.com es un ejemplo de:", o: ["Dominio lookalike (typosquatting)", "Un subdominio legítimo", "Un certificado válido"], c: 0, e: "Engaña por similitud visual." },
    { q: "SPF, DKIM y DMARC sirven para:", o: ["Cifrar el disco", "Autenticar el email y frenar spoofing", "Escanear adjuntos"], c: 1, e: "Anti-suplantación de remitente." },
  ],
  40: [
    { q: "¿Dónde se debe analizar malware?", o: ["En tu máquina de trabajo", "En una VM aislada / sandbox", "En el servidor de producción"], c: 1, e: "Aislado, con snapshots y red simulada." },
    { q: "Un IoC es:", o: ["Un tipo de cifrado", "Un indicador de compromiso (hash, IP C2, etc.)", "Un puerto"], c: 1, e: "Alimenta detección y respuesta." },
    { q: "YARA sirve para:", o: ["Cifrar malware", "Identificar malware por patrones (reglas)", "Acelerar la VM"], c: 1, e: "Reglas con strings y condiciones." },
    { q: "ANY.RUN y Cuckoo son:", o: ["Disassemblers", "Sandboxes de análisis de comportamiento", "Packers"], c: 1, e: "Ejecutan la muestra y reportan." },
  ],
  41: [
    { q: "El análisis estático examina el binario:", o: ["Ejecutándolo", "Sin ejecutarlo", "Solo en memoria"], c: 1, e: "Strings, hashes, PE headers, disassembly." },
    { q: "Las APIs importadas (IAT) revelan:", o: ["El color del icono", "Las capacidades del malware", "El precio"], c: 1, e: "VirtualAllocEx → inyección, etc." },
    { q: "Ghidra es:", o: ["Un antivirus", "Un disassembler/decompiler gratuito (NSA)", "Un packer"], c: 1, e: "Para entender la lógica del binario." },
    { q: "Un packer (UPX, Themida):", o: ["Comprime/cifra el código para evadir análisis", "Es un IoC", "Acelera el malware"], c: 0, e: "Hay que hacer unpacking." },
  ],
  42: [
    { q: "El análisis dinámico observa el malware:", o: ["Sin ejecutarlo", "Ejecutándolo en un entorno controlado", "Solo su hash"], c: 1, e: "Revela comportamiento que el estático no ve." },
    { q: "Process Monitor (ProcMon) registra:", o: ["Solo la RAM", "Actividad de archivos, registro y procesos", "El tráfico cifrado"], c: 1, e: "Comportamiento en Windows." },
    { q: "Que el malware detecte VMware y no se ejecute es:", o: ["Un falso positivo", "Sandbox/VM evasion (anti-análisis)", "Un IoC de red"], c: 1, e: "Malware consciente del entorno." },
    { q: "Para evadir el packing, el forense de memoria captura el malware:", o: ["Comprimido", "Ya descifrado en RAM", "En el disco"], c: 1, e: "Volatility analiza la memoria." },
  ],
  43: [
    { q: "La regla de oro del forense es:", o: ["Apagar todo de inmediato", "No alterar la evidencia original (trabajar sobre copias)", "Borrar logs viejos"], c: 1, e: "Admisibilidad legal." },
    { q: "Romper la cadena de custodia:", o: ["No importa", "Invalida la evidencia en la corte", "Acelera el análisis"], c: 1, e: "Registro de quién/cuándo/dónde." },
    { q: "Según el orden de volatilidad, primero capturás:", o: ["El disco", "La RAM", "Los backups"], c: 1, e: "Lo más volátil primero." },
    { q: "Un write blocker sirve para:", o: ["Cifrar la imagen", "Evitar modificar el medio original", "Acelerar la copia"], c: 1, e: "Adquisición forense sin alterar." },
  ],
  44: [
    { q: "File carving recupera:", o: ["Contraseñas", "Archivos borrados por su firma", "Tráfico de red"], c: 1, e: "foremost, scalpel." },
    { q: "Volatility se usa para:", o: ["Forense de disco", "Forense de memoria (RAM)", "Análisis de PCAP"], c: 1, e: "pslist, malfind, netscan." },
    { q: "El plugin windows.malfind de Volatility detecta:", o: ["Usuarios creados", "Código inyectado en procesos", "Puertos abiertos"], c: 1, e: "Inyección en memoria." },
    { q: "El prefetch de Windows evidencia:", o: ["Ejecución de programas", "Cookies del navegador", "Reglas de firewall"], c: 0, e: "Artefacto de ejecución." },
  ],
  45: [
    { q: "Un archivo PCAP contiene:", o: ["Hashes", "Tráfico de red capturado", "Logs del registro"], c: 1, e: "Se analiza con Wireshark/tshark." },
    { q: "NetworkMiner sirve para:", o: ["Escanear puertos", "Extraer archivos/credenciales/hosts de un PCAP", "Cifrar tráfico"], c: 1, e: "Forense de red automatizado." },
    { q: "El beaconing es un indicio de:", o: ["Backup normal", "Comunicación C2 (conexiones periódicas)", "Un escaneo de puertos"], c: 1, e: "Patrón regular hacia un destino." },
    { q: "JA3 es:", o: ["Un cifrado", "Un fingerprint de handshakes TLS", "Un puerto"], c: 1, e: "Identifica clientes aunque cifren." },
  ],
  46: [
    { q: "Un SIEM sirve para:", o: ["Cifrar discos", "Centralizar y correlacionar logs + alertar", "Escanear puertos"], c: 1, e: "Corazón del SOC." },
    { q: "Detectar N fallos de login seguidos de un éxito es una regla de:", o: ["Backup", "Correlación (brute force)", "Cifrado"], c: 1, e: "SPL/KQL en el SIEM." },
    { q: "SOAR aporta:", o: ["Más falsos positivos", "Automatización de la respuesta (aislar host, bloquear IP)", "Cifrado de logs"], c: 1, e: "Reduce el MTTR." },
    { q: "La fatiga de alertas ocurre cuando:", o: ["Hay pocos logs", "Demasiados falsos positivos hacen ignorar los reales", "El SIEM está apagado"], c: 1, e: "Por eso se afinan las reglas." },
  ],
  47: [
    { q: "El ciclo de IR de NIST 800-61 empieza con:", o: ["Recuperación", "Preparación", "Erradicación"], c: 1, e: "Plan, equipo, playbooks antes del incidente." },
    { q: "Contención significa:", o: ["Borrar la evidencia", "Limitar el daño (aislar, bloquear)", "Pagar el rescate"], c: 1, e: "Corto y largo plazo." },
    { q: "Si no se erradica la causa raíz:", o: ["No pasa nada", "El atacante puede volver", "Se acelera la recuperación"], c: 1, e: "Backdoors/cuentas deben eliminarse." },
    { q: "GDPR exige notificar una brecha en:", o: ["72 horas", "30 días", "1 año"], c: 0, e: "Comunicación es parte del IR." },
  ],
  48: [
    { q: "El threat hunting es:", o: ["Esperar alertas", "Buscar proactivamente al atacante (hypothesis-driven)", "Un antivirus"], c: 1, e: "Asume que el atacante ya está dentro." },
    { q: "En la Pyramid of Pain, lo más difícil de cambiar para el atacante son:", o: ["Los hashes", "Las TTPs (comportamiento)", "Las IPs"], c: 1, e: "Cazar por comportamiento es más robusto." },
    { q: "Las hipótesis de hunting suelen basarse en:", o: ["MITRE ATT&CK", "El horóscopo", "El uptime del servidor"], c: 0, e: "Técnicas conocidas → buscás su evidencia." },
    { q: "PowerShell con EncodedCommand desde %TEMP% es:", o: ["Normal", "Una anomalía a investigar", "Un backup"], c: 1, e: "Patrón común de actividad maliciosa." },
  ],
  49: [
    { q: "El modelo de responsabilidad compartida dice que el cliente asegura:", o: ["El hardware de AWS", "IAM, datos y configuración (EN la nube)", "El hipervisor"], c: 1, e: "AWS asegura la nube; vos, en la nube." },
    { q: "La causa #1 de brechas cloud suele ser:", o: ["Fallas de AWS", "Misconfiguración del cliente (ej: S3 público)", "Ataques cuánticos"], c: 1, e: "Bloqueá public access, mínimo privilegio." },
    { q: "CloudTrail provee:", o: ["Detección de malware", "Auditoría de las llamadas a la API (forense)", "Cifrado de S3"], c: 1, e: "Registro de actividad." },
    { q: "Un Security Group con 0.0.0.0/0 en el puerto 22 es:", o: ["Buena práctica", "Una mala configuración (SSH abierto a Internet)", "Obligatorio"], c: 1, e: "Restringí el acceso administrativo." },
  ],
  50: [
    { q: "Microsoft Entra ID (ex Azure AD) gestiona:", o: ["Bases de datos", "Identidad y acceso", "Redes físicas"], c: 1, e: "RBAC, Conditional Access, PIM." },
    { q: "En GCP, las service accounts sobre-privilegiadas son:", o: ["Recomendadas", "Un riesgo común", "Imposibles"], c: 1, e: "Aplicá mínimo privilegio." },
    { q: "El equivalente a AWS GuardDuty en Azure es:", o: ["CloudTrail", "Defender for Cloud", "S3"], c: 1, e: "En GCP es Security Command Center." },
    { q: "CSPM sirve para:", o: ["Cifrar discos", "Detectar misconfigs en multi-cloud de forma continua", "Escanear puertos"], c: 1, e: "Wiz, Prisma, Scout Suite." },
  ],
  51: [
    { q: "Los contenedores comparten con el host:", o: ["El kernel", "La RAM física exclusiva", "El disco completo"], c: 0, e: "Por eso un escape es crítico." },
    { q: "Una buena práctica en el Dockerfile es:", o: ["Correr como root", "Definir un USER no-root", "Hardcodear secretos"], c: 1, e: "Mínimo privilegio." },
    { q: "Trivy se usa para:", o: ["Orquestar pods", "Escanear imágenes por vulns/secrets", "Balancear carga"], c: 1, e: "Integrado en el pipeline." },
    { q: "En Kubernetes, las Network Policies sirven para:", o: ["Cifrar el disco", "Segmentar el tráfico entre pods (default deny)", "Escalar nodos"], c: 1, e: "Limitan el blast radius." },
  ],
  52: [
    { q: "Shift-left significa:", o: ["Probar seguridad solo en producción", "Detectar problemas lo más temprano posible", "Mover el servidor"], c: 1, e: "Más barato arreglar temprano." },
    { q: "SAST analiza:", o: ["La app corriendo", "El código fuente", "El tráfico de red"], c: 1, e: "DAST ataca la app en ejecución." },
    { q: "gitleaks/trufflehog detectan:", o: ["Puertos abiertos", "Secretos commiteados en el repo", "Malware"], c: 1, e: "Secrets scanning en CI." },
    { q: "Un SBOM es:", o: ["Un firewall", "Un inventario de componentes del software", "Un tipo de cifrado"], c: 1, e: "Clave para supply chain security." },
  ],
  53: [
    { q: "La botnet Mirai (2016) se propagó usando:", o: ["Un 0-day de Windows", "IoT con credenciales por defecto", "Phishing"], c: 1, e: "Defaults de fábrica sin cambiar." },
    { q: "binwalk se usa para:", o: ["Escanear puertos", "Extraer el filesystem de un firmware", "Crackear WiFi"], c: 1, e: "Análisis de firmware IoT." },
    { q: "Para analizar una app Android decompilás el:", o: ["PCAP", "APK (con jadx/apktool)", "Registro"], c: 1, e: "El APK es un zip con el código." },
    { q: "OWASP MASVS aplica a:", o: ["Cloud", "Seguridad de aplicaciones móviles", "Redes WiFi"], c: 1, e: "Estándar de verificación mobile." },
  ],
  54: [
    { q: "Antes de cualquier pentest se necesita:", o: ["Un exploit 0-day", "Autorización por escrito (scoping)", "Acceso físico"], c: 1, e: "Sin permiso es ilegal." },
    { q: "El resumen ejecutivo de un reporte va dirigido a:", o: ["Otros pentesters", "Directivos (riesgo de negocio, sin tecnicismos)", "El atacante"], c: 1, e: "Lenguaje no técnico." },
    { q: "Cada hallazgo del reporte debe incluir:", o: ["Solo el CVSS", "Descripción, evidencia, impacto y remediación", "Solo el payload"], c: 1, e: "Accionable para el cliente." },
    { q: "Una certificación ofensiva práctica reconocida es:", o: ["OSCP", "ISO 27001", "PMP"], c: 0, e: "Examen hands-on de 24h." },
  ],
  55: [
    { q: "En Python, re.findall se usa para:", o: ["Abrir sockets", "Extraer patrones (IPs, hashes) con regex", "Cifrar archivos"], c: 1, e: "Parsing de logs." },
    { q: "La API de VirusTotal sirve para:", o: ["Escanear puertos", "Consultar reputación de hashes/URLs", "Pivotar"], c: 1, e: "Threat intel automatizada." },
    { q: "Para escaneos concurrentes en Python usás:", o: ["Solo loops for", "threading / asyncio", "Nada, es secuencial"], c: 1, e: "Paralelismo = velocidad." },
    { q: "argparse aporta:", o: ["Cifrado", "CLIs profesionales con flags", "Acceso a la red"], c: 1, e: "Interfaz de línea de comandos." },
  ],
  56: [
    { q: "Una gran ventaja de Go para tools de seguridad es:", o: ["Necesita un intérprete instalado", "Binarios estáticos y cross-compilation", "Solo corre en Linux"], c: 1, e: "Un ejecutable autocontenido." },
    { q: "Las goroutines sirven para:", o: ["Cifrar datos", "Concurrencia (escaneos masivos)", "Renderizar HTML"], c: 1, e: "Paralelismo ligero." },
    { q: "nuclei, subfinder y httpx están escritos en:", o: ["Python", "Go", "Ruby"], c: 1, e: "ProjectDiscovery usa Go." },
    { q: "Cross-compilation en Go permite:", o: ["Compilar para otros OS desde una sola máquina", "Cifrar el binario", "Evadir AV siempre"], c: 0, e: "Windows/Linux/Mac desde un host." },
  ],
  57: [
    { q: "Metasploit está escrito en:", o: ["Python", "Ruby", "Go"], c: 1, e: "Por eso extenderlo requiere Ruby." },
    { q: "En un módulo MSF, initialize define:", o: ["La lógica del exploit", "La metadata (nombre, autor, targets)", "Los puertos del firewall"], c: 1, e: "Información del módulo." },
    { q: "Un módulo auxiliary típicamente es:", o: ["Un scanner/fuzzer", "Un payload", "Un encoder"], c: 0, e: "No necesariamente explota." },
    { q: "El mejor camino para crear módulos es:", o: ["Empezar de cero", "Leer y adaptar módulos existentes similares", "Evitar los labs"], c: 1, e: "Reload_all y probar en lab." },
  ],
  58: [
    { q: "Un <form> HTML puede enviar datos a:", o: ["Solo al mismo dominio", "Cualquier destino (action)", "Solo por HTTPS"], c: 1, e: "Base de las páginas de phishing." },
    { q: "La validación client-side (JS/required):", o: ["Es suficiente para seguridad", "NO es seguridad: el servidor debe validar", "Reemplaza al backend"], c: 1, e: "El cliente nunca es de confianza." },
    { q: "Un homograph attack usa:", o: ["Buffer overflows", "Caracteres unicode similares en el dominio", "SQL Injection"], c: 1, e: "аpple.com con 'а' cirílica." },
    { q: "Para detectar una página de phishing conviene revisar:", o: ["El color de fondo", "La URL real, el certificado y a dónde apunta el form", "La velocidad de carga"], c: 1, e: "No te fíes de la apariencia." },
  ],
  // ── Doctorate Track ──
  59: [
    { q: "tcache poisoning consiste en sobrescribir:", o: ["El size del top chunk", "El puntero fd de un chunk en tcache", "La GOT"], c: 1, e: "Dos malloc después devuelven la dirección objetivo." },
    { q: "Un Use-After-Free se explota reclamando:", o: ["El chunk liberado con datos controlados", "El kernel", "Un socket"], c: 0, e: "Típico: secuestrar una vtable de C++." },
    { q: "House of Force abusa del:", o: ["fastbin", "size del top chunk", "stack canary"], c: 1, e: "Un size enorme hace que malloc devuelva cualquier dirección." },
    { q: "Safe-linking (glibc ≥2.32) protege:", o: ["La stack", "Los punteros fd de las listas de chunks (XOR con cookie)", "El registro RIP"], c: 1, e: "Dificulta el tcache/fastbin poisoning." },
  ],
  60: [
    { q: "En Linux, un objetivo clásico de la escalada de kernel es:", o: ["Sobrescribir la struct cred (uid=0)", "Cifrar el disco", "Cerrar puertos"], c: 0, e: "O modprobe_path." },
    { q: "SMEP impide que el kernel:", o: ["Acceda a memoria de user", "Ejecute páginas de user space", "Use ASLR"], c: 1, e: "Mata ret2usr → se evade con kROP." },
    { q: "Dirty Pipe (CVE-2022-0847) permite:", o: ["Escanear puertos", "Escribir en archivos de solo lectura", "Crackear WPA2"], c: 1, e: "Primitiva de escritura en el page cache." },
    { q: "Para vencer KASLR el exploit necesita:", o: ["Más RAM", "Un info leak de una dirección de kernel", "Apagar el firewall"], c: 1, e: "Randomiza la base del kernel." },
  ],
  61: [
    { q: "Un exploit full-chain de navegador suele necesitar:", o: ["Un solo bug", "Un bug en el renderer + un sandbox escape", "Acceso físico"], c: 1, e: "El renderer corre sandboxeado." },
    { q: "Las primitivas addrof/fakeobj otorgan:", o: ["R/W arbitrario en el renderer", "Acceso al kernel", "Una shell directa"], c: 0, e: "Base de la explotación de JS engines." },
    { q: "Una type confusion en el JS engine ocurre cuando:", o: ["El engine asume un tipo y recibe otro", "Se agota la RAM", "Falla el TLS"], c: 0, e: "Ej: cambiar el shape/map de un objeto." },
    { q: "Tras lograr RCE en el renderer, el atacante todavía debe:", o: ["Escapar del sandbox", "Reiniciar el navegador", "Nada más"], c: 0, e: "Vía IPC/broker o un bug del SO." },
  ],
  62: [
    { q: "ROP existe principalmente para evadir:", o: ["ASLR", "DEP/NX (stack no ejecutable)", "Stack canaries"], c: 1, e: "Reutiliza código existente en vez de inyectar." },
    { q: "Un gadget de ROP termina típicamente en:", o: ["ret", "nop", "hlt"], c: 0, e: "JOP usa jmp/call en su lugar." },
    { q: "Para construir una cadena ROP con ASLR activo hace falta:", o: ["Un info leak para calcular la base", "Más gadgets", "Apagar DEP"], c: 0, e: "Sin leak no conocés las direcciones." },
    { q: "El Shadow Stack de Intel CET detecta:", o: ["XSS", "ROP que altera las return addresses", "SQL Injection"], c: 1, e: "IBT (endbr64) ataca además el JOP." },
  ],
  63: [
    { q: "El principio de Kerckhoffs dice que es secreta:", o: ["Solo la clave (el sistema es público)", "Todo el algoritmo", "La longitud del mensaje"], c: 0, e: "La seguridad no debe depender del secreto del diseño." },
    { q: "El criptoanálisis diferencial estudia:", o: ["El consumo eléctrico", "Cómo se propaga una diferencia (XOR) por las rondas", "El tiempo de red"], c: 1, e: "Biham–Shamir, aplicado a DES." },
    { q: "FLUSH+RELOAD es un ataque de:", o: ["Padding", "Caché (side-channel)", "Fuerza bruta"], c: 1, e: "Filtra accesos a tablas como las T-tables de AES." },
    { q: "El ataque de Bleichenbacher explota:", o: ["Un padding oracle sobre RSA PKCS#1", "Nonce reuse en AES", "Colisiones de SHA-256"], c: 0, e: "Recupera la clave de sesión consulta a consulta (ROBOT)." },
  ],
  64: [
    { q: "El algoritmo de Shor rompe:", o: ["AES y SHA-3", "RSA, Diffie-Hellman y ECC", "Argon2"], c: 1, e: "Factorización y logaritmo discreto en tiempo polinómico." },
    { q: "Grover afecta a la criptografía simétrica:", o: ["La rompe por completo", "Reduce su seguridad a la mitad", "No la afecta"], c: 1, e: "Manejable subiendo el tamaño de clave." },
    { q: "La familia PQC más versátil y eficiente se basa en:", o: ["Isogenias", "Lattices (retículos)", "Curvas elípticas"], c: 1, e: "Kyber y Dilithium son Module-LWE." },
    { q: "'Harvest now, decrypt later' significa:", o: ["Capturar tráfico cifrado hoy para descifrarlo con cuántica futura", "Minar criptomonedas", "Borrar claves viejas"], c: 0, e: "Motiva migrar a PQC ya." },
  ],
  65: [
    { q: "La propiedad 'zero-knowledge' garantiza que el verificador:", o: ["Aprende el secreto", "No aprende nada salvo la validez", "Obtiene la clave privada"], c: 1, e: "Completitud + soundness + ZK." },
    { q: "A diferencia de los zk-SNARKs, los zk-STARKs:", o: ["Requieren trusted setup", "Son transparentes y post-cuánticos (solo hashes)", "No son sucintos"], c: 1, e: "A cambio de pruebas más grandes." },
    { q: "MPC permite:", o: ["Computar una función sobre entradas privadas sin revelarlas", "Cifrar discos", "Escanear puertos"], c: 0, e: "Garbled circuits, secret sharing." },
    { q: "Una firma de umbral (t de n) sirve para:", o: ["Acelerar el hashing", "Repartir una clave sin un único punto de fallo", "Comprimir datos"], c: 1, e: "Custodia distribuida de claves." },
  ],
  66: [
    { q: "El cifrado homomórfico permite:", o: ["Operar sobre datos sin descifrarlos", "Cifrar más rápido", "Romper RSA"], c: 0, e: "Enc(a)⊕Enc(b)=Enc(a+b)." },
    { q: "Paillier es homomórfico:", o: ["Multiplicativo", "Aditivo", "Totalmente (FHE)"], c: 1, e: "RSA es el multiplicativo; ambos son PHE." },
    { q: "El bootstrapping en FHE sirve para:", o: ["Acelerar la red", "Reducir el ruido acumulado para seguir operando", "Generar claves"], c: 1, e: "Lo resolvió Gentry (2009); es costoso." },
    { q: "El esquema CKKS es ideal para:", o: ["Aritmética aproximada sobre reales (ML)", "Booleanos", "Hashing"], c: 0, e: "BFV/BGV son exactos sobre enteros." },
  ],
  67: [
    { q: "Un ejemplo adversarial es:", o: ["Un bug del framework", "Una entrada con perturbación mínima que engaña al modelo", "Un dato faltante"], c: 1, e: "Imperceptible para un humano." },
    { q: "FGSM y PGD son ataques de:", o: ["Entrenamiento (poisoning)", "Inferencia (evasión)", "Red"], c: 1, e: "Usan el gradiente de la pérdida." },
    { q: "Un backdoor (BadNets) hace que el modelo:", o: ["Falle siempre", "Funcione normal salvo ante un trigger específico", "No entrene"], c: 1, e: "Ataque en tiempo de entrenamiento." },
    { q: "La defensa más efectiva contra adversariales es:", o: ["Adversarial training", "Más capas", "Bajar el learning rate"], c: 0, e: "Costosa y reduce precisión limpia." },
  ],
  68: [
    { q: "El model extraction consiste en:", o: ["Cifrar el modelo", "Clonar un modelo consultando su API", "Borrar el dataset"], c: 1, e: "Roba IP y habilita evasión black-box." },
    { q: "El membership inference determina:", o: ["Si un registro estuvo en el entrenamiento", "El learning rate", "La arquitectura"], c: 0, e: "Se apoya en el overfitting." },
    { q: "Los LLMs pueden sufrir:", o: ["Training data extraction (regurgitar PII)", "Sólo DDoS", "Nada de privacidad"], c: 0, e: "Memorizan parte del corpus." },
    { q: "DP-SGD protege la privacidad agregando:", o: ["Más datos", "Clipping de gradientes + ruido calibrado", "Capas extra"], c: 1, e: "Provee un presupuesto ε." },
  ],
  69: [
    { q: "El problema de fondo de los LLMs es que:", o: ["Son lentos", "No distinguen instrucciones de datos (todo es texto)", "No tienen API"], c: 1, e: "Base de la prompt injection." },
    { q: "La prompt injection indirecta llega vía:", o: ["El system prompt", "Datos externos que el LLM procesa (web, email, PDF)", "El teclado físico"], c: 1, e: "La más peligrosa en agentes." },
    { q: "La salida de un LLM debe tratarse como:", o: ["Confiable", "Entrada NO confiable (puede causar XSS/SQLi/RCE)", "Cifrada"], c: 1, e: "Insecure output handling." },
    { q: "Excessive agency se mitiga con:", o: ["Más herramientas", "Least privilege + human-in-the-loop", "Más tokens"], c: 1, e: "Limitar permisos del agente." },
  ],
  70: [
    { q: "Cargar un modelo en formato pickle puede:", o: ["Ejecutar código arbitrario (RCE)", "Acelerar la inferencia", "Cifrar el modelo"], c: 0, e: "Por eso existe safetensors." },
    { q: "safetensors es más seguro porque:", o: ["Comprime mejor", "Solo guarda tensores, sin código ejecutable", "Usa GPU"], c: 1, e: "Evita la deserialización peligrosa." },
    { q: "Un MLBOM / SBOM de ML inventaria:", o: ["Solo el código", "Datasets, modelos base y dependencias", "Los usuarios"], c: 1, e: "Clave para provenance e integridad." },
    { q: "El monitoreo en producción de un modelo busca:", o: ["Drift, evasión y abuso por queries", "Subir la precisión sola", "Nada, ya está desplegado"], c: 0, e: "La seguridad no termina al desplegar." },
  ],
  71: [
    { q: "Spectre y Meltdown explotan:", o: ["Un bug de software puntual", "La ejecución especulativa/out-of-order del CPU", "WiFi"], c: 1, e: "Dejan trazas microarquitectónicas en caché." },
    { q: "KPTI mitiga Meltdown pero no Spectre porque:", o: ["Spectre cruza el predictor de saltos, no solo kernel/user", "Spectre es más viejo", "KPTI desactiva el CPU"], c: 0, e: "Separar page tables no cubre el branch prediction." },
    { q: "FLUSH+RELOAD recupera el secreto midiendo:", o: ["El voltaje", "El tiempo de recarga de líneas de caché", "El tráfico de red"], c: 1, e: "El byte secreto se usa como índice de un array." },
    { q: "Estos ataques demuestran que:", o: ["El software es siempre seguro", "El aislamiento puede romperse por debajo, en el silicio", "La caché no importa"], c: 1, e: "Procesos/VMs/enclaves afectados." },
  ],
  72: [
    { q: "El voltage glitching busca:", o: ["Cifrar datos", "Inducir un fallo (saltear una instrucción/corromper un cálculo)", "Acelerar el chip"], c: 1, e: "Ej: bypassear una verificación de firma." },
    { q: "DPA/CPA recuperan una clave correlacionando:", o: ["El consumo eléctrico con valores intermedios", "El hash con la clave", "El tiempo de red"], c: 0, e: "Estadística sobre muchas trazas." },
    { q: "Una interfaz JTAG/UART abierta en producción:", o: ["Es inofensiva", "Da acceso a memoria y consola del dispositivo", "Cifra el firmware"], c: 1, e: "Hay que deshabilitarla (fuses)." },
    { q: "Un sensor anti-tamper típicamente:", o: ["Acelera el boot", "Borra las claves (zeroization) ante manipulación", "Sube el voltaje"], c: 1, e: "Detecta voltaje/temperatura/luz anómalos." },
  ],
  73: [
    { q: "El firmware es un blanco de oro porque:", o: ["Es lento", "Persiste por debajo del SO (sobrevive a reinstalarlo)", "No tiene privilegios"], c: 1, e: "Corre antes que cualquier AV/EDR." },
    { q: "Secure Boot garantiza que el firmware:", o: ["Cifra el disco", "Solo ejecuta bootloaders firmados por claves de confianza", "Acelera el arranque"], c: 1, e: "Bloquea bootkits no firmados." },
    { q: "LoJax (APT28) fue notable por:", o: ["Ser un ransomware", "Ser un UEFI rootkit que persiste en el SPI flash", "Atacar WiFi"], c: 1, e: "Sobrevive a reinstalar el SO." },
    { q: "chipsec se usa para:", o: ["Crackear WPA2", "Auditar la configuración de seguridad del firmware", "Generar payloads"], c: 1, e: "SPI protection, Secure Boot, SMM." },
  ],
  74: [
    { q: "Un root of trust debe estar anclado en:", o: ["Software", "Hardware (no modificable por software)", "La red"], c: 1, e: "Si el ancla es software, se subvierte." },
    { q: "Los PCRs de un TPM almacenan:", o: ["Las claves en claro", "Las mediciones (hashes) del arranque", "Los logs de red"], c: 1, e: "Habilitan sealing y attestation." },
    { q: "Intel SGX / AMD SEV proveen:", o: ["Enclaves/VMs aislados del SO y el hipervisor", "Un antivirus", "Cifrado de red"], c: 0, e: "Base del confidential computing." },
    { q: "Foreshadow y SGAxe demuestran que un TEE:", o: ["Es invulnerable", "Puede caer ante side-channels microarquitectónicos", "No usa hardware"], c: 1, e: "No es una bala de plata." },
  ],
};

export function getQuiz(lessonId: number): QuizQuestion[] | undefined {
  return QUIZZES[lessonId];
}
