import type { Module } from "./types";

// 58 modules grouped by category. Static curriculum.
// Initial unlocked modules (st: "active") are M1–M8. The rest start as "locked".
// Per-user progress overrides live in Supabase (table: securities_progress).
export const SYLLABUS: Module[] = [
  // ─── BLOQUE 1: FUNDAMENTOS (1-4) ───
  { m: 1, title: "Fundamentos de Ciberseguridad", cat: "Fundamentos", wk: "1", levels: { b: "Definición, ramas, historia", i: "Modelos de amenazas, kill chain", a: "Threat modeling avanzado, STRIDE/DREAD" }, topics: ["Definición y alcance", "Ramas del campo", "Historia y evolución", "Cyber Kill Chain"], research: "Investiga el caso SolarWinds (2020): ¿cómo un ataque a la cadena de suministro afectó a miles de organizaciones incluyendo agencias del gobierno de EE.UU.?", st: "active" },
  { m: 2, title: "Tríada CIA y Principios", cat: "Fundamentos", wk: "2", levels: { b: "CIA, AAA básico", i: "Menor privilegio, separación de deberes", a: "Zero Trust Architecture" }, topics: ["Confidencialidad, Integridad, Disponibilidad", "Modelo AAA", "Menor privilegio y defensa en profundidad", "Zero Trust"], research: "Investiga el modelo Zero Trust de Google (BeyondCorp): ¿cómo elimina la confianza implícita en la red interna?", st: "active" },
  { m: 3, title: "Amenazas, Ataques y Malware", cat: "Fundamentos", wk: "3", levels: { b: "Tipos de actores y malware", i: "APTs, kill chain, IoCs", a: "Threat Intelligence y MITRE ATT&CK mapping" }, topics: ["Actores maliciosos", "Categorías de ataques", "Malware completo", "MITRE ATT&CK"], research: "Elige un grupo APT (Lazarus, APT28, APT41) e investiga: TTPs usados, campañas conocidas, y cómo mapean al framework MITRE ATT&CK.", st: "active" },
  { m: 4, title: "Frameworks y Estándares", cat: "Fundamentos", wk: "4", levels: { b: "NIST CSF, ISO 27001 overview", i: "Implementación de controles CIS", a: "Auditoría de cumplimiento, SOC 2 Type II" }, topics: ["NIST CSF 5 funciones", "ISO 27001, OWASP", "PCI-DSS, HIPAA, GDPR", "Rutas de certificación"], research: "Compara NIST CSF vs ISO 27001: ¿cuándo usarías uno sobre el otro? Crea una tabla comparativa con ventajas y desventajas.", st: "active" },

  // ─── BLOQUE 2: REDES (5-9) ───
  { m: 5, title: "Redes: Modelo OSI", cat: "Redes", wk: "5", levels: { b: "7 capas y funciones", i: "Protocolos por capa, encapsulamiento", a: "Análisis de ataques por capa OSI" }, topics: ["Las 7 capas", "Protocolos por capa", "Encapsulamiento", "Ataques por capa"], research: "Crea un diagrama detallado del modelo OSI mostrando: función, PDU, protocolos, dispositivos y al menos 2 ataques por capa.", st: "active" },
  { m: 6, title: "TCP/IP y Protocolos", cat: "Redes", wk: "6", levels: { b: "TCP vs UDP, puertos comunes", i: "Three-way handshake, DNS en profundidad", a: "Análisis de protocolos con Wireshark" }, topics: ["TCP vs UDP", "HTTP/S, DNS, SSH, FTP", "Puertos esenciales", "DNS attacks"], research: "Investiga cómo funciona un ataque de DNS Cache Poisoning paso a paso. ¿Qué es DNSSEC y cómo lo previene?", st: "active" },
  { m: 7, title: "Direccionamiento IP y Subnetting", cat: "Redes", wk: "7", levels: { b: "IPv4, IPs privadas/públicas", i: "Subnetting, CIDR, NAT", a: "Diseño de red segmentada con DMZ" }, topics: ["IPv4 e IPv6", "Subnetting y CIDR", "NAT/PAT/DHCP", "Segmentación de red"], research: "Diseña la arquitectura de red de una empresa con 200 empleados: incluye subnetting, DMZ, segmentación por departamento y justifica cada decisión.", st: "active" },
  { m: 8, title: "Análisis de Tráfico (Wireshark)", cat: "Redes", wk: "8", levels: { b: "Captura básica y filtros", i: "Detectar anomalías y ataques", a: "Forense de red avanzado" }, topics: ["Wireshark fundamentals", "Filtros de captura y display", "Detectar ataques en tráfico", "tcpdump y tshark"], research: "Describe paso a paso cómo usarías Wireshark para detectar: (1) credenciales en texto plano, (2) DNS tunneling, (3) ARP spoofing, (4) un escaneo de Nmap.", st: "active" },
  { m: 9, title: "Seguridad WiFi", cat: "Redes", wk: "9", levels: { b: "WEP/WPA/WPA2/WPA3", i: "Ataques: Evil Twin, deauth, cracking", a: "Wireless IDS, 802.1X Enterprise" }, topics: ["Estándares de seguridad WiFi", "Evil Twin y Rogue AP", "Cracking WPA2-PSK", "Protección avanzada"], research: "Investiga el ataque KRACK (2017) contra WPA2: ¿cómo funciona? ¿Por qué WPA3 lo soluciona? ¿Qué dispositivos siguen vulnerables?", st: "locked" },

  // ─── BLOQUE 3: SISTEMAS OPERATIVOS (10-15) ───
  { m: 10, title: "Linux: Fundamentos", cat: "Sistemas", wk: "10", levels: { b: "Navegación, estructura de archivos", i: "Comandos avanzados, pipes", a: "Administración de servidores" }, topics: ["Distros para seguridad", "Sistema de archivos", "Comandos esenciales", "Kali Linux"], research: "Instala Kali Linux en una VM y documenta: (1) proceso de instalación, (2) 10 herramientas que incluye y su función, (3) configuración inicial de seguridad.", st: "locked" },
  { m: 11, title: "Bash Scripting", cat: "Sistemas", wk: "11", levels: { b: "Variables, condicionales, loops", i: "Scripts de seguridad, grep/awk/sed", a: "Automatización de auditorías" }, topics: ["Fundamentos de scripting", "Scripts de seguridad", "grep, awk, sed", "Automatización"], research: "Escribe 3 scripts bash: (1) ping sweep de red, (2) port scanner básico, (3) monitor de intentos de login fallidos en /var/log/auth.log.", st: "locked" },
  { m: 12, title: "Linux: Permisos y Hardening", cat: "Sistemas", wk: "12", levels: { b: "chmod, chown, usuarios", i: "SUID/SGID, sudo, PAM", a: "SELinux/AppArmor, CIS Benchmarks" }, topics: ["Permisos rwx y especiales", "Gestión de usuarios", "Hardening esencial", "CIS Benchmarks"], research: "Crea un checklist de hardening de Linux con 20+ medidas organizadas por prioridad. Para cada una incluye: comando, qué protege y por qué es importante.", st: "locked" },
  { m: 13, title: "Windows: Seguridad", cat: "Sistemas", wk: "13", levels: { b: "Arquitectura, registro, servicios", i: "Event Viewer, logs, GPO", a: "Windows Defender, AMSI, ETW" }, topics: ["Arquitectura de Windows", "Registro y servicios", "Event Viewer y logs", "Group Policy"], research: "Investiga los Windows Event IDs críticos para seguridad (4624, 4625, 4648, 4672, 4720, 7045). ¿Qué actividad registra cada uno y por qué es importante monitorearlos?", st: "locked" },
  { m: 14, title: "Active Directory", cat: "Sistemas", wk: "14", levels: { b: "Conceptos de AD, usuarios, grupos", i: "GPO, Kerberos, LDAP", a: "Ataques a AD: Kerberoasting, DCSync" }, topics: ["Fundamentos de AD", "Kerberos authentication", "LDAP y Group Policy", "Ataques comunes a AD"], research: "Investiga el ataque Kerberoasting: ¿cómo funciona paso a paso? ¿Qué herramientas se usan? ¿Cómo se defiende una organización contra él?", st: "locked" },
  { m: 15, title: "PowerShell para Seguridad", cat: "Sistemas", wk: "15", levels: { b: "Cmdlets esenciales", i: "Scripts de auditoría", a: "PowerShell Empire, obfuscation" }, topics: ["Cmdlets de seguridad", "Scripting defensivo", "Auditoría con PowerShell", "PowerShell ofensivo"], research: "Escribe 3 scripts PowerShell: (1) auditar usuarios con privilegios admin, (2) listar servicios corriendo como SYSTEM, (3) buscar archivos modificados en últimas 24h.", st: "locked" },

  // ─── BLOQUE 4: CRIPTOGRAFÍA (16-19) ───
  { m: 16, title: "Criptografía Simétrica", cat: "Criptografía", wk: "16", levels: { b: "AES, DES, conceptos básicos", i: "Modos de operación (CBC, GCM)", a: "Implementación y vulnerabilidades" }, topics: ["AES, DES, 3DES", "Modos CBC, ECB, GCM", "Gestión de claves", "Vulnerabilidades"], research: "Investiga por qué ECB es inseguro (usa el ejemplo del pingüino cifrado). Compara visualmente ECB vs CBC cifrando una imagen.", st: "locked" },
  { m: 17, title: "Criptografía Asimétrica", cat: "Criptografía", wk: "17", levels: { b: "RSA, conceptos de key pair", i: "ECC, Diffie-Hellman, firmas", a: "Ataques a criptografía, quantum threats" }, topics: ["RSA y ECC", "Firmas digitales", "Key exchange", "Post-quantum crypto"], research: "Investiga cómo la computación cuántica amenaza la criptografía actual. ¿Qué es la criptografía post-cuántica y qué algoritmos propone NIST?", st: "locked" },
  { m: 18, title: "Hashing y PKI", cat: "Criptografía", wk: "18", levels: { b: "MD5, SHA, conceptos de hash", i: "Salting, bcrypt, rainbow tables", a: "PKI completa, certificate pinning" }, topics: ["Algoritmos de hashing", "Salting y key stretching", "PKI y certificados", "Certificate transparency"], research: "Demuestra por qué MD5 es inseguro: investiga colisiones conocidas. Compara MD5 vs SHA-256 vs bcrypt para almacenar contraseñas.", st: "locked" },
  { m: 19, title: "TLS/SSL y VPN", cat: "Criptografía", wk: "19", levels: { b: "HTTPS, certificados básicos", i: "TLS handshake, cipher suites", a: "SSL stripping, HSTS, VPN tunneling" }, topics: ["TLS 1.2 vs 1.3", "Handshake completo", "VPN: IPSec vs WireGuard", "Ataques a TLS"], research: "Analiza el TLS 1.3 handshake paso a paso. ¿Qué mejoras tiene sobre TLS 1.2? ¿Qué cipher suites eliminó y por qué?", st: "locked" },

  // ─── BLOQUE 5: SEGURIDAD WEB (20-24) ───
  { m: 20, title: "Seguridad Web: Fundamentos", cat: "Web Security", wk: "20", levels: { b: "Arquitectura web, HTTP", i: "Headers de seguridad, CORS, CSP", a: "Same-Origin, cookie security avanzada" }, topics: ["Arquitectura cliente-servidor", "HTTP headers de seguridad", "CORS y CSP", "Cookie security"], research: "Configura los headers de seguridad para un sitio web: CSP, HSTS, X-Frame-Options, X-Content-Type-Options. Explica qué ataque previene cada uno.", st: "locked" },
  { m: 21, title: "OWASP Top 10 (Parte 1)", cat: "Web Security", wk: "21", levels: { b: "A01-A05 overview", i: "Explotación práctica", a: "Bypass de protecciones" }, topics: ["Broken Access Control", "Cryptographic Failures", "Injection", "Insecure Design", "Misconfiguration"], research: "Investiga 3 CVEs reales de los últimos 2 años que correspondan a vulnerabilidades del OWASP Top 10. Para cada uno: descripción, CVSS score y fix.", st: "locked" },
  { m: 22, title: "OWASP Top 10 (Parte 2)", cat: "Web Security", wk: "22", levels: { b: "A06-A10 overview", i: "Testing manual", a: "Automated scanning y remediation" }, topics: ["Vulnerable Components", "Auth Failures", "Data Integrity", "SSRF", "Logging Failures"], research: "Investiga el ataque a Log4Shell (CVE-2021-44228): ¿cómo se relaciona con 'Vulnerable and Outdated Components'? ¿Cuál fue el impacto global?", st: "locked" },
  { m: 23, title: "SQL Injection y XSS", cat: "Web Security", wk: "23", levels: { b: "SQLi y XSS básico", i: "Blind SQLi, DOM XSS", a: "WAF bypass, polyglot payloads" }, topics: ["SQL Injection tipos", "XSS: Stored/Reflected/DOM", "Herramientas: sqlmap, XSSer", "Prevención y mitigación"], research: "Practica en DVWA o PortSwigger Labs: documenta 5 ataques de SQLi y 5 de XSS con screenshots, payloads usados y cómo se previene cada uno.", st: "locked" },
  { m: 24, title: "CSRF, SSRF y File Upload", cat: "Web Security", wk: "24", levels: { b: "CSRF y SSRF conceptos", i: "Explotación práctica", a: "Chaining vulnerabilities" }, topics: ["CSRF en profundidad", "SSRF y cloud metadata", "IDOR", "File upload attacks"], research: "Investiga cómo SSRF puede usarse para acceder a metadata de AWS (169.254.169.254). ¿Cómo el caso Capital One (2019) explotó exactamente esto?", st: "locked" },

  // ─── BLOQUE 6: PENTESTING (25-33) ───
  { m: 25, title: "Reconocimiento y OSINT", cat: "Pentesting", wk: "25", levels: { b: "Google dorking, whois", i: "Shodan, Censys, theHarvester", a: "OSINT avanzado, Maltego" }, topics: ["Pasivo vs activo", "Google dorking", "Shodan y Censys", "OSINT frameworks"], research: "Realiza un reconocimiento pasivo completo de un dominio público (ej: tesla.com). Documenta: subdominios, emails, tecnologías, IPs públicas encontradas.", st: "locked" },
  { m: 26, title: "Escaneo con Nmap", cat: "Pentesting", wk: "26", levels: { b: "Scan types básicos", i: "NSE scripts, OS detection", a: "Evasión de IDS/firewall" }, topics: ["SYN, TCP, UDP scan", "NSE scripts", "Service/OS detection", "Firewall evasion"], research: "Documenta 10 comandos Nmap esenciales con: sintaxis, qué hace, cuándo usarlo y ejemplo de output. Incluye técnicas de evasión.", st: "locked" },
  { m: 27, title: "Enumeración de Servicios", cat: "Pentesting", wk: "27", levels: { b: "Banner grabbing, SMB enum", i: "LDAP, SNMP, DNS enum", a: "Custom enumeration scripts" }, topics: ["SMB y NetBIOS", "DNS zone transfer", "SNMP y LDAP", "Enum4linux, rpcclient"], research: "Para cada servicio (SMB, FTP, HTTP, DNS, SNMP): lista herramientas de enumeración, información extraíble y cómo un atacante la aprovecha.", st: "locked" },
  { m: 28, title: "Análisis de Vulnerabilidades", cat: "Pentesting", wk: "28", levels: { b: "Nessus básico, CVE search", i: "OpenVAS, correlación de vulns", a: "Custom vulnerability assessment" }, topics: ["Nessus y OpenVAS", "CVE y CVSS scoring", "Vulnerability assessment", "Priorización de remediación"], research: "Investiga cómo se calcula un CVSS score v3.1. Toma 5 CVEs reales y calcula/verifica su score explicando cada métrica (AV, AC, PR, UI, S, C, I, A).", st: "locked" },
  { m: 29, title: "Metasploit Framework", cat: "Pentesting", wk: "29", levels: { b: "Módulos y payloads básicos", i: "Meterpreter, pivoting", a: "Custom modules, evasion" }, topics: ["Arquitectura Metasploit", "Exploits y payloads", "Meterpreter commands", "Post-exploitation"], research: "Documenta un flujo completo de Metasploit: desde search/use de módulo hasta obtener shell y post-explotación. Usa un laboratorio como Metasploitable.", st: "locked" },
  { m: 30, title: "Burp Suite", cat: "Pentesting", wk: "30", levels: { b: "Proxy, intercepción", i: "Scanner, Intruder, Repeater", a: "Extensiones, automation" }, topics: ["Proxy e intercept", "Scanner automático", "Intruder y Repeater", "Extensiones populares"], research: "Completa 10 labs de PortSwigger Web Security Academy usando Burp Suite. Documenta cada lab: vulnerabilidad, payload, proceso y fix.", st: "locked" },
  { m: 31, title: "Escalada de Privilegios: Linux", cat: "Pentesting", wk: "31", levels: { b: "SUID, world-writable files", i: "Cron, PATH hijacking, capabilities", a: "Kernel exploits, container escape" }, topics: ["SUID/SGID abuse", "Cron y PATH hijacking", "Kernel exploits", "LinPEAS/LinEnum"], research: "Investiga las 10 técnicas más comunes de escalada de privilegios en Linux. Para cada una: cómo detectarla, cómo explotarla y cómo prevenirla.", st: "locked" },
  { m: 32, title: "Escalada de Privilegios: Windows", cat: "Pentesting", wk: "32", levels: { b: "Token, unquoted paths", i: "AlwaysInstallElevated, services", a: "Potato attacks, PrintNightmare" }, topics: ["Token impersonation", "Service exploitation", "WinPEAS y PowerUp", "Potato family"], research: "Investiga los ataques de la familia 'Potato' en Windows (Hot, Rotten, Sweet, Juicy, God). ¿Cómo funciona cada uno y qué escalada logra?", st: "locked" },
  { m: 33, title: "Pivoting y Movimiento Lateral", cat: "Pentesting", wk: "33", levels: { b: "Port forwarding, SSH tunnels", i: "Chisel, ligolo, sshuttle", a: "Pass-the-Hash, Golden Ticket" }, topics: ["Port forwarding", "SSH tunneling", "Chisel y ligolo", "Lateral movement"], research: "Diseña un escenario de red con 3 subredes. Documenta cómo un atacante pivotaría desde la DMZ hasta la red interna usando al menos 2 técnicas diferentes.", st: "locked" },

  // ─── BLOQUE 7: INGENIERÍA SOCIAL (34-35) ───
  { m: 34, title: "Ingeniería Social", cat: "Social Eng.", wk: "34", levels: { b: "Principios de persuasión, phishing", i: "Pretexting, vishing, baiting", a: "Red team social engineering ops" }, topics: ["Cialdini's 6 principles", "Pretexting y baiting", "Tailgating y dumpster diving", "SET toolkit"], research: "Investiga los 6 principios de persuasión de Cialdini y cómo cada uno se aplica en ataques de ingeniería social. Da un ejemplo real de cada uno.", st: "locked" },
  { m: 35, title: "Phishing Avanzado", cat: "Social Eng.", wk: "35", levels: { b: "Anatomía de un phishing", i: "GoPhish, evasión de filtros", a: "Spear phishing, whaling, BEC" }, topics: ["Campañas de phishing", "GoPhish setup", "Evasión de filtros", "BEC (Business Email Compromise)"], research: "Investiga el caso del BEC contra Toyota (2019, $37M). ¿Cómo funcionó? ¿Qué controles habrían prevenido el ataque?", st: "locked" },

  // ─── BLOQUE 8: MALWARE ANALYSIS (36-38) ───
  { m: 36, title: "Malware Analysis: Fundamentos", cat: "Malware", wk: "36", levels: { b: "Tipos, sandbox básico", i: "IoCs, YARA rules", a: "Threat intelligence integration" }, topics: ["Clasificación de malware", "Sandbox analysis", "Indicadores de compromiso", "YARA rules"], research: "Escribe 3 reglas YARA para detectar: (1) un ransomware por extensión de archivo, (2) un keylogger por strings, (3) un backdoor por comportamiento de red.", st: "locked" },
  { m: 37, title: "Malware: Análisis Estático", cat: "Malware", wk: "37", levels: { b: "Strings, hashing, PE headers", i: "IDA Free / Ghidra basics", a: "Decompilation, unpacking" }, topics: ["PE file analysis", "Strings y hashing", "Ghidra intro", "Unpacking y deobfuscation"], research: "Analiza un sample de malware de MalwareBazaar usando análisis estático. Documenta: hash, strings interesantes, imports sospechosos, IoCs extraídos.", st: "locked" },
  { m: 38, title: "Malware: Análisis Dinámico", cat: "Malware", wk: "38", levels: { b: "Sandbox execution", i: "Process Monitor, Regshot", a: "API hooking, memory forensics" }, topics: ["Sandbox seguro", "Process Monitor", "Behavioral analysis", "Network callbacks"], research: "Configura un laboratorio de análisis de malware seguro (VM aislada). Documenta: setup, herramientas instaladas, precauciones de seguridad y proceso de análisis.", st: "locked" },

  // ─── BLOQUE 9: FORENSE (39-41) ───
  { m: 39, title: "Forense Digital: Fundamentos", cat: "Forense", wk: "39", levels: { b: "Cadena de custodia, herramientas", i: "Adquisición de evidencia", a: "Legal considerations, court testimony" }, topics: ["Cadena de custodia", "Adquisición de imagen", "Herramientas forenses", "Documentación"], research: "Crea un procedimiento operativo estándar (SOP) para la adquisición forense de un disco duro. Incluye: pasos, herramientas, hashes y documentación requerida.", st: "locked" },
  { m: 40, title: "Forense: Disco y Memoria", cat: "Forense", wk: "40", levels: { b: "Autopsy básico", i: "Volatility, timeline analysis", a: "Advanced memory forensics" }, topics: ["Autopsy y FTK", "Volatility Framework", "Análisis de RAM", "Recuperación de datos"], research: "Investiga Volatility Framework: lista 10 plugins esenciales, qué información extrae cada uno y en qué escenario de investigación los usarías.", st: "locked" },
  { m: 41, title: "Forense de Red", cat: "Forense", wk: "41", levels: { b: "PCAP analysis basics", i: "NetworkMiner, Zeek", a: "Timeline correlation, C2 detection" }, topics: ["PCAP analysis", "NetworkMiner", "Zeek/Bro IDS", "C2 traffic detection"], research: "Investiga cómo detectar comunicación de Command & Control (C2) en tráfico de red. ¿Qué patrones buscarías? ¿Qué herramientas usarías?", st: "locked" },

  // ─── BLOQUE 10: DEFENSE (42-44) ───
  { m: 42, title: "SIEM y Monitoreo", cat: "Blue Team", wk: "42", levels: { b: "Conceptos SIEM, log basics", i: "Splunk / ELK queries", a: "Custom correlation rules, dashboards" }, topics: ["Splunk / ELK Stack", "Reglas de correlación", "Dashboards", "Automatización SOAR"], research: "Crea 5 reglas de correlación SIEM para detectar: (1) brute force, (2) lateral movement, (3) data exfiltration, (4) privilege escalation, (5) malware C2.", st: "locked" },
  { m: 43, title: "Incident Response", cat: "Blue Team", wk: "43", levels: { b: "IR lifecycle, NIST 800-61", i: "Contención y erradicación", a: "IR playbooks, tabletop exercises" }, topics: ["NIST IR lifecycle", "Contención y erradicación", "Recuperación", "Lecciones aprendidas"], research: "Crea un IR playbook completo para un ataque de ransomware. Incluye: detección, contención, erradicación, recuperación y comunicación.", st: "locked" },
  { m: 44, title: "Threat Hunting", cat: "Blue Team", wk: "44", levels: { b: "Concepto de hunting", i: "Hypothesis-driven, ATT&CK mapping", a: "Custom hunting queries, automation" }, topics: ["Proactive hunting", "ATT&CK mapping", "Hunting playbooks", "KQL / SPL queries"], research: "Diseña 3 hipótesis de threat hunting basadas en MITRE ATT&CK. Para cada una: técnica, fuente de datos, query de búsqueda y expected output.", st: "locked" },

  // ─── BLOQUE 11: CLOUD & DEVOPS (45-48) ───
  { m: 45, title: "Cloud Security: AWS", cat: "Cloud", wk: "45", levels: { b: "IAM, S3, conceptos", i: "VPC, Security Groups, CloudTrail", a: "GuardDuty, Config, multi-account" }, topics: ["IAM y políticas", "S3 security", "VPC y networking", "CloudTrail y GuardDuty"], research: "Investiga los 5 errores de configuración más comunes en AWS que causan brechas: S3 público, IAM excesivo, security groups abiertos, etc.", st: "locked" },
  { m: 46, title: "Cloud Security: Azure y GCP", cat: "Cloud", wk: "46", levels: { b: "Azure AD, GCP IAM basics", i: "Cloud hardening", a: "Multi-cloud security strategy" }, topics: ["Azure AD y RBAC", "GCP IAM", "Cloud hardening", "Multi-cloud"], research: "Compara las herramientas de seguridad nativas de AWS vs Azure vs GCP. Crea una tabla de equivalencias (ej: GuardDuty = Sentinel = SCC).", st: "locked" },
  { m: 47, title: "Container Security", cat: "Cloud", wk: "47", levels: { b: "Docker basics, images", i: "Dockerfile security, scanning", a: "Kubernetes RBAC, network policies" }, topics: ["Docker security", "Image scanning", "Kubernetes security", "Pod security"], research: "Investiga las 10 mejores prácticas de seguridad en Docker: desde el Dockerfile hasta el runtime. ¿Qué herramientas de scanning existen?", st: "locked" },
  { m: 48, title: "DevSecOps y CI/CD", cat: "Cloud", wk: "48", levels: { b: "Concepto de shift-left", i: "SAST/DAST en pipeline", a: "Full pipeline security, IaC scanning" }, topics: ["SAST y DAST", "Dependency scanning", "Pipeline security", "Infrastructure as Code"], research: "Diseña un pipeline CI/CD seguro completo: desde commit hasta deploy. Incluye: SAST, DAST, SCA, secrets scanning, IaC scanning.", st: "locked" },

  // ─── BLOQUE 12: ESPECIALIZADOS (49-50) ───
  { m: 49, title: "IoT y Mobile Security", cat: "Especializado", wk: "49", levels: { b: "OWASP IoT/Mobile Top 10", i: "Firmware analysis, APK decompile", a: "Hardware hacking, BLE attacks" }, topics: ["OWASP IoT Top 10", "Firmware analysis", "Android/iOS security", "BLE y hardware"], research: "Investiga OWASP Mobile Top 10: para cada vulnerabilidad da un ejemplo real, herramienta de testing y mitigación recomendada.", st: "locked" },
  { m: 50, title: "Proyecto Final y Carrera", cat: "Especializado", wk: "50", levels: { b: "Portfolio básico", i: "Auditoría completa", a: "Reporte profesional, CTF design" }, topics: ["Auditoría end-to-end", "Reporte profesional", "Plan de certificaciones", "Portfolio y carrera"], research: "Realiza una auditoría de seguridad completa (simulada): reconocimiento, escaneo, enumeración, explotación y genera un reporte profesional de pentesting.", st: "locked" },

  // ─── BLOQUE 13: PROGRAMACIÓN (51-58) ───
  { m: 51, title: "Python para Ciberseguridad", cat: "Programación", wk: "51", levels: { b: "Sintaxis, variables, funciones", i: "Socket programming, requests, scapy", a: "Exploit development, tool building" }, topics: ["Fundamentos de Python", "Networking con sockets", "Scapy y requests", "Automatización de pentesting"], research: "Escribe en Python: (1) port scanner con sockets, (2) web scraper con requests, (3) sniffer de red con scapy. Documenta el código y su uso en seguridad.", st: "locked" },
  { m: 52, title: "Python Avanzado para Seguridad", cat: "Programación", wk: "52", levels: { b: "File I/O, regex", i: "Cryptography library, API interaction", a: "Custom exploit frameworks" }, topics: ["Regex y parsing de logs", "Cryptography en Python", "API de VirusTotal y Shodan", "Tool building avanzado"], research: "Construye un mini framework en Python que: (1) consulte la API de VirusTotal, (2) busque IPs en Shodan, (3) genere un reporte HTML automático.", st: "locked" },
  { m: 53, title: "JavaScript y Seguridad Web", cat: "Programación", wk: "53", levels: { b: "JS fundamentals, DOM", i: "XSS payloads, cookie manipulation", a: "Prototype pollution, deserialization" }, topics: ["Fundamentos de JavaScript", "DOM manipulation", "XSS desde la perspectiva del atacante", "Node.js security"], research: "Investiga Prototype Pollution en JavaScript: ¿cómo funciona? Crea un ejemplo de código vulnerable y su fix. ¿Qué CVEs famosos lo explotan?", st: "locked" },
  { m: 54, title: "SQL y Seguridad de Bases de Datos", cat: "Programación", wk: "54", levels: { b: "SELECT, INSERT, WHERE basics", i: "UNION, subqueries, SQLi avanzado", a: "Stored procedures, DB hardening" }, topics: ["SQL fundamentals", "SQL Injection manual", "Blind SQLi y time-based", "Database hardening"], research: "Practica SQLi manual: documenta payloads para (1) extraer versión de DB, (2) listar tablas, (3) extraer datos, (4) blind SQLi con time-based technique.", st: "locked" },
  { m: 55, title: "C/C++ y Low-Level Security", cat: "Programación", wk: "55", levels: { b: "Sintaxis C, punteros, memoria", i: "Buffer overflows, stack/heap", a: "Shellcode, ROP chains, format strings" }, topics: ["Fundamentos de C", "Gestión de memoria", "Buffer overflow", "Shellcode basics"], research: "Investiga cómo funciona un buffer overflow en la stack: dibuja el layout de memoria, explica cómo se sobrescribe EIP/RIP y cómo se redirige la ejecución.", st: "locked" },
  { m: 56, title: "Go para Security Tools", cat: "Programación", wk: "56", levels: { b: "Go basics, goroutines", i: "Network programming en Go", a: "Building security tools en Go" }, topics: ["Fundamentos de Go", "Concurrencia y goroutines", "Network tools en Go", "Herramientas como Chisel/Ligolo"], research: "Investiga por qué Go es popular para herramientas de seguridad modernas. Lista 10 herramientas escritas en Go y qué ventajas tiene sobre Python para tools.", st: "locked" },
  { m: 57, title: "Ruby y Metasploit Development", cat: "Programación", wk: "57", levels: { b: "Ruby basics", i: "Metasploit module structure", a: "Custom Metasploit modules" }, topics: ["Fundamentos de Ruby", "Estructura de módulos MSF", "Escribir exploits custom", "Auxiliares y post-explotación"], research: "Estudia la estructura de un módulo de Metasploit. Escribe un módulo auxiliar simple (ej: scanner) y documenta cada sección del código.", st: "locked" },
  { m: 58, title: "HTML/CSS y Seguridad Frontend", cat: "Programación", wk: "58", levels: { b: "HTML/CSS fundamentals", i: "Forms, inputs, data flow", a: "Phishing page creation y detection" }, topics: ["Estructura HTML", "Formularios y inputs", "Client-side validation (y sus límites)", "Cómo detectar phishing pages"], research: "Analiza 5 técnicas que usan los phishers para crear páginas convincentes: homograph attacks, iframe injection, CSS tricks, etc. ¿Cómo detectar cada una?", st: "locked" },

  // ═══ DOCTORATE / RESEARCH TRACK (M59+) — especializaciones de posgrado ═══
  // ─── BLOQUE 14: EXPLOIT DEV AVANZADO (59-62) ───
  { m: 59, title: "Heap Exploitation", cat: "Exploit Dev Avanzado", wk: "59", levels: { b: "glibc malloc/free, estructura de chunks", i: "tcache/fastbin attacks, use-after-free", a: "House of techniques, tcache poisoning → arbitrary write" }, topics: ["glibc heap internals", "tcache y fastbin", "Use-after-free", "House of Force/Einherjar/Orange"], research: "Elige una técnica 'House of' (Force, Spirit, Einherjar, Orange) y documenta paso a paso cómo construye una primitiva de escritura arbitraria, con qué versión de glibc funciona y qué mitigaciones la frenan.", st: "locked" },
  { m: 60, title: "Kernel Exploitation", cat: "Exploit Dev Avanzado", wk: "60", levels: { b: "espacio kernel vs user, syscalls", i: "UAF/OOB en kernel, ret2usr, cred struct", a: "bypass SMEP/SMAP/KASLR/KPTI, kROP" }, topics: ["Kernel vs user space", "Vulnerabilidades de kernel", "Primitivas (modprobe_path, cred)", "Mitigaciones y bypass"], research: "Investiga un CVE de escalada de privilegios en el kernel de Linux (ej: Dirty Pipe CVE-2022-0847): causa raíz, primitiva que otorga, exploit público y el parche que lo corrige.", st: "locked" },
  { m: 61, title: "Browser Exploitation", cat: "Exploit Dev Avanzado", wk: "61", levels: { b: "arquitectura multiproceso, JS engine", i: "type confusion en V8, OOB en JIT", a: "addrof/fakeobj, RW arbitrario, sandbox escape" }, topics: ["Arquitectura del navegador", "Vulnerabilidades del JS engine", "Primitivas de explotación", "Sandbox escape y full chain"], research: "Estudia un writeup público de Pwn2Own contra un navegador: qué bug del JS engine usaron, cómo construyeron el RW arbitrario y cómo escaparon del sandbox.", st: "locked" },
  { m: 62, title: "ROP/JOP Avanzado y Bypass de Mitigaciones", cat: "Exploit Dev Avanzado", wk: "62", levels: { b: "code-reuse, por qué (DEP/NX)", i: "gadgets, cadenas, ASLR bypass vía leak", a: "JOP, automation, bypass de CFI/Intel CET" }, topics: ["Code-reuse attacks", "Construcción de cadenas ROP", "JOP y automatización", "CFI y Intel CET"], research: "Investiga Intel CET (shadow stack + IBT) y Control-Flow Guard de Windows: cómo mitigan ROP/JOP y qué líneas de investigación existen para bypassearlos.", st: "locked" },
];

export const SYLLABUS_CATEGORIES = [
  "Fundamentos",
  "Redes",
  "Sistemas",
  "Criptografía",
  "Web Security",
  "Pentesting",
  "Social Eng.",
  "Malware",
  "Forense",
  "Blue Team",
  "Cloud",
  "Especializado",
  "Programación",
  // Doctorate / Research Track
  "Exploit Dev Avanzado",
] as const;

export type SyllabusCategory = (typeof SYLLABUS_CATEGORIES)[number];

export function getModule(id: number): Module | undefined {
  return SYLLABUS.find((m) => m.m === id);
}

export function modulesByCategory(): Record<string, Module[]> {
  const map: Record<string, Module[]> = {};
  for (const cat of SYLLABUS_CATEGORIES) map[cat] = [];
  for (const mod of SYLLABUS) {
    if (!map[mod.cat]) map[mod.cat] = [];
    map[mod.cat].push(mod);
  }
  return map;
}
