// Línea de tiempo de hitos de la ciberseguridad. Eventos ordenados por año.

import type { HistoryTimeline } from "./types";

export const TIMELINES: HistoryTimeline[] = [
  {
    id: 1,
    module: 1,
    title: "Historia y evolución de la ciberseguridad",
    events: [
      { year: 1971, title: "Creeper", desc: "Primer programa autorreplicante conocido en ARPANET; nace el antivirus Reaper para eliminarlo.", impact: "low" },
      { year: 1988, title: "Gusano de Morris", desc: "Primer gusano masivo de Internet; infectó ~10% de los hosts y motivó la creación del primer CERT.", impact: "high" },
      { year: 2000, title: "ILOVEYOU", desc: "Gusano de correo que causó miles de millones en daños; popularizó el malware por ingeniería social.", impact: "high" },
      { year: 2010, title: "Stuxnet", desc: "Primer ciberarma conocida; saboteó centrifugadoras nucleares iraníes. Inaugura la era del malware patrocinado por estados.", impact: "high" },
      { year: 2013, title: "Filtraciones de Snowden", desc: "Revelan programas de vigilancia masiva; impulsan el cifrado por defecto en toda la industria.", impact: "medium" },
      { year: 2017, title: "WannaCry / NotPetya", desc: "Ransomware que usó el exploit EternalBlue; afectó ~230.000 equipos en 150 países.", impact: "high" },
      { year: 2020, title: "SolarWinds", desc: "Ataque a la cadena de suministro que comprometió a miles de organizaciones vía una actualización troyanizada.", impact: "high" },
      { year: 2021, title: "Log4Shell", desc: "Vulnerabilidad crítica (CVSS 10.0) en Log4j; explotación masiva por su ubicuidad en software Java.", impact: "high" },
      { year: 2023, title: "MOVEit", desc: "Explotación masiva de un zero-day en software de transferencia de archivos; campaña de extorsión a gran escala.", impact: "high" },
      { year: 2024, title: "Era de la IA ofensiva", desc: "Phishing y deepfakes generados por IA elevan la escala y el realismo de los ataques de ingeniería social.", impact: "medium" },
    ],
  },
  {
    id: 2,
    module: 6,
    title: "Evolución de los protocolos de Internet",
    events: [
      { year: 1969, title: "ARPANET (NCP)", desc: "Nace la red precursora de Internet con el protocolo NCP.", impact: "medium" },
      { year: 1983, title: "TCP/IP", desc: "ARPANET adopta TCP/IP como estándar: el 'cumpleaños' de la Internet moderna.", impact: "high" },
      { year: 1983, title: "DNS", desc: "Se introduce el sistema de nombres de dominio; adiós a los archivos hosts manuales.", impact: "high" },
      { year: 1991, title: "HTTP / World Wide Web", desc: "Tim Berners-Lee publica la Web y el protocolo HTTP.", impact: "high" },
      { year: 1995, title: "SSL", desc: "Netscape crea SSL para cifrar el tráfico; base del futuro HTTPS.", impact: "medium" },
      { year: 1999, title: "TLS 1.0", desc: "SSL se estandariza como TLS; evoluciona hasta TLS 1.3 (2018).", impact: "medium" },
      { year: 2021, title: "HTTP/3 (QUIC)", desc: "HTTP sobre QUIC (UDP) reduce latencia y mejora la conexión móvil.", impact: "medium" },
    ],
  },
  {
    id: 3,
    module: 9,
    title: "Evolución de la seguridad WiFi",
    events: [
      { year: 1997, title: "WEP", desc: "Primer cifrado WiFi (RC4); se demostró roto pocos años después.", impact: "high" },
      { year: 2003, title: "WPA", desc: "Solución de transición con TKIP mientras se finalizaba WPA2.", impact: "medium" },
      { year: 2004, title: "WPA2 (802.11i)", desc: "Cifrado AES-CCMP; estándar dominante durante más de una década.", impact: "high" },
      { year: 2017, title: "Ataque KRACK", desc: "Vulnerabilidad en el 4-way handshake de WPA2; impulsó la urgencia de WPA3.", impact: "high" },
      { year: 2018, title: "WPA3", desc: "Introduce SAE (Dragonfly) y PMF obligatorio; frena el cracking offline.", impact: "high" },
    ],
  },
  {
    id: 4,
    module: 10,
    title: "Historia de Linux y las distros de seguridad",
    events: [
      { year: 1991, title: "Linux", desc: "Linus Torvalds publica el kernel; nace el ecosistema libre que domina los servidores.", impact: "high" },
      { year: 1993, title: "Debian y Slackware", desc: "Primeras distros mayores; Debian será base de Ubuntu y Kali.", impact: "medium" },
      { year: 2003, title: "Knoppix (live CD)", desc: "Populariza el Linux 'en vivo' sin instalación, base de las distros forenses.", impact: "low" },
      { year: 2006, title: "BackTrack", desc: "Primera distro de pentesting de referencia, precursora de Kali.", impact: "medium" },
      { year: 2013, title: "Kali Linux", desc: "OffSec reescribe BackTrack sobre Debian; estándar de facto del pentesting.", impact: "high" },
      { year: 2013, title: "Parrot OS", desc: "Alternativa ligera orientada a seguridad y privacidad.", impact: "low" },
    ],
  },
  {
    id: 5,
    module: 14,
    title: "Evolución de los ataques a Active Directory",
    events: [
      { year: 2000, title: "Active Directory", desc: "Microsoft lo lanza con Windows 2000; se vuelve la columna vertebral corporativa.", impact: "high" },
      { year: 2011, title: "Mimikatz", desc: "Benjamin Delpy publica la herramienta que populariza Pass-the-Hash y el volcado de credenciales.", impact: "high" },
      { year: 2014, title: "Kerberoasting", desc: "Tim Medin presenta el ataque a cuentas de servicio vía tickets Kerberos.", impact: "high" },
      { year: 2015, title: "Golden Ticket", desc: "Se difunde la falsificación de TGTs abusando de la cuenta krbtgt.", impact: "high" },
      { year: 2016, title: "BloodHound", desc: "Grafica rutas de ataque en AD usando teoría de grafos; cambia el red teaming.", impact: "high" },
    ],
  },
  {
    id: 6,
    module: 16,
    title: "Evolución de la criptografía",
    events: [
      { year: 1943, title: "Enigma y Bletchley Park", desc: "El criptoanálisis aliado de la máquina Enigma (heredera del cifrado clásico tipo César) impulsa la computación moderna.", impact: "medium" },
      { year: 1977, title: "DES", desc: "Primer estándar de cifrado simétrico ampliamente adoptado; su clave de 56 bits acabó siendo insuficiente.", impact: "medium" },
      { year: 1977, title: "RSA", desc: "Rivest, Shamir y Adleman publican el primer esquema asimétrico práctico.", impact: "high" },
      { year: 2001, title: "AES", desc: "El NIST estandariza Rijndael como AES; el cifrado simétrico dominante hoy.", impact: "high" },
      { year: 2024, title: "Estándares post-cuánticos", desc: "El NIST publica los primeros algoritmos resistentes a ordenadores cuánticos (ML-KEM/Kyber).", impact: "high" },
    ],
  },
  {
    id: 7,
    module: 19,
    title: "Evolución de SSL/TLS",
    events: [
      { year: 1996, title: "SSL 3.0", desc: "Netscape consolida el cifrado web; años después se demostraría inseguro (POODLE).", impact: "medium" },
      { year: 1999, title: "TLS 1.0", desc: "SSL se estandariza como TLS en el IETF.", impact: "medium" },
      { year: 2008, title: "TLS 1.2", desc: "Añade AEAD (AES-GCM) y hashes modernos; dominante durante una década.", impact: "high" },
      { year: 2014, title: "POODLE y Heartbleed", desc: "Fallos célebres aceleran el abandono de SSL/TLS antiguos y la cultura del parcheo.", impact: "high" },
      { year: 2018, title: "TLS 1.3", desc: "Handshake de 1-RTT, solo cifrados AEAD y forward secrecy obligatorio.", impact: "high" },
    ],
  },
  {
    id: 8,
    module: 20,
    title: "Historia de los ataques web",
    events: [
      { year: 1998, title: "SQL Injection", desc: "Rain Forest Puppy documenta la inyección SQL; sigue siendo un riesgo top 25 años después.", impact: "high" },
      { year: 2001, title: "Fundación de OWASP", desc: "Nace la comunidad que estandarizará las buenas prácticas de seguridad web.", impact: "high" },
      { year: 2005, title: "Gusano Samy (XSS)", desc: "Un XSS en MySpace infecta un millón de perfiles en horas; demuestra el poder del XSS stored.", impact: "high" },
      { year: 2008, title: "Brecha de Heartland", desc: "Una SQL Injection compromete 130M+ tarjetas; impulsa el cumplimiento PCI.", impact: "high" },
      { year: 2014, title: "Heartbleed", desc: "Fallo en OpenSSL que expone memoria de servidores; cambia la gestión de vulnerabilidades.", impact: "high" },
      { year: 2019, title: "Capital One (SSRF)", desc: "Un SSRF a metadata de AWS filtra datos de 100M+ personas; consagra el SSRF en el Top 10.", impact: "high" },
    ],
  },
  {
    id: 9,
    module: 21,
    title: "Evolución del OWASP Top 10",
    events: [
      { year: 2003, title: "Primer OWASP Top 10", desc: "La lista inaugural establece un lenguaje común para los riesgos web.", impact: "medium" },
      { year: 2013, title: "Top 10 2013", desc: "Injection en el #1; consolida la lista como referencia de la industria.", impact: "medium" },
      { year: 2017, title: "Top 10 2017", desc: "Entran XXE y deserialización insegura; refleja apps más complejas y APIs.", impact: "medium" },
      { year: 2021, title: "Top 10 2021", desc: "Broken Access Control sube al #1 y aparece SSRF (A10); enfoque por categorías de causa.", impact: "high" },
    ],
  },
  {
    id: 10,
    module: 25,
    title: "Historia del pentesting y sus herramientas",
    events: [
      { year: 1997, title: "Nmap", desc: "Fyodor publica el escáner de red que se vuelve el estándar de descubrimiento de puertos.", impact: "high" },
      { year: 1998, title: "Nessus", desc: "Nace el escáner de vulnerabilidades más influyente (luego comercial; OpenVAS surge de su fork).", impact: "medium" },
      { year: 2003, title: "Metasploit", desc: "H.D. Moore crea el framework que democratiza la explotación y la post-explotación.", impact: "high" },
      { year: 2006, title: "Burp Suite", desc: "PortSwigger lanza la plataforma que se vuelve el estándar del testing web.", impact: "high" },
      { year: 2013, title: "Kali Linux", desc: "OffSec consolida el arsenal ofensivo en una distro de referencia.", impact: "high" },
      { year: 2016, title: "BloodHound y C2 modernos", desc: "El auge de Cobalt Strike y BloodHound profesionaliza el red teaming y el movimiento lateral.", impact: "high" },
    ],
  },
  {
    id: 11,
    module: 35,
    title: "Evolución del phishing y la ingeniería social",
    events: [
      { year: 1995, title: "Phishing en AOL", desc: "Atacantes roban credenciales y datos de pago haciéndose pasar por personal de AOL; nace el phishing moderno.", impact: "medium" },
      { year: 1996, title: "El término 'phishing'", desc: "Se acuña la palabra (fishing de credenciales con cebo); el concepto se populariza.", impact: "low" },
      { year: 2011, title: "Brecha de RSA", desc: "Un spear phishing con un Excel malicioso compromete los tokens SecurID; hito del phishing dirigido.", impact: "high" },
      { year: 2016, title: "Auge del BEC", desc: "El fraude del CEO/proveedor se vuelve uno de los más costosos según el FBI, sin necesidad de malware.", impact: "high" },
      { year: 2020, title: "Hackeo de Twitter", desc: "Un vishing a empleados permite secuestrar cuentas de alto perfil; demuestra el poder de la ingeniería social telefónica.", impact: "high" },
      { year: 2024, title: "Phishing con IA", desc: "Correos sin errores, clonación de voz y deepfakes elevan el realismo y la escala del engaño.", impact: "high" },
    ],
  },
  {
    id: 12,
    module: 36,
    title: "Evolución del malware",
    events: [
      { year: 1986, title: "Brain", desc: "Primer virus de PC (sector de arranque); marca el inicio del malware en computadoras personales.", impact: "medium" },
      { year: 1999, title: "Melissa", desc: "Macro-virus de correo que se propaga por Word/Outlook a escala masiva.", impact: "medium" },
      { year: 2007, title: "Zeus", desc: "Troyano bancario que profesionaliza el robo de credenciales y el crimeware como servicio.", impact: "high" },
      { year: 2010, title: "Stuxnet", desc: "Malware patrocinado por estados que sabotea sistemas industriales; inaugura la ciberguerra.", impact: "high" },
      { year: 2013, title: "CryptoLocker", desc: "Populariza el ransomware con cifrado y pago en cripto; abre la era del ransomware.", impact: "high" },
      { year: 2017, title: "WannaCry / NotPetya", desc: "Ransomware-gusano con EternalBlue; daños globales y foco en el parcheo.", impact: "high" },
      { year: 2021, title: "Era del RaaS y doble extorsión", desc: "El ransomware como servicio y la exfiltración previa al cifrado dominan el panorama.", impact: "high" },
    ],
  },
  {
    id: 13,
    module: 39,
    title: "Evolución de la forense digital",
    events: [
      { year: 1993, title: "Forense de disco temprana", desc: "Las primeras conferencias y unidades policiales formalizan la disciplina centrada en discos.", impact: "medium" },
      { year: 1998, title: "EnCase", desc: "Se vuelve la suite forense comercial de referencia; estandariza la imagen y el análisis de disco.", impact: "high" },
      { year: 2005, title: "The Sleuth Kit / Autopsy", desc: "El kit open source de Brian Carrier democratiza la forense de disco.", impact: "medium" },
      { year: 2007, title: "Volatility (forense de memoria)", desc: "Consolida el análisis de RAM; lo volátil pasa a ser evidencia de primer orden.", impact: "high" },
      { year: 2014, title: "Era anti-forense", desc: "Timestomping, cifrado y borrado seguro obligan a técnicas más profundas (memoria, red).", impact: "medium" },
      { year: 2020, title: "Forense de cloud y móvil", desc: "La evidencia migra a la nube y a los smartphones; nuevos retos legales y técnicos.", impact: "high" },
    ],
  },
  {
    id: 14,
    module: 42,
    title: "Evolución de la defensa (Blue Team / SOC)",
    events: [
      { year: 1987, title: "Antivirus por firmas", desc: "La defensa nace centrada en detectar malware conocido por su firma.", impact: "medium" },
      { year: 2005, title: "SIEM", desc: "Se consolida la centralización y correlación de logs; nace el SOC moderno.", impact: "high" },
      { year: 2013, title: "EDR", desc: "La detección y respuesta en el endpoint supera al antivirus tradicional con telemetría rica.", impact: "high" },
      { year: 2015, title: "MITRE ATT&CK", desc: "Da un lenguaje común de TTPs que reorganiza la detección y el threat hunting.", impact: "high" },
      { year: 2019, title: "SOAR y XDR", desc: "La automatización de la respuesta y la telemetría unificada aceleran y escalan el SOC.", impact: "high" },
      { year: 2023, title: "Hunting y detección con IA", desc: "El threat hunting proactivo y la analítica con IA se vuelven estándar frente a adversarios más rápidos.", impact: "medium" },
    ],
  },
  {
    id: 15,
    module: 45,
    title: "Evolución del cloud y su seguridad",
    events: [
      { year: 2006, title: "AWS", desc: "Amazon lanza S3 y EC2; nace la nube pública moderna y un nuevo modelo de responsabilidad.", impact: "high" },
      { year: 2010, title: "Azure", desc: "Microsoft entra al cloud; comienza la era multi-proveedor empresarial.", impact: "medium" },
      { year: 2013, title: "Docker", desc: "Populariza los contenedores; cambia cómo se empaqueta y despliega el software.", impact: "high" },
      { year: 2014, title: "Kubernetes", desc: "Google libera el orquestador que se vuelve el estándar de facto cloud-native.", impact: "high" },
      { year: 2017, title: "Brechas por misconfiguración", desc: "Filtraciones masivas por buckets S3 públicos consagran la config del cliente como el riesgo #1.", impact: "high" },
      { year: 2019, title: "Capital One (SSRF a la nube)", desc: "Un SSRF roba credenciales IAM de AWS; hito de la seguridad cloud y el SSRF.", impact: "high" },
      { year: 2022, title: "CSPM y DevSecOps", desc: "El escaneo continuo de postura y el shift-left se vuelven estándar para domar la complejidad cloud.", impact: "medium" },
    ],
  },
];

export function timelinesByModule(moduleId: number): HistoryTimeline[] {
  return TIMELINES.filter((t) => t.module === moduleId);
}
